// =========================================================
// The full walk: every qualifying bill of the 25th Knesset.
// =========================================================
// Applies Lotem's STRICT entry rule ( 2026-08-12 ) and writes a
// THIN facts file per entering bill - official name, committee,
// status, stages with real discussion dates, initiators, and the
// Knesset's official summary when one exists. No vote tallies:
// those stay an enhancement of the curated bills ( sync-bill ),
// so a full walk never hammers the undocumented votes API.
//
// The entry rule, spelled out:
//   a bill enters only with EVIDENCE it moved PAST its first
//   hurdle - the preliminary reading for private bills, the
//   first reading for government and committee bills. A bill
//   rejected at the door never enters. A bill that entered and
//   then left ( merged / stopped / split ) enters WITH its
//   off-pipeline reason - it stays on the site with an
//   explanation, per the departed-bills rule.
//
// Politeness: everything is fetched in batches of 40 ids, four
// requests in flight at most. A full run is a few hundred
// requests, run nightly - not per visitor.
//
// Run it:  node scripts/sync-all.mjs
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { knesset, anyOf } from "./knesset-api.mjs";
import { COMMITTEE_BY_KNESSET_ID, TYPE_BY_SUBTYPE } from "./knesset-maps.mjs";
import { OFF_PIPELINE, STATUS_PASSED, stageForStatus, stageIndex } from "./status-map.mjs";
import { completedDateOf, deriveStages } from "./derive-stages.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(HERE, "../src/content/bills/facts");
const EDITORIAL_DIR = resolve(HERE, "../src/content/bills/editorial");

const CHUNK = 40; // ids per request - keeps URLs comfortably short
const POOL = 4;   // requests in flight

const iso = (d) => (d ? String(d).slice(0, 10) : null);
const hhmm = (d) => (d ? String(d).slice(11, 16) : null);

const PRELIM = stageIndex("preliminary");
const FIRST = stageIndex("first");

function chunked(list, size = CHUNK) {
  const out = [];
  for (let i = 0; i < list.length; i += size) out.push(list.slice(i, i + size));
  return out;
}

// Run tasks with a small concurrency pool, in order of submission.
async function withPool(tasks, onProgress) {
  const results = [];
  let next = 0;
  async function worker() {
    for (;;) {
      const index = next++;
      if (index >= tasks.length) return;
      results[index] = await tasks[index]();
      onProgress?.(index + 1, tasks.length);
    }
  }
  await Promise.all(Array.from({ length: Math.min(POOL, tasks.length) }, worker));
  return results;
}

function progressLogger(label) {
  return (done, total) => {
    if (done % 25 === 0 || done === total) console.log(`  ${label}: ${done}/${total}`);
  };
}

// The curated bills are synced richly by sync-bill ( with votes )
// and must never be overwritten by the thin walk. Their ids are
// read from the editorial files themselves - the one registry
// that cannot drift.
async function curatedBillIds() {
  const ids = new Set();
  for (const file of await readdir(EDITORIAL_DIR)) {
    if (!file.endsWith(".ts")) continue;
    const source = await readFile(resolve(EDITORIAL_DIR, file), "utf8");
    const match = source.match(/billId:\s*(\d+)/);
    if (match) ids.add(Number(match[1]));
  }
  return ids;
}

function toTypeScript(facts) {
  const body = JSON.stringify(facts, null, 2)
    .replace(/^(\s*)"([A-Za-z_][A-Za-z0-9_]*)":/gm, "$1$2:");

  return `// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = ${body};
`;
}

// Writing is diff-aware: syncedAt changes on every run, so two
// versions are compared WITHOUT it - a file is rewritten only
// when something real moved. This is what lets the nightly job
// say "nothing changed, nothing committed" and mean it.
async function writeIfChanged(path, content) {
  const stripSyncedAt = (s) => s.replace(/^\s*syncedAt: ".*",?$/m, "");
  try {
    const existing = await readFile(path, "utf8");
    if (stripSyncedAt(existing) === stripSyncedAt(content)) return "unchanged";
  } catch {
    // New file - fall through and write it.
  }
  await writeFile(path, content, "utf8");
  return "written";
}

async function main() {
  const startedAt = Date.now();
  const today = iso(new Date().toISOString());

  console.log("Fetching every bill of Knesset 25...");
  const bills = await knesset.parliament("KNS_Bill", {
    $filter: "KnessetNum eq 25",
    $select: "BillID,Name,SubTypeDesc,StatusID,CommitteeID,SummaryLaw,LastUpdatedDate",
  });
  console.log(`  ${bills.length} bills`);

  // ─── The gate, part 1: current status ────────────────────
  const skips = (b) => b.SubTypeDesc === "ממשלתית" || b.SubTypeDesc === "ועדה";
  const certain = []; // passed, or clearly past the hurdle
  const departed = []; // off-pipeline now - history decides
  for (const b of bills) {
    if (b.StatusID === STATUS_PASSED) { certain.push(b); continue; }
    if (OFF_PIPELINE[b.StatusID]) { departed.push(b); continue; }
    const stage = stageForStatus(b.StatusID);
    if (stage && stageIndex(stage) > (skips(b) ? FIRST : PRELIM)) certain.push(b);
  }
  console.log(`  ${certain.length} certain + ${departed.length} departed to resolve`);

  // ─── History for everyone we may keep ────────────────────
  const candidates = [...certain, ...departed];
  const candidateIds = candidates.map((b) => b.BillID);

  const plmByBill = new Map(); // BillID -> [{ PlenumSessionID, StatusID }]
  const cmtByBill = new Map(); // BillID -> [CommitteeSessionID]

  const itemTasks = chunked(candidateIds).map((ids) => async () => {
    const [plm, cmt] = await Promise.all([
      knesset.parliament("KNS_PlmSessionItem", {
        $filter: anyOf("ItemID", ids),
        $select: "ItemID,PlenumSessionID,StatusID",
      }),
      knesset.parliament("KNS_CmtSessionItem", {
        $filter: anyOf("ItemID", ids),
        $select: "ItemID,CommitteeSessionID",
      }),
    ]);
    for (const row of plm) {
      if (!plmByBill.has(row.ItemID)) plmByBill.set(row.ItemID, []);
      plmByBill.get(row.ItemID).push(row);
    }
    for (const row of cmt) {
      if (!cmtByBill.has(row.ItemID)) cmtByBill.set(row.ItemID, []);
      cmtByBill.get(row.ItemID).push(row.CommitteeSessionID);
    }
  });
  console.log("Fetching plenum + committee history...");
  await withPool(itemTasks, progressLogger("history chunks"));

  // ─── The gate, part 2: the departed ──────────────────────
  const maxPlenumStage = (billId) => {
    let max = -1;
    for (const row of plmByBill.get(billId) ?? []) {
      const stage = stageForStatus(row.StatusID);
      if (stage) max = Math.max(max, stageIndex(stage));
    }
    return max;
  };
  const entering = [...certain];
  let diedAtDoor = 0;
  for (const b of departed) {
    const entered = skips(b)
      ? maxPlenumStage(b.BillID) > FIRST
      : maxPlenumStage(b.BillID) > PRELIM || (cmtByBill.get(b.BillID) ?? []).length > 0;
    if (entered) entering.push(b);
    else diedAtDoor++;
  }
  console.log(`  entering: ${entering.length} | died at the door: ${diedAtDoor}`);

  // ─── Session dates ───────────────────────────────────────
  const enteringIds = new Set(entering.map((b) => b.BillID));
  const plenumIds = new Set();
  const cmtIds = new Set();
  for (const b of entering) {
    for (const row of plmByBill.get(b.BillID) ?? []) plenumIds.add(row.PlenumSessionID);
    for (const id of cmtByBill.get(b.BillID) ?? []) cmtIds.add(id);
  }

  const plenumDates = new Map(); // PlenumSessionID -> ISO date
  const cmtSessions = new Map(); // CommitteeSessionID -> { date, time }

  const plenumTasks = chunked([...plenumIds]).map((ids) => async () => {
    const rows = await knesset.parliament("KNS_PlenumSession", {
      $filter: anyOf("PlenumSessionID", ids),
      $select: "PlenumSessionID,StartDate",
    });
    for (const r of rows) plenumDates.set(r.PlenumSessionID, iso(r.StartDate));
  });
  const cmtTasks = chunked([...cmtIds]).map((ids) => async () => {
    const rows = await knesset.parliament("KNS_CommitteeSession", {
      $filter: anyOf("CommitteeSessionID", ids),
      $select: "CommitteeSessionID,StartDate",
    });
    for (const r of rows) {
      cmtSessions.set(r.CommitteeSessionID, { date: iso(r.StartDate), time: hhmm(r.StartDate) });
    }
  });
  console.log(`Fetching ${plenumIds.size} plenum + ${cmtIds.size} committee session dates...`);
  await withPool([...plenumTasks, ...cmtTasks], progressLogger("session chunks"));

  // ─── Initiators ( private bills only ) ───────────────────
  const privateIds = entering.filter((b) => !skips(b)).map((b) => b.BillID);
  const initiatorRows = new Map(); // BillID -> rows
  const initiatorTasks = chunked(privateIds).map((ids) => async () => {
    const rows = await knesset.parliament("KNS_BillInitiator", {
      $filter: anyOf("BillID", ids),
      $select: "BillID,PersonID,IsInitiator,Ordinal",
    });
    for (const r of rows) {
      if (!r.IsInitiator) continue;
      if (!initiatorRows.has(r.BillID)) initiatorRows.set(r.BillID, []);
      initiatorRows.get(r.BillID).push(r);
    }
  });
  console.log(`Fetching initiators for ${privateIds.length} private bills...`);
  await withPool(initiatorTasks, progressLogger("initiator chunks"));

  // The rail shows at most three leaders per bill.
  const leadIds = new Set();
  for (const rows of initiatorRows.values()) {
    rows.sort((a, b) => (a.Ordinal ?? 99) - (b.Ordinal ?? 99));
    for (const r of rows.slice(0, 3)) leadIds.add(r.PersonID);
  }

  const people = new Map(); // PersonID -> full name
  const factions = new Map(); // PersonID -> faction name
  const personTasks = chunked([...leadIds]).map((ids) => async () => {
    const rows = await knesset.parliament("KNS_Person", {
      $filter: anyOf("PersonID", ids),
      $select: "PersonID,FirstName,LastName",
    });
    for (const r of rows) people.set(r.PersonID, `${r.FirstName} ${r.LastName}`.trim());
  });
  const positionTasks = chunked([...leadIds]).map((ids) => async () => {
    const rows = await knesset.parliament("KNS_PersonToPosition", {
      $filter: `(${anyOf("PersonID", ids)}) and KnessetNum eq 25`,
      $select: "PersonID,FactionName",
    });
    for (const r of rows) {
      if (r.FactionName && !factions.has(r.PersonID)) factions.set(r.PersonID, r.FactionName.trim());
    }
  });
  console.log(`Fetching ${leadIds.size} lead initiators...`);
  await withPool([...personTasks, ...positionTasks], progressLogger("person chunks"));

  // partyIdForFaction lives in knesset-maps; imported lazily here
  // to keep the top import list honest about heavy use.
  const { partyIdForFaction, ministryDisplayName } = await import("./knesset-maps.mjs");

  // ─── Special committees ──────────────────────────────────
  const unmappedCommitteeIds = [
    ...new Set(
      entering
        .map((b) => b.CommitteeID)
        .filter((id) => id && !COMMITTEE_BY_KNESSET_ID[id]),
    ),
  ];
  const committeeNames = new Map();
  if (unmappedCommitteeIds.length) {
    const rows = await knesset.parliament("KNS_Committee", {
      $filter: anyOf("CommitteeID", unmappedCommitteeIds),
      $select: "CommitteeID,Name",
    });
    for (const r of rows) committeeNames.set(r.CommitteeID, r.Name?.trim());
    console.log(`  ${unmappedCommitteeIds.length} ad-hoc committees -> the "special" bucket`);
  }

  // ─── Emit ────────────────────────────────────────────────
  const curated = await curatedBillIds();
  await mkdir(OUT_DIR, { recursive: true });

  let written = 0;
  let unchanged = 0;
  let skippedCurated = 0;

  for (const b of entering) {
    if (curated.has(b.BillID)) { skippedCurated++; continue; }

    const milestones = (plmByBill.get(b.BillID) ?? [])
      .map((row) => ({
        statusId: row.StatusID,
        stage: stageForStatus(row.StatusID),
        offPipeline: OFF_PIPELINE[row.StatusID] ?? null,
        date: plenumDates.get(row.PlenumSessionID) ?? null,
      }))
      .filter((m) => m.date)
      .sort((a, b2) => a.date.localeCompare(b2.date));

    const discussions = (cmtByBill.get(b.BillID) ?? [])
      .map((sessionId) => ({ sessionId, ...(cmtSessions.get(sessionId) ?? {}) }))
      .filter((d) => d.date)
      .sort((a, b2) => a.date.localeCompare(b2.date));

    const stages = deriveStages(milestones, discussions, b.StatusID);
    const offPipelineReason = OFF_PIPELINE[b.StatusID] ?? undefined;

    const mappedCommittee = b.CommitteeID ? COMMITTEE_BY_KNESSET_ID[b.CommitteeID] : undefined;
    const committeeId = mappedCommittee ?? (b.CommitteeID ? "special" : undefined);
    const committeeName = committeeId === "special" ? committeeNames.get(b.CommitteeID) : undefined;

    const type = TYPE_BY_SUBTYPE[b.SubTypeDesc] ?? "private";
    let initiators;
    if (type === "governmental") {
      initiators = [{ kind: "ministry", name: ministryDisplayName(null) }];
    } else if (type === "committee") {
      initiators = [];
    } else {
      initiators = (initiatorRows.get(b.BillID) ?? []).slice(0, 3).map((r) => ({
        kind: "mk",
        personId: r.PersonID,
        name: people.get(r.PersonID) ?? `#${r.PersonID}`,
        partyId: partyIdForFaction(factions.get(r.PersonID)) ?? undefined,
        factionName: factions.get(r.PersonID) ?? undefined,
      }));
    }

    const facts = {
      billId: b.BillID,
      syncedAt: today,
      officialName: b.Name,
      type,
      committeeId,
      committeeName,
      status: b.StatusID === STATUS_PASSED ? "completed" : offPipelineReason ? "dropped" : "agenda",
      offPipelineReason,
      summaryOfficial: b.SummaryLaw?.trim() || undefined,
      lastUpdated: iso(b.LastUpdatedDate),
      completedDate: completedDateOf(milestones, b.StatusID),
      initiators,
      stages,
    };

    const outcome = await writeIfChanged(
      resolve(OUT_DIR, `${b.BillID}.ts`),
      toTypeScript(facts),
    );
    if (outcome === "written") written++;
    else unchanged++;
  }

  const seconds = ((Date.now() - startedAt) / 1000).toFixed(0);
  console.log(`\nDone in ${seconds}s:`);
  console.log(`  ${entering.length} bills on the site`);
  console.log(`  ${written} files written | ${unchanged} unchanged | ${skippedCurated} curated ( sync-bill's territory )`);
  void enteringIds;
}

main().catch((err) => {
  console.error("SYNC-ALL FAILED:", err.message);
  process.exit(1);
});
