// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 1046296,
  syncedAt: "2026-08-12",
  officialName: "חוק העונשין (תיקון מס' 154), התשפ\"ו-2026",
  type: "governmental",
  committeeId: "foreign-defense",
  status: "completed",
  summaryOfficial: "תיקון מספר 154 לחוק העונשין מוסיף לחוק סימן חדש של פגיעה בריבונות המדינה באמצעות הכנסה או הוצאה של דבר בגבולות, וקובע בו עבירה של פגיעה בריבונות המדינה בגבולות, האוסרת על הכנסת דבר לישראל או הוצאתו ממנה שלא כדין ושלא דרך תחנת גבול, שעונשה יעמוד על 9 שנות מאסר. בנוסף, החוק מתקן את חוק סדר הדין הפלילי (מעצרים), כך שיחולו על עבירה זו הוראות המעצר הייעודיות לעבירות ביטחון.",
  lastUpdated: "2026-07-22",
  completedDate: "2026-06-08",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2026-01-19",
          time: "12:15",
          sessionId: 2239456
        },
        {
          date: "2026-05-13",
          time: "09:00",
          sessionId: 2242881
        },
        {
          date: "2026-05-14",
          time: "09:30",
          sessionId: 2243129
        },
        {
          date: "2026-05-14",
          time: "12:45",
          sessionId: 2243199
        },
        {
          date: "2026-05-20",
          time: "10:30",
          sessionId: 2243306
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
