// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 1046679,
  syncedAt: "2026-08-12",
  officialName: "חוק התקציב לשנת הכספים 2026, התשפ\"ו-2026",
  type: "governmental",
  committeeId: "finance",
  status: "completed",
  lastUpdated: "2026-07-09",
  completedDate: "2026-03-29",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2026-03-05",
          time: "14:35",
          sessionId: 2241332
        },
        {
          date: "2026-03-08",
          time: "15:30",
          sessionId: 2241398
        },
        {
          date: "2026-03-09",
          time: "10:00",
          sessionId: 2241399
        },
        {
          date: "2026-03-09",
          time: "19:00",
          sessionId: 2241471
        },
        {
          date: "2026-03-10",
          time: "14:00",
          sessionId: 2241393
        },
        {
          date: "2026-03-11",
          time: "09:00",
          sessionId: 2241403
        },
        {
          date: "2026-03-11",
          time: "17:00",
          sessionId: 2241523
        },
        {
          date: "2026-03-12",
          time: "10:00",
          sessionId: 2241402
        },
        {
          date: "2026-03-15",
          time: "16:00",
          sessionId: 2241643
        },
        {
          date: "2026-03-16",
          time: "18:00",
          sessionId: 2241647
        },
        {
          date: "2026-03-17",
          time: "19:00",
          sessionId: 2241795
        },
        {
          date: "2026-03-18",
          time: "09:00",
          sessionId: 2241649
        },
        {
          date: "2026-03-18",
          time: "19:30",
          sessionId: 2241832
        },
        {
          date: "2026-03-19",
          time: "19:00",
          sessionId: 2241651
        },
        {
          date: "2026-03-22",
          time: "10:00",
          sessionId: 2241950
        },
        {
          date: "2026-03-22",
          time: "18:00",
          sessionId: 2241951
        },
        {
          date: "2026-03-23",
          time: "08:30",
          sessionId: 2242021
        },
        {
          date: "2026-03-25",
          time: "10:00",
          sessionId: 2242119
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
