// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 1046710,
  syncedAt: "2026-09-17",
  officialName: "חוק הביטוח הלאומי (תיקון מס' 265), התשפ\"ו-2026",
  type: "governmental",
  committeeId: "labor-welfare",
  status: "completed",
  summaryOfficial: "החוק קובע, כהוראה קבועה, כי המוסד לביטוח לאומי ישפה מעסיק של עובד המשרת במילואים בשל תשלומים ששילם המעסיק לקופת גמל או קרן פנסיה או כדמי ביטוח לאומי בעד עובדו בתקופת שירותו במילואים, החל מיום 1.4.2026. השיפוי יהיה בסכום השווה ל-20% מהכנסתו של העובד ליום כפול מספר ימי שירות המילואים לפי החישוב המפורט בחוק. השיפוי לא יינתן למעסיק שהוא \"מעביד ציבורי\" - דהיינו המדינה, גוף מתוקצב, תאגיד בריאות או קופת חולים. אוצר המדינה באמצעות תקציב הביטחון ישפה את המוסד לביטוח לאומי על התשלומים. נקבע כי במקרה שיותקנו תקנות לפי סעיף 376 לחוק הביטוח הלאומי לשיפוי מעסיקים על תשלומים סוציאליים לגבי שירות מילואים שהוא שירות חירום, יחולו לגבי השיפוי בשל אותו שירות מילואים ההוראות שייקבעו באותן תקנות (במקום הסדר השיפוי שנקבע כאמור). \nבנוסף נקבע כהוראת שעה כי נדרש היתר מוועדת תעסוקה לפיטורים או הוצאה לחל\"ת ממושך (חל\"ת שהוא בלתי מוגבל בזמן או ל-30 ימים לפחות, לרבת חל\"ת שהחל מ1 בינואר 2026 לתקופה בלתי מוגבלת או לתקופה שסיומה הוא לאחר ה29.4.2026) של עובד שעמו ילד עד גיל 14 וזאת אם בן זוגו או הורהו האחר של ילדו נמצא בשירות מילואים לפי צו 8 או שמשכו 21 ימים רצופים לפחות, או שטרם חלפו 14 ימים מסיום שירות המילואים, ובכפוף לכך שהעובד מסר למעסיקו הודעה על כך כנדרש בחוק. תוקף הוראת שעה זו יהיה עד תום 30 ימים מפקיעת ההכרזה על מצב מיוחד בעורף במבצע שאגת הארי, והשר יוכל להאריך את תוקפה עד שנה נוספת.",
  lastUpdated: "2026-09-16",
  completedDate: "2026-04-27",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2026-03-24",
          time: "19:45",
          sessionId: 2242111
        },
        {
          date: "2026-03-25",
          time: "19:00",
          sessionId: 2242118
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
