// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 1046189,
  syncedAt: "2026-08-12",
  officialName: "חוק מס חברות מזערי בקבוצה רב-לאומית, התשפ\"ו-2025",
  type: "governmental",
  committeeId: "finance",
  status: "completed",
  lastUpdated: "2026-01-01",
  completedDate: "2025-12-29",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-12-09",
          time: "14:10",
          sessionId: 2237584
        },
        {
          date: "2025-12-14",
          time: "09:00",
          sessionId: 2237801
        },
        {
          date: "2025-12-16",
          time: "14:00",
          sessionId: 2237808
        },
        {
          date: "2025-12-22",
          time: "09:15",
          sessionId: 2238102
        },
        {
          date: "2025-12-23",
          time: "09:15",
          sessionId: 2238106
        },
        {
          date: "2025-12-24",
          time: "09:00",
          sessionId: 2238112
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
