// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 1056885,
  syncedAt: "2026-08-12",
  officialName: "חוק הסכמים קיבוציים (תיקון מס' 12 - הוראת שעה) (הוראות מיוחדות לעניין הרחבת הסכם קיבוצי כללי שנעשה בשל המצב המיוחד בעורף), התשפ\"ו-2026",
  type: "governmental",
  committeeId: "labor-welfare",
  status: "completed",
  summaryOfficial: "החוק קובע בהוראת שעה הליך מקוצר כמפורט להלן למתן צווי הרחבה להסכמים קיבוציים שנחתמו בשל המצב המיוחד בעורף שהוכרז ביום 28.2.2026. תוקף הוראת השעה עד שלושה חודשים מסיום ההכרזה על המצב המיוחד בעורף.\nלפי הוראת השעה, הודעה על כוונה לתת צו הרחבה להסכם קיבוצי שנעשה בשל המצב המיוחד בעורף תפורסם ברשומות ותציין כי ההסכם נעשה בשל המצב המיוחד בעורף וכי יש דחיפות בהרחבתו, ערר לעניין הכוונה לתת צו הרחבה יוגש בתוך 4 ימים מפרסום ההודעה ושר העבודה רשאי לחתום על צו ההרחבה בחלוף  7 ימים מפרסום ההודעה. שהמועד להגשת טענת כשרות בקשר לרישום ההסכם הקיבוצי יהיה לכל המאוחר המועד להגשת ערר על מתן צו ההרחבה, ורישום ההסכם הקיבוצי יוכל להתבצע עד למועד מתן צו ההרחבה.\nההליכים המקוצרים הוחלו, בשינויים מסוימים, גם על ההסכם הקיבוצי בעניין משרתי מילואים, בני זוגם וצבירת חופשה שהודעה על כוונה לתת צו הרחבה לגביו פורסמה ביום 3.3.2026.",
  lastUpdated: "2026-06-28",
  completedDate: "2026-03-23",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2026-03-22",
          time: "09:00",
          sessionId: 2241922
        },
        {
          date: "2026-03-23",
          time: "13:00",
          sessionId: 2242041
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
