// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 1057297,
  syncedAt: "2026-08-12",
  officialName: "חוק כליאתם של לוחמים בלתי חוקיים (תיקון מס' 4 והוראת שעה – חרבות ברזל) (תיקון מס' 8), התשפ\"ו-2026",
  type: "governmental",
  committeeId: "foreign-defense",
  status: "completed",
  summaryOfficial: "חוק כליאתם של לוחמים בלתי חוקיים, התשס\"ב–2002, מסדיר את כליאתם של מי שנטלו חלק בפעולות איבה נגד מדינת ישראל או נמנו עם כוחות המבצעים פעולות איבה, ואינם מוגדרים כשבויי מלחמה. החוק קובע הליך מוסדר להוצאת צווי כליאה ומנגנוני בקרה וביקורת שיפוטית, וכולל הסדר מיוחד למקרים שבהם הממשלה הכריזה על מלחמה או על פעולות צבאיות משמעותיות. בשל היקף העצורים הרב במלחמת חרבות ברזל, נקבעה הוראת שעה שהאריכה את התקופות המנויות בחוק והתאימה את הדרגים המאשרים. כעת, במסגרת חוק כליאתם של לוחמים בלתי חוקיים (תיקון מס' 4 והוראת שעה – חרבות ברזל) (תיקון מס' 8), התשפ\"ו–2026, הוארך תוקפה של הוראת השעה לעניין כליאתם של לוחמים בלתי חוקיים עד ליום י\"ט בתשרי התשפ\"ז (30 בספטמבר 2026), ובמקביל הוארך עד לאותו מועד גם תוקפה של ההכרזה מכוח החוק. לצד הארכות אלו, תוקנה הוראת השעה כך שקוצרו פרקי הזמן המרביים הקבועים בה לעניין הוצאת צווי כליאה קבועים, קיום ביקורת שיפוטית, מניעת מפגש של כלוא עם עורך דין וכליאתם של קטינים.",
  lastUpdated: "2026-07-22",
  completedDate: "2026-06-24",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2026-06-23",
          time: "11:30",
          sessionId: 2244471
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
