// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2161081,
  syncedAt: "2026-08-12",
  officialName: "חוק עבודת הנוער (תיקון מס' 21), התשפ\"ג-2023",
  type: "private",
  committeeId: "children-rights",
  status: "completed",
  summaryOfficial: "החוק קובע שכל העסקה של נער בגילאי 15 עד 18 בתחום הדוגמנות או הצילומים, לרבות בשלבים מוקדמים של ההעסקה כגון תיווך להעסקה ומבחני במה, ייעשו בכפוף לאישור של הנער והורהו או האפוטרופוס. האישור יינתן בכתב בהתאם לטופס מובנה שיפורסם באתר משרד הכלכלה. כמו כן, במקרה של תיווך או העסקה חוזרת אצל אותו מתווך או מעסיק בתוך תקופה של שנה, ההסכמה יכולה להינתן באמצעות מסרון או אמצעי דיגיטלי אחר שהמתווך או המעסיק יוכלו לשמור אותו. כמו כן נקבע שמעסיק הפועל בניגוד לאמור עובר עבירה שדינה קנס או מאסר, ושלהורה או לבן משפחה בגיר אחר יש זכות להיות נוכח בזמן ובמקום שבהם מועסק הנער.",
  lastUpdated: "2023-08-06",
  completedDate: "2023-07-30",
  initiators: [
    {
      kind: "mk",
      personId: 30780,
      name: "רון כץ",
      partyId: "yesh-atid",
      factionName: "יש עתיד"
    },
    {
      kind: "mk",
      personId: 30722,
      name: "יבגני סובה",
      partyId: "yisrael-beiteinu",
      factionName: "ישראל ביתנו"
    },
    {
      kind: "mk",
      personId: 23560,
      name: "יוליה מלינובסקי",
      partyId: "yisrael-beiteinu",
      factionName: "ישראל ביתנו"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2022-02-07",
          time: "13:00",
          sessionId: 2169589
        },
        {
          date: "2022-02-07",
          time: "10:30",
          sessionId: 2169803
        },
        {
          date: "2022-02-16",
          time: "09:30",
          sessionId: 2169993
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2022-06-29",
          time: "13:00",
          sessionId: 2194754
        },
        {
          date: "2023-07-17",
          time: "12:00",
          sessionId: 2208709
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
