// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2163229,
  syncedAt: "2026-08-12",
  officialName: "חוק הרשות הלאומית לביטחון קהילתי (תיקון מס' 2), התשפ\"ד-2023",
  type: "governmental",
  committeeId: "national-security",
  status: "completed",
  summaryOfficial: "נקבעו תיקוני חקיקה המשלימים להחלטת הממשלה בדבר סגירת המשרד לחיזוק וקידום קהילתי והעברת הרשות לביטחון קהילתי למשרד לביטחון הפנים.",
  lastUpdated: "2025-12-10",
  completedDate: "2023-11-06",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2022-05-16",
          time: "11:15",
          sessionId: 2192217
        },
        {
          date: "2022-06-01",
          time: "09:30",
          sessionId: 2192730
        },
        {
          date: "2023-02-15",
          time: "09:30",
          sessionId: 2201739
        },
        {
          date: "2023-05-08",
          time: "12:00",
          sessionId: 2204757
        },
        {
          date: "2023-06-07",
          time: "09:00",
          sessionId: 2206210
        },
        {
          date: "2023-06-13",
          time: "11:30",
          sessionId: 2206736
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
