// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2165539,
  syncedAt: "2026-08-12",
  officialName: "חוק הטיס (תיקון מס' 4), התשפ\"ד-2024",
  type: "governmental",
  committeeId: "economy",
  status: "completed",
  summaryOfficial: "החוק מרחיב את סמכותו של מנהל רשות התעופה האזרחית בסעיף 165 לחוק הטיס, התשע\"א–2011 (להלן – חוק הטיס), לתת פטור מהוראות החוק, כך שיהיה מוסמך לתת פטור גם מהוראות סעיף 35 לחוק הטיס לעניין הפעלת מיתקן עזר לטיסה.\nסעיף 165 לחוק הטיס מסמיך את מנהל רשות התעופה האזרחית לתת פטור מהוראות לפי חוק הטיס, רק לגבי רשימת סעיפים המנויה בסעיף, בהתקיים נסיבות המפורטות בסעיף ובכפוף לכך שיינקטו צעדים מתאימים לשמירה על בטיחות הטיסה וסדירותה. סעיף 35 לחוק הטיס, קובע כי הפעלת מיתקן עזר לטיסה, המשמש או המיועד לשמש כלי טיס אזרחיים, טעונה אישור מנהל רשות התעופה האזרחית לכך שהמיתקן בנוי או מותקן, מתוחזק ומופעל בהתאם לתנאי האישור. האישור ניתן, ככלל, לאחר שהמנהל נוכח כי מתקיימות לגבי המיתקן דרישות ארגון התעופה הבינלאומי.\nנכון להיום, קיימים ברשות שדות התעופה מיתקנים שאינם עומדים, מבחינת ביצועים ותחזוקה, בדרישות ארגון התעופה העולמי, ולפיכך מנהל רשות התעופה האזרחית אינו יכול לאשרם לפי סעיף 35 לחוק הטיס. עם זאת, לרשות שדות התעופה אין ברירה אלא להמשיך שימוש במיתקנים כאמור עד להחלפתם העתידית, שכן הימנעות משימוש בהם, משמעותה הפסקת הפעילות האווירית האזרחית. עם כניסתו לתוקף, יאפשר החוק למנהל רשות התעופה האזרחית לתת פטור למיתקנים האמורים מקיום הוראות סעיף 35 לחוק הטיס.",
  lastUpdated: "2024-01-16",
  completedDate: "2024-01-01",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-07-04",
          time: "12:30",
          sessionId: 2208113
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
