// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2169199,
  syncedAt: "2026-08-12",
  officialName: "חוק הסיוע המשפטי (תיקון מס' 26 והוראת שעה), התשפ\"ד-2024",
  type: "governmental",
  committeeId: "constitution",
  status: "completed",
  summaryOfficial: "החוק מעגן סיוע משפטי למשפחותיהם של נפגעי עבירות המתה לרבות ליווי וקבלת ייעוץ וסיוע במימוש זכויותיהם בהליכים המשפטיים. החוק מרחיב את רשימת עבירות המין שבעניינן ניתן לקבל סיוע משפטי. בנוסף, החוק קובע הוראת שעה לפיה יורחב הסיוע המשפטי הניתן לנפגעי עבירות מין ועבירות של סחר בבני אדם, כך שיחול כבר משלב החקירה וגם על הליכים אזרחיים הנובעים מהעבירה.",
  lastUpdated: "2025-02-23",
  completedDate: "2024-07-24",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-07-02",
          time: "12:10",
          sessionId: 2219402
        },
        {
          date: "2024-07-02",
          time: "12:37",
          sessionId: 2220166
        },
        {
          date: "2024-07-11",
          time: "08:30",
          sessionId: 2220436
        },
        {
          date: "2024-07-17",
          time: "08:30",
          sessionId: 2220876
        },
        {
          date: "2024-07-21",
          time: "12:20",
          sessionId: 2221084
        },
        {
          date: "2024-07-22",
          time: "08:45",
          sessionId: 2221094
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
