// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2194824,
  syncedAt: "2026-08-12",
  officialName: "חוק למניעת אלימות במשפחה (תיקון מס' 19 – הוראת שעה), התשפ\"ג–2023 ",
  type: "governmental",
  committeeId: "national-security",
  status: "completed",
  summaryOfficial: "החוק מסדיר את סמכותו של בית המשפט לתת צו הגנה בתנאי פיקוח טכנולוגי במסגרת הגנה על בני משפחה מפני אלימות, וקובע את הסדרים אלו כהוראת שעה למשך שלוש שנים מיום תחילת החוק. ראשית, החוק קובע שלושה תנאים שעל בית המשפט לבחון בבואו לתן צו הגנה בתנאי פיקוח טכנולוגי, וכן קובע חריג לתנאים אלו במצבים בהם נשקפת סכנה גבוהה או חשש ממשי לחיי בן המשפחה. שנית, נקבע כי בסמכות השר לביטחון לאומי לקבוע בצו את המספר המרבי של אמצעי פיקוח טכנולוגי שניתן לעשות בהם שימוש, וכי מספר זה יעלה על המספר שנקבע בשנה הקודמת. עוד נקבע כי בית המשפט יורה על ביצוע הערכת מסוכנות של מי שכלפיו מבוקש הצו, וכן כי מכסת הערכות המסוכנות תקבע לכל שנה על ידי שר הרווחה והביטחון החברתי, ובלבד שלא תפחת מהמכסה שנקבעה בשנה הקודמת. בנוסף, תוקם יחידת פיקוח טכנולוגי בשירות בתי הסוהר, והיא תהיה אמונה על פיקוח ואכיפה של צווים שניתנו בתנאי פיקוח טכנולוגי. ביחידת הפיקוח הטכנולוגי יעבדו הן עובדי מדינה, והן עובדים מחברה מפעילה אשר ימלאו תפקידי טכנאות וסיוע אזרחי. לבסוף, נקבעה חובת דיווח שנתית על השר לביטחון לאומי לוועדה לביטחון לאומי של הכנסת בדבר קיום החוק, לצד הקמת ועדת היגוי לשם ביצוע מחקר מלווה. לצד זאת, בתום שנה מיום תחילת החוק תבחן הוועדה לביטחון לאומי של הכנסת את האפשרות להאריך את תוקפו של צו הגנה בתנאי פיקוח טכנולוגי שניתן ללא הערכת מסוכנות, ואת פרק הזמן להגשת הערכת המסוכנות לבית המשפט.",
  lastUpdated: "2026-04-20",
  completedDate: "2023-07-30",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2022-06-30",
          time: "13:50",
          sessionId: 2194856
        },
        {
          date: "2023-07-10",
          time: "11:30",
          sessionId: 2208371
        },
        {
          date: "2023-07-12",
          time: "09:00",
          sessionId: 2208738
        },
        {
          date: "2023-07-16",
          time: "10:00",
          sessionId: 2208764
        },
        {
          date: "2023-07-17",
          time: "12:00",
          sessionId: 2209068
        },
        {
          date: "2023-07-19",
          time: "08:30",
          sessionId: 2208770
        },
        {
          date: "2023-07-20",
          time: "08:30",
          sessionId: 2209252
        },
        {
          date: "2024-01-08",
          time: "09:00",
          sessionId: 2213217
        },
        {
          date: "2024-03-14",
          time: "14:00",
          sessionId: 2215748
        },
        {
          date: "2024-05-07",
          time: "10:30",
          sessionId: 2217709
        },
        {
          date: "2025-07-21",
          time: "10:15",
          sessionId: 2231629
        },
        {
          date: "2025-08-13",
          time: "10:00",
          sessionId: 2234793
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
