// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2195806,
  syncedAt: "2026-08-12",
  officialName: "חוק יום בריאות הנפש, התשפ\"ד-2024",
  type: "private",
  committeeId: "education",
  status: "completed",
  summaryOfficial: "נקבע בחוק כי יתקיים בישראל יום ציון שנתי לבריאות הנפש ב-10 באוקטובר, המועד שבו מצוין יום זה בעולם. זאת, לשם הגברת מודעות הציבור לנושא, קידום ההכרה בזכויות של מתמודדי נפש ולשם הפחתת דעות קדומות כלפיהם. יום זה יצוין, בין השאר, במליאת הכנסת, בבית הנשיא, במערכת הבריאות, במשרד הרווחה ובשירותי הרווחה ברשויות המקומיות, במוסד לביטוח לאומי, במשרדי העבודה, השיכון, המשפטים, העלייה והקליטה והתרבות והספורט; כן יצוין בערכאות השיפוט, בצה\"ל ובמשטרה, ברשויות המקומיות, ובמסגרות החינוך הבלתי פורמלי. יום זה יצוין גם במערכת החינוך, אם יחליט על כך שר החינוך. שר הבריאות הוא הממונה על ביצוע החוק.",
  lastUpdated: "2024-08-06",
  completedDate: "2024-07-23",
  initiators: [
    {
      kind: "mk",
      personId: 30810,
      name: "מיכל מרים וולדיגר",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    },
    {
      kind: "mk",
      personId: 30840,
      name: "ואליד אלהואשלה",
      partyId: "raam",
      factionName: "רע\"ם"
    },
    {
      kind: "mk",
      personId: 30830,
      name: "אוהד טל",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-02-26",
          time: "11:30",
          sessionId: 2215598
        },
        {
          date: "2024-03-18",
          time: "11:30",
          sessionId: 2216406
        },
        {
          date: "2024-05-20",
          time: "11:30",
          sessionId: 2217947
        },
        {
          date: "2024-06-10",
          time: "10:00",
          sessionId: 2218744
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-07-21",
          time: "10:30",
          sessionId: 2220926
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
