// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2195431,
  syncedAt: "2026-08-12",
  officialName: "חוק סמכויות לאיסוף ואבחון של נתוני נוסעים הנכנסים לישראל או היוצאים ממנה, התשפ\"ג-2023 ",
  type: "governmental",
  committeeId: "foreign-defense",
  status: "completed",
  summaryOfficial: "החוק מסדיר את הקמתו של מרכז לאומי לאבחון נתוני נוסעים, אשר יקים וינהל מאגר מידע של נתוני הנוסעים והצוות בטיסות המופעלות אל ישראל וממנה. במסגרת זאת, יהיה רשאי ראש המרכז לדרוש מחברת תעופה למסור את נתוני הנוסעים ולהקים ממשק אלקטרוני קבוע בכדי לאפשר הזרמה קבועה ורציפה של המידע, ומידע זה יימסר בשלושה מועדים קבועים לכל טיסה. במסגרת המידע שיימסר ייכללו נתוני API (Advanced Passenger Information), כגון שם הנוסע, תאריך לידה, מין, לאום, מספר דרכון ושם המדינה שהנפיקה את הדרכון, וכן נתוני PNR (Passenger Name Record), כגון מספר טלפון נייד, כתובת דואר אלקטרוני, אמצעי התשלום, תאריכי הנסיעה, מסלול הנסיעה ונתוני הכבודה. ניתן יהיה להשתמש במידע למטרות של מניעה וסיכול טרור ופשיעה חמורה, אבטחת התעופה האזרחית, מאבק בהגירה בלתי חוקית והגנה על בריאות הציבור, והגופים שיהיו רשאים לקבל גישה למאגר יהיו השב\"כ, המוסד, משטרת ישראל, רשות המיסים, רשות האוכלוסין וההגירה, משרד הבריאות ומשרד התחבורה. עוד מוצע להטיל על חברות התעופה חובת יידוע הנוסעים בדבר העברת המידע. בנוסף, נקבעו מנגנונים שנועדו לצמצם את הפגיעה בפרטיות, כגון חובת מינוי ממונה על הגנת הפרטיות במרכז, שמינויו ותנאי כשירותו ייקבעו בעצה אחת עם ראש הרשות להגנת הפרטיות במשרד המשפטים, ושעליו להכין תכנית עבודה שנתית ולהגיש דו\"חות שנתיים על קיום הוראות הגנת הפרטיות במרכז.",
  lastUpdated: "2024-01-15",
  completedDate: "2023-03-29",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2022-09-19",
          time: "10:00",
          sessionId: 2195439
        },
        {
          date: "2023-02-15",
          time: "09:30",
          sessionId: 2201739
        },
        {
          date: "2023-02-20",
          time: "11:00",
          sessionId: 2201838
        },
        {
          date: "2023-02-27",
          time: "12:00",
          sessionId: 2202325
        },
        {
          date: "2023-03-01",
          time: "09:00",
          sessionId: 2202326
        },
        {
          date: "2023-03-14",
          time: "14:00",
          sessionId: 2202682
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
