// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2196572,
  syncedAt: "2026-08-12",
  officialName: "חוק חוזה הביטוח (תיקון מס' 12), התשפ\"ג-2023",
  type: "private",
  committeeId: "constitution",
  status: "completed",
  summaryOfficial: "נקבע כי יש לאפשר העברת מוטבים בין תאגידים בנקאיים במסגרת אותו חוזה ביטוח ובכך לחסוך בירוקרטיה רבה מלווי משכנתאות ולמנוע את החסם הקיים במחזור משכנתאות בשל התקדמות גיל הלווה או שינוי במצב רפואי.",
  lastUpdated: "2024-02-11",
  completedDate: "2023-07-11",
  initiators: [
    {
      kind: "mk",
      personId: 23641,
      name: "יעקב אשר",
      partyId: "utj",
      factionName: "יהדות התורה"
    },
    {
      kind: "mk",
      personId: 526,
      name: "משה גפני",
      partyId: "utj",
      factionName: "יהדות התורה"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-06-05",
          time: "09:30",
          sessionId: 2205659
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-07-09",
          time: "12:30",
          sessionId: 2208405
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
