// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2196090,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק לתיקון פקודת המכס (איסור השמדת טובין חבי מכס), התשפ\"ג-2022",
  type: "private",
  committeeId: "finance",
  status: "agenda",
  lastUpdated: "2025-01-29",
  initiators: [
    {
      kind: "mk",
      personId: 30770,
      name: "יוסף טייב",
      partyId: "shas",
      factionName: "התאחדות הספרדים שומרי תורה תנועתו של מרן הרב עובדיה יוסף זצ\"ל"
    },
    {
      kind: "mk",
      personId: 30719,
      name: "עופר כסיף",
      partyId: "hadash-taal",
      factionName: "חד\"ש-תע\"ל"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: []
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
