// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2196966,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק סדר הדין הפלילי (סמכויות אכיפה - מעצרים) (תיקון - מעצר עד תום ההליכים בגין עבירה של החזקת נשק שלא כדין), התשפ\"ג-2023",
  type: "private",
  committeeId: "constitution",
  status: "agenda",
  lastUpdated: "2024-03-14",
  initiators: [
    {
      kind: "mk",
      personId: 560,
      name: "אחמד טיבי",
      partyId: "hadash-taal",
      factionName: "חד\"ש-תע\"ל"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2023-06-27",
          time: "09:30",
          sessionId: 2206551
        },
        {
          date: "2023-07-04",
          time: "12:00",
          sessionId: 2207874
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
