// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2196745,
  syncedAt: "2026-08-12",
  officialName: "חוק הגנה על זכויות בדירת המשפחה של ילד שהורהו הומת בידי בן זוגו, התשפ\"ד-2024",
  type: "private",
  committeeId: "constitution",
  status: "completed",
  summaryOfficial: "החוק קובע שבמקרה בו אדם מורשע בהמתה של בן זוגו ולבני הזוג יש דירת מגורים משותפת, ההחלטות באשר לניהול הדירה יתקבלו על ידי הילדים המשותפים או ילדי בן הזוג שהומת בלבד, ללא צורך בהסכמת בן הזוג הממית. הילדים יוכלו להחליט לגור בדירה ללא הסכמת בן הזוג הממית כאמור, או לחילופין להשכיר או למכור את הדירה, ואולם החלטה על מכירת הדירה תהיה טעונה את אישורו של בית המשפט. בכל מקרה, ככל שהתקבלה תמורה מהשכרה או ממכירה של הדירה, בן הזוג שהמית יקבלו את חלקו. החוק קובע כי למעט החלטה באשר לעסקה במקרקעין הטעונה רישום, ההסדר יחול כבר מעת הגשת כתב האישום. בנוסף, אם חויב בן הזוג הממית במזונות או במדור עבור הילדים, יוכלו הילדים לקזז את הסכומים המגיעים להם מהכספים להם הוא זכאי מהם כתמורה מהשכרה או מכירה של הדירה.",
  lastUpdated: "2025-02-23",
  completedDate: "2024-07-16",
  initiators: [
    {
      kind: "mk",
      personId: 30067,
      name: "עאידה תומא סלימאן",
      partyId: "hadash-taal",
      factionName: "חד\"ש-תע\"ל"
    },
    {
      kind: "mk",
      personId: 23635,
      name: "פנינה תמנו",
      partyId: "national-unity",
      factionName: "המחנה הממלכתי"
    },
    {
      kind: "mk",
      personId: 30832,
      name: "אליהו רביבו",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-03-11",
          time: "09:00",
          sessionId: 2215509
        },
        {
          date: "2024-05-21",
          time: "11:00",
          sessionId: 2217584
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-06-26",
          time: "09:00",
          sessionId: 2219076
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
