// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2196349,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק זכויות החולה (תיקון - קביעת הוראות לעניין הכנסת חפצים ודברי מאכל למוסד רפואי), התשפ\"ג-2023",
  type: "private",
  committeeId: "health",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2023-03-01",
  initiators: [
    {
      kind: "mk",
      personId: 1057,
      name: "ישראל אייכלר",
      partyId: "utj",
      factionName: "יהדות התורה"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2023-02-27",
          time: "09:30",
          sessionId: 2202407
        },
        {
          date: "2023-02-28",
          time: "14:00",
          sessionId: 2202291
        },
        {
          date: "2023-03-01",
          time: "09:30",
          sessionId: 2202573
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
