// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2196997,
  syncedAt: "2026-08-12",
  officialName: "חוק דיווח לכנסת על הטרדות מיניות בכוחות הביטחון והטיפול בהן (תיקוני חקיקה), התשפ\"ו-2025",
  type: "private",
  committeeId: "national-security",
  status: "completed",
  summaryOfficial: "במסגרת החוק הוטלה על משטרת ישראל, שירות בתי הסוהר וצבא הגנה לישראל חובת דיווח שנתית לכנסת בנושא הטרדות מיניות והטיפול בהן. נקבע כי המפקח הכללי של המשטרה ונציב בתי הסוהר יגישו לוועדה לביטחון לאומי, ואילו ראש המטה הכללי של צה\"ל יגיש לוועדת החוץ והביטחון, דין וחשבון שנתי עד ל-31 במרץ בכל שנה. הדיווח יתייחס לשנה הקלנדרית שקדמה לו ויכלול פירוט של הפעולות שנקטו הגופים למניעת הטרדות מיניות בארגונים, את מספר הדיווחים שהוגשו לממונה על הטיפול בנושא ואת אופן הטיפול בהם. לשם הגנה על פרטיות המעורבים, נקבע איסור מפורש לכלול בדוח פרטי מידע שיאפשרו את זיהוי המדווחים, המתלוננים, הנילונים או אנשים אחרים המעורבים בדיווח.",
  lastUpdated: "2026-04-21",
  completedDate: "2025-12-10",
  initiators: [
    {
      kind: "mk",
      personId: 30102,
      name: "מירב בן ארי",
      partyId: "yesh-atid",
      factionName: "יש עתיד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-07-18",
          time: "15:15",
          sessionId: 2209179
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-03-10",
          time: "09:30",
          sessionId: 2229310
        },
        {
          date: "2025-07-15",
          time: "11:00",
          sessionId: 2234216
        },
        {
          date: "2026-05-12",
          time: "10:15",
          sessionId: 2242751
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
