// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2196910,
  syncedAt: "2026-08-12",
  officialName: "חוק יום לציון אירועי הפרהוד, התשפ\"ד–2024",
  type: "private",
  committeeId: "education",
  status: "completed",
  summaryOfficial: "נקבע בחוק יום לציון אירועי הפרהוד, הפרעות שהתחוללו ביהודי בגדד בחג השבועות של שנת 1941, אשר יחול מדי שנה ביום החול הראשון שלאחר חג השבועות ואסרו חג. יום זה יצויין בטקס מרכזי לפי החלטת השר לשוויון חברתי וקידום מעמד האישה ובהתייעצות עם שר המורשת, בדיון מיוחד במליאת הכנסת וכן במוסדות החינוך ככל שיחליט על כך שר החינוך.",
  lastUpdated: "2024-08-06",
  completedDate: "2024-07-02",
  initiators: [
    {
      kind: "mk",
      personId: 30701,
      name: "אופיר כץ",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-05-27",
          time: "11:00",
          sessionId: 2218241
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-06-17",
          time: "10:30",
          sessionId: 2218950
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
