// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2196149,
  syncedAt: "2026-08-12",
  officialName: "חוק המקרקעין (תיקון מס' 36), התשפ\"ג–2023",
  type: "private",
  committeeId: "interior-environment",
  status: "completed",
  summaryOfficial: "התיקון קובע כי בעל דירה רשאי להתקין על חשבונו מנגנון המאפשר הפעלה אוטומטית של משאבת מים בלא חילול שבת ברכוש המשותף והוא יישא בהוצאות החזקתו של המנגנון והפעלתו. עוד נקבע כי ההתקנה לא תותנה בקבלת הסכמת בעלי הדירות האחרים אך תעשה בכפוף לתנאים המנויים בתיקון.",
  lastUpdated: "2023-09-28",
  completedDate: "2023-05-29",
  initiators: [
    {
      kind: "mk",
      personId: 23641,
      name: "יעקב אשר",
      partyId: "utj",
      factionName: "יהדות התורה"
    },
    {
      kind: "mk",
      personId: 526,
      name: "משה גפני",
      partyId: "utj",
      factionName: "יהדות התורה"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-02-21",
          time: "13:00",
          sessionId: 2201906
        },
        {
          date: "2023-03-01",
          time: "09:00",
          sessionId: 2202242
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-03-20",
          time: "09:00",
          sessionId: 2203310
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
