// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2196049,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק לתיקון פקודת בתי הסוהר (שלילת זכאות למימון שירותי בריאות משפרי איכות חיים לאסיר ביטחוני), התשפ\"ג-2022",
  type: "private",
  committeeId: "national-security",
  status: "agenda",
  lastUpdated: "2024-01-01",
  initiators: [
    {
      kind: "mk",
      personId: 30810,
      name: "מיכל מרים וולדיגר",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    },
    {
      kind: "mk",
      personId: 30859,
      name: "צביקה פוגל",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2023-05-29",
          time: "12:00",
          sessionId: 2205223
        },
        {
          date: "2023-06-21",
          time: "09:00",
          sessionId: 2206921
        },
        {
          date: "2023-11-20",
          time: "12:30",
          sessionId: 2211534
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
