// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2196942,
  syncedAt: "2026-08-12",
  officialName: "חוק לביטול אזרחותו או תושבותו של פעיל טרור שמקבל תגמול עבור ביצוע מעשה הטרור (תיקוני חקיקה), התשפ\"ג-2023",
  type: "private",
  committeeId: "special",
  committeeName: "הוועדה המשותפת של ועדת הכנסת וועדת הפנים והגנת הסביבה לדיון בהצעות חוק בנושא לביטול אזרחותו או תושבותו של פעיל טרור שמקבל תגמול עבור ביצוע מעשה הטרור",
  status: "completed",
  summaryOfficial: "נקבע כי אזרח או תושב ישראלי שהורשע בביצוע עבירה שהיא הפרת אמונים למדינת ישראל, נגזר עליו מאסר בפועל בגינה, והוכח כי הרשות הפלסטינית מתגמלת אותו על כך, ניתן יהיה לבטל את אזרחותו או את רישיונו לישיבת הקבע לפי העניין, ולהרחיקו לשטחי הרשות הפלסטינית או לרצועת עזה. רישיון ישיבת קבע יבוטל על ידי שר הפנים, לאחר היוועצות בוועדה מייעצת ובהסכמת שר המשפטים, וביטול אזרחות יהיה על ידי בית המשפט, לבקשת שר הפנים, לאחר היוועצות בוועדה מייעצת ובהסכמת שר המשפטים. החוק תוחם את לוח הזמנים להליך ביטול התושבות או האזרחות וקובע חזקה לפיה אדם שקיבל כספים כאמור,  זכאי למעמד ברשות הפלסטינית.",
  lastUpdated: "2023-02-22",
  completedDate: "2023-02-15",
  initiators: [
    {
      kind: "mk",
      personId: 30701,
      name: "אופיר כץ",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30118,
      name: "שרן מרים השכל",
      partyId: "national-unity",
      factionName: "המחנה הממלכתי"
    },
    {
      kind: "mk",
      personId: 30812,
      name: "שמחה רוטמן",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-01-09",
          time: "09:30",
          sessionId: 2199245
        },
        {
          date: "2023-01-16",
          time: "09:00",
          sessionId: 2199249
        },
        {
          date: "2023-01-17",
          time: "17:30",
          sessionId: 2199815
        },
        {
          date: "2023-01-24",
          time: "14:00",
          sessionId: 2199942
        },
        {
          date: "2023-01-24",
          time: "12:00",
          sessionId: 2199939
        },
        {
          date: "2023-01-24",
          time: "14:00",
          sessionId: 2200392
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-01-30",
          time: "09:00",
          sessionId: 2200542
        },
        {
          date: "2023-02-14",
          time: "14:00",
          sessionId: 2200752
        },
        {
          date: "2023-02-15",
          time: "09:30",
          sessionId: 2201739
        },
        {
          date: "2023-02-15",
          time: "09:00",
          sessionId: 2201774
        },
        {
          date: "2023-06-20",
          time: "10:30",
          sessionId: 2207103
        },
        {
          date: "2023-06-20",
          time: "12:00",
          sessionId: 2207105
        },
        {
          date: "2023-11-27",
          time: "10:00",
          sessionId: 2211448
        },
        {
          date: "2024-02-05",
          time: "12:30",
          sessionId: 2214150
        },
        {
          date: "2025-03-11",
          time: "12:15",
          sessionId: 2229333
        },
        {
          date: "2025-03-11",
          time: "12:15",
          sessionId: 2229337
        },
        {
          date: "2025-05-28",
          time: "09:30",
          sessionId: 2231409
        },
        {
          date: "2025-06-04",
          time: "09:30",
          sessionId: 2232367
        },
        {
          date: "2025-06-11",
          time: "09:30",
          sessionId: 2232625
        },
        {
          date: "2025-06-30",
          time: "13:00",
          sessionId: 2233192
        },
        {
          date: "2025-12-02",
          time: "12:00",
          sessionId: 2237062
        },
        {
          date: "2025-12-16",
          time: "12:20",
          sessionId: 2237592
        },
        {
          date: "2026-01-13",
          time: "11:00",
          sessionId: 2239006
        },
        {
          date: "2026-01-27",
          time: "11:00",
          sessionId: 2239557
        },
        {
          date: "2026-04-27",
          time: "12:30",
          sessionId: 2242442
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
