// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2196129,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק למניעת העסקה בתחום החינוך והטיפול של אדם שהורשע או שמואשם בתקיפה או בהתעללות בחסר ישע, התשפ\"ג-2022",
  type: "private",
  committeeId: "education",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2023-05-03",
  initiators: [
    {
      kind: "mk",
      personId: 30780,
      name: "רון כץ",
      partyId: "yesh-atid",
      factionName: "יש עתיד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2023-02-28",
          time: "13:45",
          sessionId: 2202515
        },
        {
          date: "2023-03-21",
          time: "15:00",
          sessionId: 2203322
        },
        {
          date: "2023-05-03",
          time: "09:30",
          sessionId: 2203925
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
