// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2196924,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק-יסוד: השפיטה (תיקון - סמכויות שיפוט ותקנות סדרי דין באישור ועדה)",
  type: "private",
  committeeId: "constitution",
  status: "agenda",
  lastUpdated: "2025-03-04",
  initiators: [
    {
      kind: "mk",
      personId: 30812,
      name: "שמחה רוטמן",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2025-01-27",
          time: "09:15",
          sessionId: 2226532
        },
        {
          date: "2025-07-14",
          time: "10:00",
          sessionId: 2233739
        },
        {
          date: "2025-07-20",
          time: "13:00",
          sessionId: 2234165
        },
        {
          date: "2025-10-28",
          time: "12:00",
          sessionId: 2235505
        },
        {
          date: "2025-10-29",
          time: "09:00",
          sessionId: 2235854
        },
        {
          date: "2025-11-10",
          time: "12:45",
          sessionId: 2236426
        },
        {
          date: "2025-11-25",
          time: "12:00",
          sessionId: 2237044
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
