// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2197896,
  syncedAt: "2026-08-12",
  officialName: "חוק ההתייעלות הכלכלית (תיקוני חקיקה להשגת יעדי התקציב לשנות התקציב 2017 ו-2018) (תיקון מס' 9), התשפ\"ג-2023",
  type: "private",
  committeeId: "finance",
  status: "completed",
  summaryOfficial: "החוק מתקן את המנגנון להקצאת תשלומים לרשויות הסמוכות לנתב\"ג כך שיימחק הסעיף המקצה חלק מהתקציב לרשויות ספציפיות ותבוטל האפשרות לקבוע עבורן כללי חלוקה שונים.",
  lastUpdated: "2024-05-15",
  completedDate: "2023-06-27",
  initiators: [
    {
      kind: "mk",
      personId: 526,
      name: "משה גפני",
      partyId: "utj",
      factionName: "יהדות התורה"
    },
    {
      kind: "mk",
      personId: 23641,
      name: "יעקב אשר",
      partyId: "utj",
      factionName: "יהדות התורה"
    },
    {
      kind: "mk",
      personId: 30601,
      name: "ינון אזולאי",
      partyId: "shas",
      factionName: "התאחדות הספרדים שומרי תורה תנועתו של מרן הרב עובדיה יוסף זצ\"ל"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-03-26",
          time: "12:00",
          sessionId: 2203806
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-06-13",
          time: "11:50",
          sessionId: 2206763
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
