// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2197419,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק הסדרת העיסוק במקצועות הבריאות (תיקון - הסדרת מקצוע הרנטגנאות והדימות), התשפ\"ג-2023",
  type: "private",
  committeeId: "health",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2023-09-05",
  initiators: [
    {
      kind: "mk",
      personId: 30758,
      name: "אימאן ח'טיב יאסין",
      partyId: "raam",
      factionName: "רע\"ם"
    },
    {
      kind: "mk",
      personId: 30713,
      name: "מנסור עבאס",
      partyId: "raam",
      factionName: "רע\"ם"
    },
    {
      kind: "mk",
      personId: 30752,
      name: "ווליד טאהא",
      partyId: "raam",
      factionName: "רע\"ם"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2023-06-12",
          time: "09:30",
          sessionId: 2206705
        },
        {
          date: "2023-06-19",
          time: "09:00",
          sessionId: 2207165
        },
        {
          date: "2023-06-27",
          time: "13:30",
          sessionId: 2207593
        },
        {
          date: "2023-07-04",
          time: "13:00",
          sessionId: 2207963
        },
        {
          date: "2023-07-10",
          time: "09:00",
          sessionId: 2207924
        },
        {
          date: "2023-07-13",
          time: "12:30",
          sessionId: 2208464
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
