// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2197027,
  syncedAt: "2026-08-12",
  officialName: "חוק שירותי הובלה (תיקון מס' 3), התשפ\"ה–2024",
  type: "private",
  committeeId: "economy",
  status: "completed",
  summaryOfficial: "התיקון קובע חובה, שחלה על מוסר מטען, לבדוק בעת העמסת מטען על רכב מסחרי כי המטען מתאים למטען שהותר להובלה ברכב לפי התנאים שנקבעו לכך ברישיון הרכב, ולדרוש מהמוביל להפסיק מיד את ההעמסה אם המטען אינו תואם תנאי מהתנאים האמורים. בכך, התיקון מרחיב את החובה שהייתה מוטלת על מוסר המטען ערב התיקון, לפיה היה עליו לבדוק רק את התאמת משקל המטען המועמס על גבי הרכב למשקל שהותר להובלה לפי רישיון הרכב. הפרת החובה החדשה דינה קנס כאמור בסעיף 61(א)(3) לחוק העונשין, התשל\"ז–1977 (העומד כיום על סך של עד 75,300 שקלים חדשים). אם נעברה העבירה בידי תאגיד, דינו של התאגיד קנס בגובה פי ארבעה מהקנס האמור. אולם, החובה האמורה אינה חלה על התאגיד הנמליים (נמלים), משום שנמצא כי הטלת חובה זו על הנמלים עלולה לגרום לעיכובים משמעותיים בשחרור סחורות מהנמלים.    \n\nבנוסף, התיקון קובע כי על נושא משרה בתאגיד מוטלת החובה לפקח ולעשות כל שניתן כדי למנוע ביצוע עבירות כאמור לעיל, כלומר, העמסה על רכב של מטען שאינו תואם את המטען המותר להובלה לפי תנאי רישיון הרכב, ובכלל זה מטען שמשקלו אינו תואם את המשקל המותר להובלה ברכב, בידי התאגיד ועובדיו. הפרת חובה זו דינה קנס כאמור בסעיף 61(א)(3) לחוק העונשין. כמו כן, התיקון מתקן את הסעיפים שהיו קיימים בחוק ערב תיקונו לעניין אחריות נושאי משרה, כך שיחול לגביהם הנוסח המקובל בעניין זה בחקיקה העדכנית. לעניין זה נותר על כנו משטר הענישה הקיים, כך שהפרת חובת הפיקוח האמורה לגבי חלק מהעבירות המנויות בחוק דינה קנס כאמור בסעיף 61(א)(3) לחוק העונשין, ואילו לעניין הפרת חובת הפיקוח לגבי עבירות אחרות, ובכלל זה לגבי ביצוע עבירה בעת הובלת חומרים מסוכנים, יוטל על נושא המשרה קנס כאמור בסעיף 61(א)(4) לחוק העונשין (העומד כיום על סך של עד 226,000 שקלים חדשים).",
  lastUpdated: "2024-12-03",
  completedDate: "2024-11-12",
  initiators: [
    {
      kind: "mk",
      personId: 23639,
      name: "בועז טופורובסקי",
      partyId: "yesh-atid",
      factionName: "יש עתיד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-07-21",
          time: "16:35",
          sessionId: 2220919
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-10-30",
          time: "10:00",
          sessionId: 2222196
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
