// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2197130,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק הבנקאות (שירות ללקוח) (תיקון מס' 41), התשפ\"ו–2026",
  type: "private",
  committeeId: "economy",
  status: "agenda",
  lastUpdated: "2026-06-11",
  initiators: [
    {
      kind: "mk",
      personId: 23641,
      name: "יעקב אשר",
      partyId: "utj",
      factionName: "יהדות התורה"
    },
    {
      kind: "mk",
      personId: 30840,
      name: "ואליד אלהואשלה",
      partyId: "raam",
      factionName: "רע\"ם"
    },
    {
      kind: "mk",
      personId: 526,
      name: "משה גפני",
      partyId: "utj",
      factionName: "יהדות התורה"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2026-01-14",
          time: "09:30",
          sessionId: 2238857
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2026-05-20",
          time: "09:00",
          sessionId: 2242501
        }
      ]
    },
    {
      stage: "secondThird",
      state: "inProgress",
      discussions: []
    }
  ]
};
