// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2197787,
  syncedAt: "2026-08-12",
  officialName: "חוק אומנה לילדים (תיקון מס' 7), התשפ\"ו-2026",
  type: "private",
  committeeId: "labor-welfare",
  status: "completed",
  summaryOfficial: "תיקון זה לחוק אומנה לילדים מחיל הוראות הקבועות בחוק לעניין הזכות לחינוך והזכות לשירותים ולהטבות, גם לגבי ילדים השוהים במסגרות השמה חוץ־ביתיות שאינן אומנה. במסגרת התיקון נקבע, בין היתר, כי זכותו של ילד שלא להיות מופלה במוסד חינוך, לרבות בכל הנוגע לרישומו למוסד חינוך או קבלתו למוסד חינוך, תחול גם לגבי ילד במסגרת השמה חוץ-ביתית שאינה אומנה. כמו כן, נקבע כי גם ילד המושם במסגרת השמה חוץ-ביתית שאינה אומנה, יהיה זכאי לכל הזכויות, השירותים וההטבות שזכאי להם ילד שהוא תושב הרשות המקומית שבה נמצאת מסגרת ההשמה החוץ-ביתית שבה הושם, לרבות בכל הנוגע לשיוכו למוסדות חינוכיים ברשות המקומית האמורה, בדומה לילד שהושם באומנה. נוסף על כך, תוקן סעיף 3(ב) לחוק, כך שגם ילד שנמצא במסגרת השמה חוץ-ביתית שאינה אומנה או בתהליך השמה במסגרת כאמור, זכאי לכל הזכויות שזכאי להן כל ילד בישראל",
  lastUpdated: "2026-04-28",
  completedDate: "2026-01-21",
  initiators: [
    {
      kind: "mk",
      personId: 30777,
      name: "משה טור פז",
      partyId: "yesh-atid",
      factionName: "יש עתיד"
    },
    {
      kind: "mk",
      personId: 30758,
      name: "אימאן ח'טיב יאסין",
      partyId: "raam",
      factionName: "רע\"ם"
    },
    {
      kind: "mk",
      personId: 30713,
      name: "מנסור עבאס",
      partyId: "raam",
      factionName: "רע\"ם"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-07-24",
          time: "08:30",
          sessionId: 2221216
        },
        {
          date: "2024-11-20",
          time: "09:30",
          sessionId: 2223860
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-05-05",
          time: "10:30",
          sessionId: 2231059
        },
        {
          date: "2025-09-03",
          time: "09:30",
          sessionId: 2234979
        },
        {
          date: "2025-09-16",
          time: "10:00",
          sessionId: 2235326
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
