// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2197981,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק תאגידי מים וביוב (תיקון מס' 20) (הפעלת שירותי מים וביוב על ידי רשות מקומית), התשפ\"ו–2026",
  type: "private",
  committeeId: "economy",
  status: "agenda",
  lastUpdated: "2026-03-31",
  initiators: [
    {
      kind: "mk",
      personId: 30752,
      name: "ווליד טאהא",
      partyId: "raam",
      factionName: "רע\"ם"
    },
    {
      kind: "mk",
      personId: 30713,
      name: "מנסור עבאס",
      partyId: "raam",
      factionName: "רע\"ם"
    },
    {
      kind: "mk",
      personId: 30840,
      name: "ואליד אלהואשלה",
      partyId: "raam",
      factionName: "רע\"ם"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2026-01-12",
          time: "12:00",
          sessionId: 2238941
        },
        {
          date: "2026-02-18",
          time: "09:00",
          sessionId: 2240622
        },
        {
          date: "2026-02-25",
          time: "09:00",
          sessionId: 2240979
        },
        {
          date: "2026-03-01",
          time: "08:30",
          sessionId: 2241253
        },
        {
          date: "2026-03-19",
          time: "13:00",
          sessionId: 2241742
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2026-07-01",
          time: "09:30",
          sessionId: 2244547
        }
      ]
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
