// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2197582,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק המקרקעין (תיקון - התקנת עמדת טעינה לרכב חשמלי בבית משותף ודייני מקרקעין), התשפ\"ג-2022",
  type: "private",
  committeeId: "interior-environment",
  status: "dropped",
  offPipelineReason: "נעצרה",
  lastUpdated: "2026-06-08",
  initiators: [
    {
      kind: "mk",
      personId: 23639,
      name: "בועז טופורובסקי",
      partyId: "yesh-atid",
      factionName: "יש עתיד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2024-09-22",
          time: "11:00",
          sessionId: 2221705
        },
        {
          date: "2025-02-17",
          time: "11:00",
          sessionId: 2228541
        },
        {
          date: "2025-07-07",
          time: "11:30",
          sessionId: 2232956
        },
        {
          date: "2025-07-15",
          time: "14:00",
          sessionId: 2234178
        },
        {
          date: "2025-09-08",
          time: "10:00",
          sessionId: 2235088
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
