// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2197909,
  syncedAt: "2026-08-12",
  officialName: "חוק היועץ המשפטי לממשלה (חוות דעת, ייצוג ופיקוח), התשפ\"ו–2026",
  type: "private",
  committeeId: "constitution",
  status: "completed",
  summaryOfficial: "החוק קובע כי היועץ המשפטי לממשלה ייתן חוות דעת ועצה משפטית בענייני חוק ומשפט לכל גורמי הרשות המבצעת, ויסייע לממשלה להגשים את מדיניותה ויעדיה במסגרת הדין, להשליט חוק ומשפט ברשות המבצעת ולהנהיג בה אחידות ותיאום בפרשנות הדין. עוד קובע החוק כי גורמי הרשות המבצעת יראו חוות דעת משפטית בכתב שנתן היועץ המשפטי לממשלה כמשקפת את הדין הקיים, ואולם הממשלה רשאית להחליט כי היא או גורמים אחרים ברשות המבצעת אינם חייבים לראותה כך, למעט לעניין הפעלת סמכויות בתחום המשפט הפלילי. \nבנוסף, החוק קובע כי היועץ המשפטי לממשלה יציג את עמדת הרשות המבצעת בהליכים בפני בית משפט, וכי הסמכות לקבוע את עמדת הרשות המבצעת נתונה בידי הממשלה; העמדה תיקבע בידי היועץ המשפטי לממשלה, אלא אם כן קבעה הממשלה עמדה אחרת. עוד קובע החוק כי במקרים שבהם היועץ סבור שלא ניתן להציג את עמדת הרשות המבצעת, או שהשר הנוגע בדבר סבור כי העמדה אינה מוצגת או לא תוצג כראוי באמצעות היועץ המשפטי לממשלה, רשאית הממשלה לקבוע כי העמדה תוצג באמצעות עורך דין אחר. במצב כזה, ככלל, היועץ לא יוכל להתייצב אלא אם קיבל אישור. הוראות אלה אינן חלות על הליכים בתחום המשפט הפלילי, על סמכויות שהוקנו ליועץ בחיקוק ועל ייצוג גורמים המפעילים סמכות שיפוטית או מעין-שיפוטית. \nעוד קובע החוק כי היועץ המשפטי לממשלה יהיה עצמאי בשיקוליו ובהחלטותיו, ובעניינים הנוגעים לתחום המשפט הפלילי לא תהיה עליו מרות זולת מרותו של הדין. החוק קובע כי היועץ נושא באחריות למילוי תפקידו בפני הממשלה ונתון לפיקוחו של שר המשפטים, וכן מסדיר את חובות הדיווח שלו לשר ואת החריגים לחובות אלה. תחילתו של החוק ביום 1 בינואר 2027. נקבע כי בתוך 30 ימים מיום תחילתו של חוק זה, תקבל הממשלה החלטה בהתאם לסמכותה לפי סעיף 5 לחוק שירות המדינה (מינויים), התשי\"ט–1959.",
  lastUpdated: "2026-07-26",
  completedDate: "2026-07-13",
  initiators: [
    {
      kind: "mk",
      personId: 30842,
      name: "חנוך דב מלביצקי",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30867,
      name: "יצחק קרויזר",
      partyId: "otzma",
      factionName: "עוצמה יהודית בראשות איתמר בן גביר"
    },
    {
      kind: "mk",
      personId: 30710,
      name: "אריאל קלנר",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-11-03",
          time: "12:15",
          sessionId: 2236063
        },
        {
          date: "2025-11-10",
          time: "09:00",
          sessionId: 2236414
        },
        {
          date: "2025-11-17",
          time: "09:00",
          sessionId: 2236415
        },
        {
          date: "2025-11-24",
          time: "09:00",
          sessionId: 2236704
        },
        {
          date: "2025-11-25",
          time: "14:00",
          sessionId: 2237113
        },
        {
          date: "2025-12-02",
          time: "11:15",
          sessionId: 2237043
        },
        {
          date: "2025-12-08",
          time: "09:00",
          sessionId: 2237291
        },
        {
          date: "2025-12-09",
          time: "09:00",
          sessionId: 2237293
        },
        {
          date: "2025-12-23",
          time: "11:15",
          sessionId: 2237786
        },
        {
          date: "2025-12-29",
          time: "11:00",
          sessionId: 2238312
        },
        {
          date: "2025-12-30",
          time: "13:00",
          sessionId: 2238313
        },
        {
          date: "2026-01-05",
          time: "11:15",
          sessionId: 2238672
        },
        {
          date: "2026-01-06",
          time: "12:00",
          sessionId: 2238675
        },
        {
          date: "2026-01-12",
          time: "09:00",
          sessionId: 2238678
        },
        {
          date: "2026-01-14",
          time: "09:00",
          sessionId: 2238681
        },
        {
          date: "2026-01-19",
          time: "11:00",
          sessionId: 2239327
        },
        {
          date: "2026-01-20",
          time: "11:30",
          sessionId: 2239328
        },
        {
          date: "2026-01-26",
          time: "09:00",
          sessionId: 2239329
        },
        {
          date: "2026-01-27",
          time: "11:30",
          sessionId: 2239330
        },
        {
          date: "2026-02-01",
          time: "09:00",
          sessionId: 2239645
        },
        {
          date: "2026-02-03",
          time: "13:00",
          sessionId: 2239646
        },
        {
          date: "2026-02-09",
          time: "11:00",
          sessionId: 2239935
        },
        {
          date: "2026-02-10",
          time: "12:00",
          sessionId: 2239937
        },
        {
          date: "2026-02-17",
          time: "11:00",
          sessionId: 2240251
        },
        {
          date: "2026-02-23",
          time: "09:00",
          sessionId: 2240593
        },
        {
          date: "2026-02-24",
          time: "12:10",
          sessionId: 2240597
        },
        {
          date: "2026-03-01",
          time: "10:30",
          sessionId: 2240985
        },
        {
          date: "2026-03-05",
          time: "11:00",
          sessionId: 2240991
        },
        {
          date: "2026-03-09",
          time: "11:00",
          sessionId: 2241241
        },
        {
          date: "2026-03-15",
          time: "10:30",
          sessionId: 2241656
        },
        {
          date: "2026-03-16",
          time: "10:00",
          sessionId: 2241574
        },
        {
          date: "2026-03-17",
          time: "13:15",
          sessionId: 2241575
        },
        {
          date: "2026-03-19",
          time: "12:30",
          sessionId: 2241798
        },
        {
          date: "2026-03-22",
          time: "10:00",
          sessionId: 2241857
        },
        {
          date: "2026-03-23",
          time: "09:00",
          sessionId: 2241858
        },
        {
          date: "2026-03-24",
          time: "12:00",
          sessionId: 2242027
        },
        {
          date: "2026-04-15",
          time: "09:30",
          sessionId: 2242344
        },
        {
          date: "2026-04-29",
          time: "09:30",
          sessionId: 2242386
        },
        {
          date: "2026-05-06",
          time: "09:30",
          sessionId: 2242678
        },
        {
          date: "2026-05-11",
          time: "09:00",
          sessionId: 2242776
        },
        {
          date: "2026-05-12",
          time: "09:30",
          sessionId: 2242779
        },
        {
          date: "2026-05-12",
          time: "13:30",
          sessionId: 2242782
        },
        {
          date: "2026-05-17",
          time: "09:00",
          sessionId: 2243120
        },
        {
          date: "2026-05-18",
          time: "09:00",
          sessionId: 2243122
        },
        {
          date: "2026-05-19",
          time: "09:00",
          sessionId: 2243168
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2026-05-25",
          time: "09:00",
          sessionId: 2243361
        },
        {
          date: "2026-06-10",
          time: "09:00",
          sessionId: 2243870
        },
        {
          date: "2026-06-11",
          time: "10:00",
          sessionId: 2243874
        },
        {
          date: "2026-06-14",
          time: "09:00",
          sessionId: 2243875
        },
        {
          date: "2026-06-14",
          time: "13:15",
          sessionId: 2244153
        },
        {
          date: "2026-06-15",
          time: "09:00",
          sessionId: 2243876
        },
        {
          date: "2026-06-16",
          time: "09:00",
          sessionId: 2243880
        },
        {
          date: "2026-06-16",
          time: "13:15",
          sessionId: 2244155
        },
        {
          date: "2026-06-17",
          time: "09:00",
          sessionId: 2243881
        },
        {
          date: "2026-06-21",
          time: "09:00",
          sessionId: 2244290
        },
        {
          date: "2026-06-22",
          time: "12:30",
          sessionId: 2244291
        },
        {
          date: "2026-06-23",
          time: "09:00",
          sessionId: 2244292
        },
        {
          date: "2026-06-23",
          time: "13:00",
          sessionId: 2244482
        },
        {
          date: "2026-06-24",
          time: "09:00",
          sessionId: 2244488
        },
        {
          date: "2026-06-28",
          time: "09:00",
          sessionId: 2244551
        },
        {
          date: "2026-06-29",
          time: "10:00",
          sessionId: 2244555
        },
        {
          date: "2026-06-30",
          time: "14:00",
          sessionId: 2244558
        },
        {
          date: "2026-06-30",
          time: "09:00",
          sessionId: 2244561
        },
        {
          date: "2026-06-30",
          time: "13:00",
          sessionId: 2244562
        },
        {
          date: "2026-06-30",
          time: "18:00",
          sessionId: 2244778
        },
        {
          date: "2026-07-02",
          time: "09:00",
          sessionId: 2244559
        },
        {
          date: "2026-07-05",
          time: "11:30",
          sessionId: 2244806
        },
        {
          date: "2026-07-06",
          time: "10:00",
          sessionId: 2244807
        },
        {
          date: "2026-07-07",
          time: "10:00",
          sessionId: 2244982
        },
        {
          date: "2026-07-07",
          time: "20:15",
          sessionId: 2245051
        },
        {
          date: "2026-07-08",
          time: "09:00",
          sessionId: 2245057
        },
        {
          date: "2026-07-09",
          time: "09:00",
          sessionId: 2245099
        },
        {
          date: "2026-07-12",
          time: "10:00",
          sessionId: 2245168
        },
        {
          date: "2026-07-12",
          time: "16:35",
          sessionId: 2245170
        },
        {
          date: "2026-07-12",
          time: "19:10",
          sessionId: 2245183
        },
        {
          date: "2026-07-12",
          time: "18:05",
          sessionId: 2245181
        },
        {
          date: "2026-07-13",
          time: "23:00",
          sessionId: 2245196
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
