// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2197572,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק לביטול אזרחותו או תושבותו של פעיל טרור שמקבל תגמול עבור ביצוע מעשה הטרור (תיקוני חקיקה), התשפ\"ג-2022",
  type: "private",
  committeeId: "special",
  committeeName: "הוועדה המשותפת של ועדת הכנסת וועדת הפנים והגנת הסביבה לדיון בהצעות חוק בנושא לביטול אזרחותו או תושבותו של פעיל טרור שמקבל תגמול עבור ביצוע מעשה הטרור",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2023-01-18",
  initiators: [
    {
      kind: "mk",
      personId: 30812,
      name: "שמחה רוטמן",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    },
    {
      kind: "mk",
      personId: 30830,
      name: "אוהד טל",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    },
    {
      kind: "mk",
      personId: 30852,
      name: "משה סולומון",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2023-01-09",
          time: "09:30",
          sessionId: 2199245
        },
        {
          date: "2023-01-16",
          time: "09:00",
          sessionId: 2199249
        },
        {
          date: "2023-01-17",
          time: "17:30",
          sessionId: 2199815
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
