// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2197901,
  syncedAt: "2026-08-12",
  officialName: "חוק שיפוט בתי דין דתיים (בוררות), התשפ\"ו–2026",
  type: "private",
  committeeId: "constitution",
  status: "completed",
  summaryOfficial: "נקבע כי בית דין רבני או שרעי רשאי לדון כבורר בעניינים אזרחיים בהתאם לדין הדתי החל בו, וזאת בכפוף להסכמת הצדדים בחתימה על טופס בוררות ייעודי ולכך שלבית הדין יש סמכות שיפוט אישית כלפי אחד מהם או שכל הצדדים הם תאגידים. סמכות זו אינה חלה על עניינים פליליים, מינהליים, סכסוכי משפחה, עניינים שהמדינה או רשות מקומית צד להם, עניינים מסוימים מתחום משפט העבודה, ועניינים הנוגעים להליכים משמעתיים. \nעוד נקבע כי אם הוגשה בקשה בצירוף טופס חתום רק בידי חלק מן הצדדים, מזכירות בית הדין רשאית לשלוח לצדדים שלא חתמו, הודעה על האפשרות לחתום, וכי עד לקבלת טופס חתום בידי כל הצדדים לא יתקיימו דיונים ולא תינתן החלטה מהותית, למעט החלטה טכנית שאינה נוגעת לגוף הסכסוך. כמו כן, בתחילת הדיון יברר בית הדין שהחתימה נעשתה מרצון חופשי ויבהיר לצדדים כי מדובר בהליך בוררות ולא בהליך שיפוטי. בעניין הנמצא בסמכות בית הדין לעבודה כשקיימים יחסי עבודה בין הצדדים יברר בית הדין אם היוזמה להבאת ההליך הייתה של העובד. בית הדין יהיה רשאי לסרב לדון בבוררות מטעמים שיירשמו.\nבמסגרת הבוררות, פסיקת בית הדין לא תפגע בזכויות מהותיות המוקנות לצדדים בחוקים שנמנו בסעיף ובכלל זה, אלו שבחוק שיווי זכויות האישה, חוק החוזים האחידים, חוק המגן על אנשים עם מוגבלות וחוקים קוגנטיים אחרים. עוד נקבע כי על ההליך יחולו דיני הבוררות בשינויים מסוימים, לרבות אפשרות לביטול פסק שניתן בניגוד להוראות חוק זה, ואכיפת פסק הבוררות כפסק דין ללא צורך באישורו על ידי בית המשפט.",
  lastUpdated: "2026-07-28",
  completedDate: "2026-03-23",
  initiators: [
    {
      kind: "mk",
      personId: 526,
      name: "משה גפני",
      partyId: "utj",
      factionName: "יהדות התורה"
    },
    {
      kind: "mk",
      personId: 23641,
      name: "יעקב אשר",
      partyId: "utj",
      factionName: "יהדות התורה"
    },
    {
      kind: "mk",
      personId: 30601,
      name: "ינון אזולאי",
      partyId: "shas",
      factionName: "התאחדות הספרדים שומרי תורה תנועתו של מרן הרב עובדיה יוסף זצ\"ל"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-02-27",
          time: "09:30",
          sessionId: 2202407
        },
        {
          date: "2024-03-26",
          time: "09:00",
          sessionId: 2216805
        },
        {
          date: "2024-11-05",
          time: "13:00",
          sessionId: 2222975
        },
        {
          date: "2024-11-12",
          time: "12:00",
          sessionId: 2223568
        },
        {
          date: "2024-12-11",
          time: "09:00",
          sessionId: 2224570
        },
        {
          date: "2025-03-04",
          time: "14:00",
          sessionId: 2229259
        },
        {
          date: "2025-04-03",
          time: "11:00",
          sessionId: 2230616
        },
        {
          date: "2025-05-06",
          time: "09:30",
          sessionId: 2230892
        },
        {
          date: "2025-06-10",
          time: "14:00",
          sessionId: 2232548
        },
        {
          date: "2025-07-01",
          time: "09:20",
          sessionId: 2233411
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-12-02",
          time: "14:45",
          sessionId: 2237334
        },
        {
          date: "2025-12-30",
          time: "09:30",
          sessionId: 2238317
        },
        {
          date: "2026-01-06",
          time: "09:30",
          sessionId: 2238682
        },
        {
          date: "2026-01-07",
          time: "09:00",
          sessionId: 2238957
        },
        {
          date: "2026-01-28",
          time: "09:00",
          sessionId: 2239648
        },
        {
          date: "2026-02-01",
          time: "13:30",
          sessionId: 2239934
        },
        {
          date: "2026-02-03",
          time: "10:45",
          sessionId: 2239936
        },
        {
          date: "2026-02-10",
          time: "10:00",
          sessionId: 2240232
        },
        {
          date: "2026-02-16",
          time: "11:00",
          sessionId: 2240233
        },
        {
          date: "2026-02-17",
          time: "12:00",
          sessionId: 2240878
        },
        {
          date: "2026-02-17",
          time: "10:15",
          sessionId: 2240749
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
