// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2197160,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק זכויות הסטודנט (תיקון - העדפה מתקנת ללוחמים), התשפ\"ג-2022",
  type: "private",
  committeeId: "education",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2026-02-25",
  initiators: [
    {
      kind: "mk",
      personId: 30867,
      name: "יצחק קרויזר",
      partyId: "otzma",
      factionName: "עוצמה יהודית בראשות איתמר בן גביר"
    },
    {
      kind: "mk",
      personId: 23597,
      name: "מאיר כהן",
      partyId: "yesh-atid",
      factionName: "יש עתיד"
    },
    {
      kind: "mk",
      personId: 30842,
      name: "חנוך דב מלביצקי",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2024-11-05",
          time: "11:00",
          sessionId: 2223014
        },
        {
          date: "2025-01-27",
          time: "10:00",
          sessionId: 2227144
        },
        {
          date: "2026-01-20",
          time: "09:30",
          sessionId: 2239273
        },
        {
          date: "2026-02-24",
          time: "13:00",
          sessionId: 2240902
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
