// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2198435,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק העונשין (תיקון - הגדרת איום), התשפ\"ג-2023",
  type: "private",
  committeeId: "special",
  committeeName: "הוועדה המשותפת של ועדת החוקה, חוק ומשפט והוועדה לביטחון לאומי לדיון בהצעת חוק העונשין (תיקון - הגדרת איום), התשפ\"ג-2023 (פ/2156/25)",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2023-07-18",
  initiators: [
    {
      kind: "mk",
      personId: 30772,
      name: "ניסים ואטורי",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2023-07-03",
          time: "10:00",
          sessionId: 2208211
        },
        {
          date: "2023-07-12",
          time: "09:15",
          sessionId: 2208545
        },
        {
          date: "2023-07-17",
          time: "08:00",
          sessionId: 2208913
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
