// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2198601,
  syncedAt: "2026-08-17",
  officialName: "הצעת חוק עקרונות האסדרה (תיקון) (בחינה תקופתית של אסדרה ואי-הטלת אחריות בשל אי-פרסום אסדרה), התשפ''ד–2024",
  type: "private",
  committeeId: "constitution",
  status: "agenda",
  lastUpdated: "2025-01-21",
  initiators: [
    {
      kind: "mk",
      personId: 30832,
      name: "אליהו רביבו",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-03-20",
          time: "09:00",
          sessionId: 2216126
        },
        {
          date: "2024-05-22",
          time: "09:00",
          sessionId: 2217627
        },
        {
          date: "2024-07-17",
          time: "09:00",
          sessionId: 2220674
        },
        {
          date: "2024-07-21",
          time: "13:30",
          sessionId: 2220997
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "inProgress",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
