// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2198188,
  syncedAt: "2026-08-12",
  officialName: "חוק להפסקת פעילות אונר\"א בשטח מדינת ישראל, התשפ\"ה-2024",
  type: "private",
  committeeId: "foreign-defense",
  status: "completed",
  summaryOfficial: "במרוצת השנים התגלו אי סדרים שונים בפעילותה של אונר\"א ונמצאו הוכחות ישירות למעורבות שלה ושל עובדיה בפעילות טרור נגד ישראל, לרבות באמצעות מערכת החינוך של אונר\"א המסיטה להסתה, שנאה ואלימות נגד ישראל ובכלל זה השתתפות עובדי אונר\"א במתקפת הטרור שהחלה ביום כ״ב בתשרי התשפ״ד (7 באוקטובר 2023).\nלאור זאת, נחקקו שני חוקים העוסקים באופנים שונים בהפסקת פעילות סוכנות אונר\"א. הראשון – חוק להפסקת פעילות אונר\"א, התשפ\"ה–2024, והשני – חוק להפסקת פעילות אונר\"א בשטח מדינת ישראל, התשפ\"ה–2024. במסגרת החוק האחרון, נקבע כי אונר\"א לא תפעיל כל נציגות, לא תספק כל שירות ולא תקיים כל פעילות, במישרין או בעקיפין, בשטחה הריבוני של מדינת ישראל. בנוסף, נקבע כי תחילתו של חוק זה יהיה שלושה חודשים מיום פרסומו, וחובת דיווח של ראש המטה לביטחון לאומי או נציגו לוועדת החוץ והביטחון של הכנסת, אחת לשישה חודשים, ובשנה הראשונה מיום תחילתו של חוק זה – אחת לחודשיים, בנוגע ליישום הוראות חוק זה.",
  lastUpdated: "2025-08-12",
  completedDate: "2024-10-28",
  initiators: [
    {
      kind: "mk",
      personId: 30835,
      name: "בועז ביסמוט",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30831,
      name: "אלי דלל",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30842,
      name: "חנוך דב מלביצקי",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-04-08",
          time: "11:30",
          sessionId: 2217315
        },
        {
          date: "2024-07-02",
          time: "09:00",
          sessionId: 2219925
        },
        {
          date: "2024-07-09",
          time: "10:30",
          sessionId: 2220252
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-09-03",
          time: "10:00",
          sessionId: 2221880
        },
        {
          date: "2024-09-24",
          time: "11:00",
          sessionId: 2222257
        },
        {
          date: "2024-10-06",
          time: "12:00",
          sessionId: 2222465
        },
        {
          date: "2024-10-08",
          time: "13:00",
          sessionId: 2222460
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
