// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2198100,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק לחילוט תקבולי עבירה בשווי בעבירת גניבה חקלאית ובעבירות הגורמות נזק לרכוש חקלאי, התשפ\"ג-2023",
  type: "private",
  committeeId: "national-security",
  status: "agenda",
  lastUpdated: "2023-03-27",
  initiators: [
    {
      kind: "mk",
      personId: 30691,
      name: "רם בן ברק",
      partyId: "yesh-atid",
      factionName: "יש עתיד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2023-06-27",
          time: "12:00",
          sessionId: 2207536
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
