// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2198282,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק העונשין (תיקון מס' 156) התשפ\"ו-2026",
  type: "governmental",
  committeeId: "constitution",
  status: "agenda",
  lastUpdated: "2026-06-25",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-07-02",
          time: "14:10",
          sessionId: 2219406
        },
        {
          date: "2026-06-08",
          time: "10:00",
          sessionId: 2243866
        },
        {
          date: "2026-06-16",
          time: "12:00",
          sessionId: 2244093
        }
      ]
    },
    {
      stage: "secondThird",
      state: "inProgress",
      discussions: []
    }
  ]
};
