// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2198763,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק לעידוד השקעות הון בחקלאות (תיקון - השוואת ההטבות בתעשייה להטבות בחקלאות), התשפ\"ג-2023",
  type: "private",
  committeeId: "finance",
  status: "agenda",
  lastUpdated: "2024-05-27",
  initiators: [
    {
      kind: "mk",
      personId: 30691,
      name: "רם בן ברק",
      partyId: "yesh-atid",
      factionName: "יש עתיד"
    },
    {
      kind: "mk",
      personId: 30851,
      name: "מטי צרפתי הרכבי",
      partyId: "yesh-atid",
      factionName: "יש עתיד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2024-06-04",
          time: "10:00",
          sessionId: 2218471
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
