// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2198001,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק שוויון ההזדמנויות בעבודה (תיקון - הארכת תקופת ההתיישנות), התשפ\"ג-2023",
  type: "private",
  committeeId: "labor-welfare",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2024-07-08",
  initiators: [
    {
      kind: "mk",
      personId: 30758,
      name: "אימאן ח'טיב יאסין",
      partyId: "raam",
      factionName: "רע\"ם"
    },
    {
      kind: "mk",
      personId: 30713,
      name: "מנסור עבאס",
      partyId: "raam",
      factionName: "רע\"ם"
    },
    {
      kind: "mk",
      personId: 30752,
      name: "ווליד טאהא",
      partyId: "raam",
      factionName: "רע\"ם"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2024-07-08",
          time: "12:30",
          sessionId: 2220305
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
