// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2199718,
  syncedAt: "2026-08-12",
  officialName: "חוק לפינוי שדות מוקשים ושטחי נפלים (תיקון מס' 2), התשפ\"ג-2023",
  type: "governmental",
  committeeId: "foreign-defense",
  status: "completed",
  summaryOfficial: "חוק לפינוי שדות מוקשים ושטחי נפלים (תיקון מס' 2), התשפ\"ג-2023 אושר בקריאה השנייה והשלישית ביום כ\"ג בשבט התשפ\"ג (14 בפברואר 2023).\nהחוק כלל שורה של תיקונים בחוק לפינוי שדות מוקשים ושטחי נפלים. בין היתר:\n* הוראת השעה המסמיכה את הרשות לפינוי מוקשים לפנות שטחי נפלים לבקשת יזם על חשבונו הפכה להוראת קבע. בנוסף, הפכו להוראות קבע ההוראות המסמיכות אותה לפנות מוקשים נגד טנקים, לפנות שדה מוקשים על בסיס סקר ולפנות שטחי נפלים באופן זמני.\n* לצד ההסדר הכללי המסדיר פינוי מוקשים על חשבון המדינה, נוספה אפשרות לפנות שדות מוקשים לבקשת יזם ועל חשבונו.\n* בוטל הצורך באישור המפקד הצבאי (הרמטכ\"ל או אלוף הפיקוד הרלוונטי) לפתיחתו של שדה מוקשים או שטח נפלים שפונה ובצד זאת בוטלה החובה שהוטלה על צה\"ל להסיר את הגדרות שהקיפו אותו, ופעולה זו תבוצע כחלק מהליך הפינוי.\n* בוטל הצורך בהוצאת צו סגירה של הרמטכ\"ל לשטח נפלים בטרם ניתן יהיה להתחיל בפינויו.\n* בוטל הפטור שניתן לעובדי הרשות לפינוי מוקשים ולצה\"ל מאחריות פלילית במקרה של פגיעה ממוקש או מנפל לאחר שחרור השטח.\n* נוספה הבהרה בדבר אחריות המדינה לנזקים שייגרמו לאדם שייפגע ממוקש או מנפל בשטח שפונה.\n* הורחבה הסמכות לפנות מוקשים ונפלים בים ללא מגבלת עומק.\n* נוספו נציגים של משרדי האוצר והאנרגיה לוועדה המייעצת הפועלת ליד הרשות.\n* הוטלה על שר הביטחון חובה לצרף את חוות הדעת של הוועדה המייעצת לדיווח שלו לממשלה על התוכנית הלאומית לפינוי מוקשים שאישר.",
  lastUpdated: "2024-01-16",
  completedDate: "2023-02-13",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-01-16",
          time: "09:00",
          sessionId: 2199249
        },
        {
          date: "2023-01-30",
          time: "11:00",
          sessionId: 2200204
        },
        {
          date: "2023-02-13",
          time: "09:00",
          sessionId: 2201565
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
