// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2199527,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק לימוד חובה (תיקון - חינוך חינם לפעוטות ולילדים), התשפ\"ג-2023",
  type: "private",
  status: "dropped",
  offPipelineReason: "נעצרה",
  lastUpdated: "2026-07-26",
  initiators: [
    {
      kind: "mk",
      personId: 30799,
      name: "מישל בוסקילה",
      factionName: "הימין הממלכתי"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2023-02-13",
          time: "15:45",
          sessionId: 2201566
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
