// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2199293,
  syncedAt: "2026-08-12",
  officialName: "חוק להארכת תוקפן של תקנות שעת חירום (יהודה והשומרון – שיפוט בעבירות ועזרה משפטית), התשפ\"ג-2023",
  type: "governmental",
  committeeId: "foreign-defense",
  status: "completed",
  summaryOfficial: "חוק להארכת תוקפן של תקנות שעת חירום (יהודה והשומרון – שיפוט בעבירות ועזרה משפטית), התשפ\"ג-2023 התקבל בקריאה השנייה ובקריאה השלישית ביום ב' בשבט תשפ\"ג (24 בינואר 2023). \nהחוק האריך בחמש שנים, עד ה-15 בפברואר 2028, את תוקפן של תקנות שעת חירום (יהודה והשומרון – שיפוט בעבירות ועזרה משפטית), התשכ\"ז-1967. התקנות עוסקות ביחסי הגומלין המשפטיים בין ישראל לבין אזור יהודה והשומרון, לרבות הסדרת החיים והסמכויות לגבי ישראלים המתגוררים בו (דוגמת: הקניית סמכות לבתי המשפט בישראל לדון, לפי הדין הישראלי, בעניינו של ישראלי שביצע עבירות פליליות באזור; קביעת סמכויות שיטור לשוטרי משטרת ישראל לפעול ביחס לעבירות פליליות שבתי משפט בישראל או בתי משפט צבאיים באזור מוסמכים לדון בהן; הרחבת סמכויותיהם של מי שהוקנו להם בישראל סמכויות בענייני מיסים, הוצאה לפועל, אגודות שיתופיות, עמותות ועוד, להפעיל את סמכויותיהם גם באזור), והעזרה המשפטית בין ישראל לרשות הפלסטינית.",
  lastUpdated: "2023-06-19",
  completedDate: "2023-01-24",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-01-09",
          time: "09:30",
          sessionId: 2199245
        },
        {
          date: "2023-01-17",
          time: "13:00",
          sessionId: 2199535
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
