// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2200908,
  syncedAt: "2026-08-12",
  officialName: "חוק להנצחת זכרה של גולדה מאיר, התשפ\"ו–2026",
  type: "private",
  committeeId: "education",
  status: "completed",
  summaryOfficial: "החוק מקים מרכז להנצחת גולדה מאיר, שהיתה ראשת הממשלה של מדינת ישראל בין השנים 1969 ל-1974. המרכז יכלול אתר הנצחה ומוזאון, וכן מכון מחקר וארכיון אם יוחלט להקימם. המרכז יעסוק בהנצחת פועלה ומורשתה של גולדה מאיר, וכן במחקר על מנהיגות נשים ועל מדינאות ככלי לחיזוק הביטחון. החוק מסדיר את מבנה המרכז, מוסדותיו, דרכי הפיקוח עליו ותקציבו, ואת הרכב מועצת המרכז, וקובע כי בשתי תקופות הכהונה הראשונות תעמוד אישה בראש המועצה. נוסף על כך, יום ח' בכסלו, יום פטירתה של גולדה מאיר, יהיה יום זיכרון שיצוין בטקסים, בפעילויות חינוכיות ובדיון מיוחד בכנסת. ראש הממשלה ידווח לכנסת מדי שנה על פעילות המרכז.",
  lastUpdated: "2026-07-29",
  completedDate: "2026-07-13",
  initiators: [
    {
      kind: "mk",
      personId: 23565,
      name: "מרב מיכאלי",
      partyId: "labor",
      factionName: "העבודה"
    },
    {
      kind: "mk",
      personId: 23635,
      name: "פנינה תמנו",
      partyId: "national-unity",
      factionName: "המחנה הממלכתי"
    },
    {
      kind: "mk",
      personId: 30106,
      name: "נעמה לזימי",
      partyId: "labor",
      factionName: "העבודה"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2026-02-02",
          time: "10:30",
          sessionId: 2239939
        },
        {
          date: "2026-03-24",
          time: "13:00",
          sessionId: 2241278
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2026-05-19",
          time: "09:30",
          sessionId: 2243080
        },
        {
          date: "2026-05-25",
          time: "09:00",
          sessionId: 2243342
        },
        {
          date: "2026-06-30",
          time: "11:00",
          sessionId: 2244465
        },
        {
          date: "2026-07-09",
          time: "11:00",
          sessionId: 2245101
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
