// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2200570,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק רשות המורשת ביהודה והשומרון, התשפ\"ו–2026",
  type: "private",
  committeeId: "education",
  status: "agenda",
  lastUpdated: "2026-05-12",
  initiators: [
    {
      kind: "mk",
      personId: 30711,
      name: "עמית הלוי",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-11-27",
          time: "09:00",
          sessionId: 2224074
        },
        {
          date: "2025-02-11",
          time: "10:00",
          sessionId: 2228089
        },
        {
          date: "2025-03-18",
          time: "10:00",
          sessionId: 2229776
        },
        {
          date: "2025-12-31",
          time: "09:00",
          sessionId: 2238257
        },
        {
          date: "2026-01-06",
          time: "13:15",
          sessionId: 2238733
        },
        {
          date: "2026-01-06",
          time: "09:30",
          sessionId: 2238758
        },
        {
          date: "2026-01-13",
          time: "12:30",
          sessionId: 2238855
        },
        {
          date: "2026-01-26",
          time: "11:00",
          sessionId: 2239562
        },
        {
          date: "2026-02-03",
          time: "09:30",
          sessionId: 2239849
        },
        {
          date: "2026-02-03",
          time: "12:35",
          sessionId: 2240151
        },
        {
          date: "2026-02-10",
          time: "12:30",
          sessionId: 2240382
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2026-05-18",
          time: "11:00",
          sessionId: 2243077
        },
        {
          date: "2026-05-19",
          time: "13:30",
          sessionId: 2243076
        },
        {
          date: "2026-05-20",
          time: "08:30",
          sessionId: 2243081
        },
        {
          date: "2026-05-24",
          time: "09:00",
          sessionId: 2243338
        },
        {
          date: "2026-05-24",
          time: "10:00",
          sessionId: 2243403
        },
        {
          date: "2026-05-26",
          time: "08:30",
          sessionId: 2243378
        },
        {
          date: "2026-06-01",
          time: "10:00",
          sessionId: 2243586
        },
        {
          date: "2026-06-02",
          time: "09:30",
          sessionId: 2243587
        },
        {
          date: "2026-06-29",
          time: "12:00",
          sessionId: 2244271
        }
      ]
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
