// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2200898,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק לתיקון פקודת המועצות המקומיות (בחירות לוועד מקומי במועצה אזורית), התשפ\"ג-2023",
  type: "private",
  committeeId: "interior-environment",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2023-06-13",
  initiators: [
    {
      kind: "mk",
      personId: 30772,
      name: "ניסים ואטורי",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2023-05-30",
          time: "13:30",
          sessionId: 2205646
        },
        {
          date: "2023-06-12",
          time: "12:30",
          sessionId: 2206404
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
