// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2201621,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק ביטוח בריאות ממלכתי (תיקון - העברת מידע מלא בעת מעבר בין קופות החולים), התשפ\"ג-2023",
  type: "private",
  committeeId: "health",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2024-06-05",
  initiators: [
    {
      kind: "mk",
      personId: 30780,
      name: "רון כץ",
      partyId: "yesh-atid",
      factionName: "יש עתיד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2024-01-09",
          time: "14:00",
          sessionId: 2213206
        },
        {
          date: "2024-06-03",
          time: "09:30",
          sessionId: 2218683
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
