// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2201297,
  syncedAt: "2026-08-12",
  officialName: "חוק למניעת הטרדה מינית (תיקון מס' 16), התשפ\"ד–2024",
  type: "private",
  committeeId: "womens-status",
  status: "completed",
  lastUpdated: "2024-07-28",
  completedDate: "2024-07-23",
  initiators: [
    {
      kind: "mk",
      personId: 23565,
      name: "מרב מיכאלי",
      partyId: "labor",
      factionName: "העבודה"
    },
    {
      kind: "mk",
      personId: 30879,
      name: "ששון ששי גואטה",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30871,
      name: "שלי טל מירון",
      partyId: "yesh-atid",
      factionName: "יש עתיד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-06-03",
          time: "12:00",
          sessionId: 2210162
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-07-15",
          time: "11:00",
          sessionId: 2220560
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
