// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2201068,
  syncedAt: "2026-08-12",
  officialName: "חוק הרשות השנייה לטלוויזיה ורדיו (תיקון מס' 48), התשפ\"ג-2023",
  type: "governmental",
  committeeId: "economy",
  status: "completed",
  summaryOfficial: "התיקון מאריך בשנה וחצי את תוקפה של הוראת מעבר שנקבעה בתיקון מס' 44 לחוק הרשות השנייה לטלוויזיה ולרדיו, התש\"ן–1990 (להלן – תיקון 44), שהתקבל בכנסת בשנת 2018.\nבתיקון 44 נקבעו שורה של הקלות רגולטוריות לערוצים זעירים ולערוצים זעירים ייעודיים, שהם ערוצים בעלי היקף הכנסה מצומצם שנועדו לתת מענה לקהלים ולנושאים ספציפיים שלא מקבלים ייצוג הולם בערוצי התקשורת המרכזיים. ערוצים אלו היו בפיקוח של המועצה לשידורי כבלים ולשידורי לוויין, ועברו בתיקון 44 לפיקוח הרשות השנייה לטלוויזיה ולרדיו, ומשמעות המעבר היא שאותם ערוצים זכו להקלות משמעותיות במחויבויות החלות עליהם. מדובר בערוץ בשפה הערבית (\"הלא TV\"), בערוץ בשפה הרוסית (ערוץ 9), בערוץ 24 ובערוץ 14.\nנוסף על ההקלות שנקבעו בתיקון 44, נקבעה גם הוראת מעבר לתקופה של חמש שנים, עד ליום ד' באדר התשפ\"ג (25.2.2023), שעניינה מתן הקלות נוספות וזמניות לערוצים האמורים, במטרה לאפשר את המשך קיומם נוכח היקף הכנסתם המצומצם. ההקלות הזמניות שנקבעו בהוראת המעבר, ותוקפן מוארך בשנה וחצי לפי התיקון, הן פטור מתשלום דמי רישיון שנתיים;  חובה של חברות הכבלים והלוויין (כיום הוט ויס) להעביר במסגרת שידוריהם את שידורי הערוצים ופטור מתשלום עבור שידור כאמור;  פטור מחובת הפקדת בטוחות מעבר לערבויות קיימות;  וכן החרגתם של ערוצים אלה מהוראות מסוימות בחוק לעניין מתן רישיון מבקש רישיון שהפר את ההוראות לפי חוק הרשות השנייה, לעניין הגבלות על בעלויות צולבות של שידורי רדיו או טלוויזיה בנסיבות מסוימות וכן לעניין האיסור על החזקת אמצעי שליטה על ידי בעלים יחיד.",
  lastUpdated: "2023-02-27",
  completedDate: "2023-02-20",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-02-06",
          time: "09:30",
          sessionId: 2201070
        },
        {
          date: "2023-02-13",
          time: "12:00",
          sessionId: 2201210
        },
        {
          date: "2023-02-20",
          time: "09:30",
          sessionId: 2202034
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
