// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2201602,
  syncedAt: "2026-08-12",
  officialName: "חוק לפיצוי קורבנות טרור (פיצויים לדוגמה), התשפ\"ד-2024",
  type: "private",
  committeeId: "foreign-defense",
  status: "completed",
  summaryOfficial: "החוק מסדיר את זכאותם של נפגעי טרור ומשפחותיהם לפיצויים לדוגמה ממבצע מעשה טרור, מי שנתן תגמול בעד ביצוע מעשה טרור וכן מי שנקבעה חבותו לפי פקודת הנזיקין. נקבע כי סכום הפיצויים לדוגמה יהיה עשרה מיליון שקלים חדשים אם מעשה הטרור גרם למותו של אדם, וחמישה מיליון שקלים חדשים אם מעשה הטרור גרם לאדם נכות צמיתה. במסגרת זאת, מוצע שפיצויים אלו לא יהיו ניתנים לניכוי מכל סכום המשולם לנפגעי מעשה הטרור מטעם המדינה או מוסד ממוסדותיה. עוד נקבע כי נפגעי הטרור יוכלו לממש את פסק הדין מכל נכס של מתגמל הטרור; וביחס למתגמל טרור או מי שנקבעה חבותו לפי פקודת הנזיקין שהוא הרשות הפלסטינית גם מהכספים המוקפאים לפי חוק להקפאת כספים ששילמה הרשות הפלסטינית בזיקה לטרור המועברים אליה מממשלת ישראל, התשע\"ח-2018, למעט הכספים המועברים לרשות הפלסטינית מכוח חוקי היישום. בנוסף, נקבעה חזקה לפיה אם מדיניות מתמגל הטרור בעניין העברת תשלומים למבצעי מעשי טרור מיושמת בחקיקה ראשית, חקיקת משנה או הנחיות, הוא ייחשב מתמגל טרור לעניין מעשה טרור שגרם למוות או נכות, אלא אם הוכח אחרת.",
  lastUpdated: "2025-07-30",
  completedDate: "2024-03-11",
  initiators: [
    {
      kind: "mk",
      personId: 30672,
      name: "יצחק פינדרוס",
      partyId: "utj",
      factionName: "יהדות התורה"
    },
    {
      kind: "mk",
      personId: 30121,
      name: "עודד פורר",
      partyId: "yisrael-beiteinu",
      factionName: "ישראל ביתנו"
    },
    {
      kind: "mk",
      personId: 23558,
      name: "דוד ביטן",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-06-12",
          time: "12:00",
          sessionId: 2206686
        },
        {
          date: "2023-07-11",
          time: "11:30",
          sessionId: 2208349
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-01-22",
          time: "12:00",
          sessionId: 2213960
        },
        {
          date: "2024-03-05",
          time: "13:00",
          sessionId: 2215714
        },
        {
          date: "2024-03-06",
          time: "10:45",
          sessionId: 2216048
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
