// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2201424,
  syncedAt: "2026-08-12",
  officialName: "חוק־יסוד: הממשלה (תיקון מס' 12)",
  type: "private",
  committeeId: "special",
  committeeName: "הוועדה המיוחדת לתיקונים לחוק יסוד: הממשלה",
  status: "completed",
  summaryOfficial: "בחוק נקבע שנבצרות זמנית של ראש הממשלה למלא את תפקידו תהיה בשל אי מסוגלות פיזית או נפשית בלבד ותיקבע על ידי ראש הממשלה בהודעה לממשלה וליושב ראש הכנסת ובאישור ועדת הכנסת ברוב של 2/3 מחבריה. בנוסף, גם הממשלה תהיה רשאית להחליט ברוב של 3/4 מחבריה כי נבצר מראש הממשלה זמנית למלא את תפקידו בשל אי מסוגלות פיזית או נפשית; במקרה מעין זה הממשלה תכונס על ידי ראש הממשלה לבקשת 3/5 מחברי הממשלה ועל ראש הממשלה יהיה לכנס את הממשלה בתוך שלושה ימים ממועד הגשת הבקשה או במועד מאוחר יותר אם התבקש לכך בבקשה. אם ישיבת הממשלה לא כונסה בתוך שלושה ימים יכנס מזכיר הממשלה את הממשלה באופן מיידי וממלא מקום ראש הממשלה ינהל את הישיבה. החלטת הממשלה במקרה זה תעמוד בתוקפה שלושה ימים ותובא לאישור ועדת הכנסת ברוב של 2/3 מחבריה, ואם החלטת הממשלה ניתנה מטעמי בריאות, תהיה החלטת ועדת הכנסת גם על יסוד חוות דעת רפואית וועדת הכנסת תהיה רשאית לקבוע שהנבצרות תמשך לא יותר משבעה ימים מיום החלטת הממשלה; כן נקבע שאם ראש הממשלה לא יגיש חוות דעת רפואית בהתאם לכללים שקבעה ועדת הכנסת יראו אותו כאילו הודיע על נבצרותו. הארכת תקופת הנבצרות במקרה שוועדת הכנסת אישרה את החלטת הממשלה או במקרה שראש הממשלה לא הגיש  חוות דעת רפואית טעונה החלטה של הכנסת, לפי הצעת ועדת הכנסת, שהתקבלה ברוב של שמונים חברי הכנסת לתקופה שלא תימשך יותר מ-21 ימים בכל פעם, ובלבד שסך התקופות לא יעלה על 100 ימים כקבוע בסעיף 16(ב) לחוק-יסוד: הממשלה. עוד נקבע שסיום נבצרותו הזמנית של ראש הממשלה, אם זו נקבעה על ידי הממשלה ואושרה על ידי ועדת הכנסת וכן הארכת תקופת הנבצרות, תיעשה בהחלטה של ועדת הכנסת ואם נקבעה הנבצרות מטעמי בריאות - על יסוד חוות דעת רפואית. לבסוף, נקבע כי הוראות בדבר כינוס הכנסת או הוועדות בזמן פגרה לא יחולו לעניין זה.",
  lastUpdated: "2023-03-28",
  completedDate: "2023-03-22",
  initiators: [
    {
      kind: "mk",
      personId: 30701,
      name: "אופיר כץ",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30601,
      name: "ינון אזולאי",
      partyId: "shas",
      factionName: "התאחדות הספרדים שומרי תורה תנועתו של מרן הרב עובדיה יוסף זצ\"ל"
    },
    {
      kind: "mk",
      personId: 30812,
      name: "שמחה רוטמן",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-03-01",
          time: "15:35",
          sessionId: 2202649
        },
        {
          date: "2023-03-02",
          time: "13:00",
          sessionId: 2202655
        },
        {
          date: "2023-03-05",
          time: "12:20",
          sessionId: 2202702
        },
        {
          date: "2023-03-09",
          time: "11:00",
          sessionId: 2202842
        },
        {
          date: "2023-03-12",
          time: "10:00",
          sessionId: 2202959
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-03-13",
          time: "08:30",
          sessionId: 2203059
        },
        {
          date: "2023-03-19",
          time: "11:00",
          sessionId: 2203355
        },
        {
          date: "2023-03-20",
          time: "08:30",
          sessionId: 2203525
        },
        {
          date: "2023-03-21",
          time: "12:00",
          sessionId: 2203641
        },
        {
          date: "2023-03-22",
          time: "08:30",
          sessionId: 2203722
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
