// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2202778,
  syncedAt: "2026-08-12",
  officialName: "חוק הגדלת נקודות זיכוי להורים במס הכנסה והגדלת מענק עבודה (הוראת שעה) (תיקון), התשפ\"ג-2023",
  type: "governmental",
  committeeId: "finance",
  status: "completed",
  summaryOfficial: "החוק מאריך את תקופת הוראת השעה המעניקה נקודת זיכוי אחת נוספת לכל הורה בעד ילדיו שמלאו להם שש שנים לפחות אך טרם מלאו להם שלוש עשרה שנים בשנת 2022.",
  lastUpdated: "2024-05-02",
  completedDate: "2023-04-19",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-03-20",
          time: "10:30",
          sessionId: 2203380
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
