// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2202412,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק לתיקון פקודת מס הכנסה (פטור ממס במכירת מטבעות דיגיטליים לתושבי חוץ ובהקצאת מטבעות דיגיטליים לעובדים), התשפ\"ג-2023",
  type: "private",
  committeeId: "finance",
  status: "agenda",
  lastUpdated: "2023-07-11",
  initiators: [
    {
      kind: "mk",
      personId: 30839,
      name: "דן אילוז",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30710,
      name: "אריאל קלנר",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30812,
      name: "שמחה רוטמן",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2023-07-10",
          time: "11:00",
          sessionId: 2208641
        },
        {
          date: "2024-11-04",
          time: "13:00",
          sessionId: 2222976
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
