// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2202135,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק שירות המדינה (מינויים) (תיקון - מתן העדפה למשרתים בהעדפה מתקנת), התשפ\"ג-2023",
  type: "private",
  committeeId: "knesset-committee",
  status: "agenda",
  lastUpdated: "2026-07-12",
  initiators: [
    {
      kind: "mk",
      personId: 30867,
      name: "יצחק קרויזר",
      partyId: "otzma",
      factionName: "עוצמה יהודית בראשות איתמר בן גביר"
    },
    {
      kind: "mk",
      personId: 30859,
      name: "צביקה פוגל",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2024-09-25",
          time: "13:30",
          sessionId: 2222222
        },
        {
          date: "2024-11-25",
          time: "09:00",
          sessionId: 2224331
        },
        {
          date: "2024-12-18",
          time: "09:00",
          sessionId: 2225640
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
