// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2202411,
  syncedAt: "2026-08-12",
  officialName: "חוק הצלילה הספורטיבית (תיקון מס' 3), התשפ\"ג-2023",
  type: "governmental",
  committeeId: "education",
  status: "completed",
  summaryOfficial: "החוק מבקש לעגן בחקיקה ראשית את המצב הקיים בפועל, לפיו ילדים החל מגיל 8 יוכלו לבצע צלילת היכרות בכפוף לתנאים והגבלות שיפורטו בחוק. ההגבלות על צלילת היכרות לילדים החל מגיל 8, כוללות הגבלת עומק הצלילה ל-6 מטרים, ליווי צמוד של מדריך צלילה לכל צולל, בדיקת כשירות רפואית ותפקודית, אישור הורים חתום, ציוד המותאם לילד, משך הצלילה לא יעלה על 45 דקות, ולילדים עד גיל 10 לא ניתן לבצע יותר משתי צלילות היכרות ביום ועוד. כמו כן, החוק קובע ששר התרבות והספורט רשאי לקבוע תנאים שונים לצלילת היכרות בבריכת שחייה מסוג שהוא יקבע, השונים מהתנאים שפורטו לעיל, ובלבד שלא תיפגע בטיחות הצוללים, ושלא ניתן יהיה לקבוע גיל הנמוך מגיל 8 לצלילת היכרות בבריכת שחייה. עוד נקבע שהרשות המוסמכת רשאית לקבוע הוראות שיחולו על מרכזי צלילה לעניין עריכת צלילת היכרות.",
  lastUpdated: "2023-08-02",
  completedDate: "2023-07-25",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-06-20",
          time: "10:30",
          sessionId: 2207089
        },
        {
          date: "2023-07-03",
          time: "11:30",
          sessionId: 2207946
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
