// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2203951,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק שירות התעסוקה (תיקון מס' 24) (הגברת התחרות בסיעוד הביתי), התשפ\"ה–2025",
  type: "private",
  committeeId: "labor-welfare",
  status: "agenda",
  lastUpdated: "2025-07-24",
  initiators: [
    {
      kind: "mk",
      personId: 30832,
      name: "אליהו רביבו",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-05-26",
          time: "11:00",
          sessionId: 2232033
        }
      ]
    },
    {
      stage: "first",
      state: "inProgress",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
