// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2203342,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק פיקוח על בתי ספר (תיקון - איסור העסקת מורשעי ותומכי טרור ופיקוח על תכני הלימוד למניעת הסתה), התשפ\"ג-2023",
  type: "private",
  committeeId: "education",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2024-03-03",
  initiators: [
    {
      kind: "mk",
      personId: 30711,
      name: "עמית הלוי",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2023-06-20",
          time: "12:30",
          sessionId: 2207175
        },
        {
          date: "2023-07-04",
          time: "12:30",
          sessionId: 2207972
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
