// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2203894,
  syncedAt: "2026-08-12",
  officialName: "חוק לתיקון דיני הבחירות לרשויות המקומיות, התשפ\"ג-2023",
  type: "governmental",
  committeeId: "interior-environment",
  status: "completed",
  summaryOfficial: "החוק מאגד תיקוני חקיקה שונים הנוגעים לייעול הליך הבחירות ברשויות המקומיות, לרבות אפשרות למנוי מזכיר קלפי שני, הסדרת הצבעת בעלי תפקידים, הטלת חובת פרסום הרכב ועדת הבחירות של רשות מקומית והסדרת התהליך לתיקון ליקויים ברשימת מועמדים.",
  lastUpdated: "2024-01-02",
  completedDate: "2023-07-10",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-05-29",
          time: "10:00",
          sessionId: 2205609
        },
        {
          date: "2023-06-13",
          time: "10:00",
          sessionId: 2205610
        },
        {
          date: "2023-06-14",
          time: "09:00",
          sessionId: 2207099
        },
        {
          date: "2023-06-20",
          time: "10:30",
          sessionId: 2207148
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
