// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2203907,
  syncedAt: "2026-08-12",
  officialName: "חוק הכניסה לישראל (תיקון מס' 38), התשפ\"ד–2024",
  type: "private",
  committeeId: "national-security",
  status: "completed",
  summaryOfficial: "חוק הכניסה לישראל, התשי\"ב–1952, מתייחס בין היתר לעבירות העוסקות בהסעה, הלנה והעסקה של תושבי אזור יהודה והשומרון שנכנסו לישראל או שוהים במדינה שלא כדין, וזאת על מנת לצמצם את התופעה זו. בעקבות הגידול שחל בשנים האחרונות בהיקף התופעה לצד השלכותיה על ביטחון אזרחי ישראל, תוקן חוק הכניסה לישראל כך שהוחמרה הענישה בעבירות הרלוונטיות, נקבעו מנגנונים לאכיפתן וקנסות מזעריים. \nבמסגרת תיקון מספר 38, הוחלט לשנות את עונש המאסר הקבוע בין היתר, בעבירת הסעה, הלנה והעסקה של שוהה שלא כדין כאמור, משנתיים לארבע שנות מאסר, וכן להחמיר את עונשי המאסר הקבועים לאותן עבירות בנסיבות מחמירות, מחמש לשבע שנות מאסר. כמו כן, נקבע כהוראת שעה עד ליום כ\"ד בניסן התשפ\"ז (1 במאי 2027), עונש מזערי על עבירות הסעה, העסקה והלנה של שוהה שלא כדין, כך שהעונש שיטיל בית המשפט לא יפחת מרבע העונש המרבי הקבוע לעבירות אלו, אלא אם ראה לנכון לסטות מכך לפי שיקול דעתו בנסיבות מתאימות ומטעמים מיוחדים.\nבנוסף, נקבעה מחדש הוראת השעה בעניין הטלת קנסות מזעריים, לתקופה שעד יום כ\"ד בניסן התשפ\"ז (1 במאי 2027), תוך קביעת שיעור קנסות מינימלי לצד מתן סמכות לבית המשפט להקל ולסטות מסכומים אלו, אם סבר כי קיימים טעמים מיוחדים לכך. בהוראת שעה נוספת עד ליום כ\"ד בניסן התשפ\"ז (1 במאי 2027), נקבע גובה מזערי לקנס המוטל על ידי בית המשפט על אדם שהורשע בעבירות הסעת שוהה שלא כדין, כך שלא יפחת ממחצית שווי הרכב, אלא אם סבר בית המשפט שיש לסטות מכך מטעמים מיוחדים. \nמעבר לכך, נקבעו הסדרים נוספים שנועדו להיטיב את הטיפול בתופעה כאמור ולצמצמה, לרבות מתן סמכות לבית המשפט להתלות רישיון של חשוד בעבירות הסעה שלא כדין, הטלת חובה על בעל רכב לנקוט באמצעים סבירים למניעת עבירה הכוללת מתן הרשאה לשימוש ברכבו שלא כדין על ידי תושב זר וחובת דיווח שנתית לוועדה לביטחון לאומי.",
  lastUpdated: "2025-08-13",
  completedDate: "2024-04-03",
  initiators: [
    {
      kind: "mk",
      personId: 30859,
      name: "צביקה פוגל",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    },
    {
      kind: "mk",
      personId: 30722,
      name: "יבגני סובה",
      partyId: "yisrael-beiteinu",
      factionName: "ישראל ביתנו"
    },
    {
      kind: "mk",
      personId: 427,
      name: "אביגדור ליברמן",
      partyId: "yisrael-beiteinu",
      factionName: "ישראל ביתנו"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-03-11",
          time: "11:45",
          sessionId: 2215906
        },
        {
          date: "2024-03-19",
          time: "10:00",
          sessionId: 2216372
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-03-31",
          time: "13:00",
          sessionId: 2216776
        },
        {
          date: "2024-04-01",
          time: "11:00",
          sessionId: 2217156
        },
        {
          date: "2026-05-05",
          time: "15:45",
          sessionId: 2242658
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
