// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2203829,
  syncedAt: "2026-08-12",
  officialName: "חוק הנכים (תגמולים ושיקום) (תיקון מס' 31), התשפ\"ג-2023 ",
  type: "governmental",
  committeeId: "labor-welfare",
  status: "completed",
  summaryOfficial: "החוק קובע כי נכי צה\"ל וכן נפגעי פעולות איבה הזכאים לתגמול חודשי, זכאים להשתתפות המדינה בדמי ביטוח חיים, ביטוח בריאות וביטוח סיעוד בסכום שיקבע שר הביטחון או שר העבודה, לפי העניין, באישור ועדת העבודה והרווחה של הכנסת.\nכמו כן, החוק קובע כי קצין התגמולים או פקיד תביעות, לפי העניין, ינכו מהתגמול של נכה או נפגע איבה דמי חברות בארגון היציג, תשלומים לקרן לעזרה הדדית של הארגון היציג ודמי השתתפות בביטוח חיים הדדי ובביטוח סיעודי הדדי שנערכו באמצעות הארגון היציג – עד לסכום מירבי שיקבע שר הביטחון או שר העבודה, לפי העניין, באישור ועדת העבודה והרווחה.\nקצין התגמולים ינכה כאמור מתגמולו של נכה צה\"ל רק לאחר שהודיע לו בכתב על זכותו להגיש התנגדות לניכוי, ואם הנכה שהוחל לנכות לו לראשונה, הגיש התנגדות תוך 30 ימים מום ההודעה, יושב לו סכום הניכוי אם נוכה.\nעוד נקבעו הוראות המסמיכות לנכות מתגמולו של נכה  צה\"ל או של נפגע איבה, לפי בקשה מפורשת בכתב, הלוואות שניטלו מהארגון היציג ונקבעה מגבלה על שיעור הגבייה מהתגמול. ההגבלה כאמור תחול על הלוואות שניטלו לאחר ה-15 במאי 23. נוסף על כך, נקבעה הוראה המאפשרת לנכות מתגמולו של נכה צה\"ל דמי חברות במיתקן חברה וספורט של ארגון נכי צה\"ל, אם ביקש זאת בכתב.\nנוסף על כך נקבע כי האגף או המוסד לביטוח לאומי, לפי העניין, יעבירו לארגון היציג הרלוונטי, מדי חודש דיווח על כל אחד מהניכויים מהתגמול החודשי כאמור.",
  lastUpdated: "2023-05-29",
  completedDate: "2023-03-29",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-03-23",
          time: "14:00",
          sessionId: 2203780
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
