// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2204663,
  syncedAt: "2026-08-12",
  officialName: "חוק ארגון הפיקוח על העבודה (תיקון מס' 12), התשפ\"ד-2023",
  type: "governmental",
  committeeId: "labor-welfare",
  status: "completed",
  summaryOfficial: "חוק זה מאריך את תוקף הוראת השעה לעניין עוזרי בטיחות בשנתיים נוספות וכן מכניס בהוראה זו מספר שינויים. ראשית, החוק מבהיר כי החובה למנות עוזר בטיחות חלה רק באתר בנייה בו נדרש מינוי של מנהל עבודה. שנית, בחוק נוספה הוראה המאפשרת גם לאוכלוסיות נוספות להיות עוזרי בטיחות -  כך שכעת גם אדם ללא ניסיון בעבודות בניה או בניה הנדסית יוכל לשמש כעוזר בטיחות וזאת אם עבר בהצלחה הכשרה מעשית בהיקף של יותר ממאה שעות, וכן יוכל לשמש כעוזר בטיחות מי שהוא מהנדס או הנדסאי בענף הנדסה אזרחית או מי שהוא כשיר להיות מנהל עבודה או ממונה בטיחות, כל עוד לא מונה לתפקידים אלה באותו אתר בנייה. שלישית, בחוק נוספו תפקידים נוספים לתפקידים של עוזר הבטיחות, כמו תפקיד של סיוע למנהל העבודה במעקב אחר תיקון של הוראת בטיחות שהחובה לקיומה מוטלת על מנהל העבודה.",
  lastUpdated: "2024-01-11",
  completedDate: "2023-11-20",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-11-14",
          time: "11:30",
          sessionId: 2211402
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
