// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2204484,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק העונשין (תיקון מס' 153) (החזקה, נשיאה והובלה של כמה כלי נשק), התשפ\"ד–2024",
  type: "private",
  committeeId: "constitution",
  status: "dropped",
  offPipelineReason: "נעצרה",
  lastUpdated: "2025-04-20",
  initiators: [
    {
      kind: "mk",
      personId: 30833,
      name: "אלמוג כהן",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-02-26",
          time: "11:30",
          sessionId: 2215598
        },
        {
          date: "2024-06-19",
          time: "09:00",
          sessionId: 2219071
        },
        {
          date: "2024-07-21",
          time: "13:31",
          sessionId: 2221005
        }
      ]
    },
    {
      stage: "first",
      state: "inProgress",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
