// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2204871,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק העונשין (תיקון - קביעת עונש מינימום לעבירות יידוי אבנים), התשפ\"ג-2023",
  type: "private",
  committeeId: "constitution",
  status: "agenda",
  lastUpdated: "2025-03-12",
  initiators: [
    {
      kind: "mk",
      personId: 30863,
      name: "שרון ניר",
      partyId: "yisrael-beiteinu",
      factionName: "ישראל ביתנו"
    },
    {
      kind: "mk",
      personId: 427,
      name: "אביגדור ליברמן",
      partyId: "yisrael-beiteinu",
      factionName: "ישראל ביתנו"
    },
    {
      kind: "mk",
      personId: 30121,
      name: "עודד פורר",
      partyId: "yisrael-beiteinu",
      factionName: "ישראל ביתנו"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: []
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
