// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2205266,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק המרכז לגביית קנסות, אגרות והוצאות (תיקון מס' 30) (פיצויים שהטיל בית משפט צבאי), התשפ\"ד–2024",
  type: "private",
  committeeId: "constitution",
  status: "agenda",
  lastUpdated: "2024-12-10",
  initiators: [
    {
      kind: "mk",
      personId: 30877,
      name: "משה פסל",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30706,
      name: "קטי קטרין שטרית",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30812,
      name: "שמחה רוטמן",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-03-04",
          time: "11:00",
          sessionId: 2214886
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2024-12-04",
          time: "09:00",
          sessionId: 2224198
        },
        {
          date: "2024-12-10",
          time: "14:00",
          sessionId: 2225090
        },
        {
          date: "2024-12-23",
          time: "09:00",
          sessionId: 2224970
        },
        {
          date: "2025-03-04",
          time: "09:00",
          sessionId: 2229248
        },
        {
          date: "2025-03-20",
          time: "09:00",
          sessionId: 2229906
        },
        {
          date: "2025-06-03",
          time: "13:30",
          sessionId: 2232310
        },
        {
          date: "2025-06-17",
          time: "09:00",
          sessionId: 2232551
        },
        {
          date: "2025-07-08",
          time: "14:20",
          sessionId: 2233441
        }
      ]
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
