// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2205309,
  syncedAt: "2026-08-12",
  officialName: "חוק לתיקון סדרי הדין (חקירת עדים) (תיקון מס' 10), התשפ\"ד–2024",
  type: "private",
  committeeId: "constitution",
  status: "completed",
  summaryOfficial: "החוק מחיל את ההסדרים הקבועים לגבי עדות במשפט פלילי גם על תביעה נזיקית נגד נתבע שהוגש נגדו כתב אישום בעבירה שבה נמסרת עדות של קטין או חסר ישע שהוא נפגע עבירת מין, עבירת סחר בבני אדם או עבירת אלימות חמורה המנויה בתוספת, כך שהקטין יוכל למסור את עדותו בבית המשפט באופן המותאם לו. החוק קובע  הסדר שלפיו במשפט פלילי בשל עבירת מין או סחר בבני אדם או בשל עבירות אלימות חמורה במשפחה, בית המשפט רשאי להורות כי קטין או נפגע עבירת מין או סחר בבני אדם, ימסור את עדותו שלא בנוכחות הנאשם, אם נוכח שמסירת העדות בנוכחותו עלולה לפגוע במתלונן או לפגום בעדות. בית המשפט לא יחליט כאמור אלא לאחר שנתן הזדמנות לבעלי הדין להשמיע את טענותיהם ונעשו הסידורים הדרושים כדי לאפשר לבית המשפט ולנאשם לצפות בעדות. עוד קובע החוק לעניין קטינים כי בעדות בעניין עבירה המנויה בתוספת לחוק, הנאשם לא יחקור בעצמו את הקטין אלא באמצעות סניגורו. נוסף על כך, החוק מחיל את ההסדר הקבוע לגבי עדות במשפט פלילי גם על עדות של בגיר נפגע עבירת מין או סחר בבני אדם בתביעת נזיקין נגד נתבע שהוגש נגדו כתב אישום בעבירה כאמור. בנוסף נקבע כי במקרה שבו לא הוגש כתב אישום נגד הנתבע יחולו חלק מההסדרים כך שבמקרים של תקיפה מינית או התעללות שבוצעה בקטין על ידי בן משפחה או אחראי, ובמקרים של תקיפה מינית שבוצעה במי שטרם מלאו לו 21 שנים תוך ניצול יחסי מרות או על ידי בן משפחה, בית המשפט יהיה רשאי לקבוע שהנפגע יעיד שלא בנוכחות הנתבע, ואולם, לא תאסר חקירה נגדית על ידי הנתבע. כמו כן, נקבע כי תיאסר חקירתו בדבר עברו המיני. בנוסף, הורחבה התוספת לחוק המפרטת את העבירות שבהן יחול ההסדר לעניין קטינים ושעניינן עבירות מין ועבירות אלימות מסוימות והמתייחסת הן להסדרים הקבועים לגבי עדות במשפט פלילי והן לנקבע בחוק זה בדבר עדות בתביעה נזיקית, והוספו לה עבירות חמורות נוספות.",
  lastUpdated: "2025-02-23",
  completedDate: "2024-07-23",
  initiators: [
    {
      kind: "mk",
      personId: 30837,
      name: "דבי ביטון",
      partyId: "yesh-atid",
      factionName: "יש עתיד"
    },
    {
      kind: "mk",
      personId: 30831,
      name: "אלי דלל",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30868,
      name: "יונתן מישרקי",
      partyId: "shas",
      factionName: "התאחדות הספרדים שומרי תורה תנועתו של מרן הרב עובדיה יוסף זצ\"ל"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-02-26",
          time: "11:30",
          sessionId: 2215598
        },
        {
          date: "2024-03-14",
          time: "09:30",
          sessionId: 2216125
        },
        {
          date: "2024-04-02",
          time: "09:40",
          sessionId: 2217062
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-07-16",
          time: "10:30",
          sessionId: 2220276
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
