// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2205767,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק השידור הציבורי הישראלי (תיקון מס' 10 והוראת שעה), התשפ\"ה–2025",
  type: "private",
  committeeId: "economy",
  status: "agenda",
  lastUpdated: "2025-07-24",
  initiators: [
    {
      kind: "mk",
      personId: 30710,
      name: "אריאל קלנר",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-03-26",
          time: "09:00",
          sessionId: 2216805
        },
        {
          date: "2024-12-09",
          time: "10:45",
          sessionId: 2224484
        },
        {
          date: "2025-01-15",
          time: "09:00",
          sessionId: 2226674
        },
        {
          date: "2025-03-17",
          time: "09:30",
          sessionId: 2229690
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-05-26",
          time: "10:00",
          sessionId: 2231261
        },
        {
          date: "2025-06-09",
          time: "09:00",
          sessionId: 2232587
        }
      ]
    },
    {
      stage: "secondThird",
      state: "inProgress",
      discussions: []
    }
  ]
};
