// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2205959,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק לתיקון פקודת מסי העירייה ומסי הממשלה (פטורין) (פטור מארנונה למצללה), התשפ\"ג-2023 ",
  type: "private",
  committeeId: "finance",
  status: "agenda",
  lastUpdated: "2024-06-26",
  initiators: [
    {
      kind: "mk",
      personId: 30877,
      name: "משה פסל",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2024-07-16",
          time: "11:25",
          sessionId: 2220608
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
