// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2205831,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק שירותי הדת היהודיים (בחירות רבני עיר, רבנים אזוריים, רבני יישוב ורבני שכונות), התשפ\"ג-2023",
  type: "private",
  committeeId: "constitution",
  status: "agenda",
  lastUpdated: "2023-08-08",
  initiators: [
    {
      kind: "mk",
      personId: 30812,
      name: "שמחה רוטמן",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2023-07-03",
          time: "10:00",
          sessionId: 2208211
        },
        {
          date: "2023-07-10",
          time: "09:00",
          sessionId: 2208400
        },
        {
          date: "2023-07-13",
          time: "09:00",
          sessionId: 2208838
        },
        {
          date: "2023-07-16",
          time: "14:30",
          sessionId: 2208912
        },
        {
          date: "2023-07-23",
          time: "08:00",
          sessionId: 2209308
        },
        {
          date: "2023-07-25",
          time: "12:00",
          sessionId: 2209403
        },
        {
          date: "2023-07-30",
          time: "09:00",
          sessionId: 2209515
        },
        {
          date: "2023-08-01",
          time: "09:30",
          sessionId: 2209518
        },
        {
          date: "2023-08-07",
          time: "09:00",
          sessionId: 2209424
        },
        {
          date: "2023-08-09",
          time: "09:30",
          sessionId: 2209425
        },
        {
          date: "2023-08-13",
          time: "09:30",
          sessionId: 2209919
        },
        {
          date: "2023-09-20",
          time: "12:00",
          sessionId: 2210164
        },
        {
          date: "2023-10-08",
          time: "12:00",
          sessionId: 2210386
        },
        {
          date: "2024-03-19",
          time: "11:00",
          sessionId: 2216466
        },
        {
          date: "2024-06-18",
          time: "10:00",
          sessionId: 2219322
        },
        {
          date: "2024-06-18",
          time: "15:00",
          sessionId: 2219447
        },
        {
          date: "2024-06-19",
          time: "08:30",
          sessionId: 2219465
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
