// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2205720,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק לביטול ההפליה ברכישת מקרקעין ביהודה והשומרון, התשפ\"ו–2025",
  type: "private",
  committeeId: "foreign-defense",
  status: "agenda",
  lastUpdated: "2025-12-07",
  initiators: [
    {
      kind: "mk",
      personId: 30852,
      name: "משה סולומון",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    },
    {
      kind: "mk",
      personId: 30849,
      name: "לימור סון הר מלך",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    },
    {
      kind: "mk",
      personId: 532,
      name: "יולי יואל אדלשטיין",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-02-04",
          time: "13:30",
          sessionId: 2227989
        },
        {
          date: "2025-02-13",
          time: "09:30",
          sessionId: 2228214
        },
        {
          date: "2025-05-13",
          time: "14:00",
          sessionId: 2231401
        },
        {
          date: "2025-11-25",
          time: "09:30",
          sessionId: 2237011
        }
      ]
    },
    {
      stage: "first",
      state: "inProgress",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
