// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2206507,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק בתי דין רבניים (סדרי דין בעת מצב חירום מיוחד), התשפ\"ג-2023",
  type: "governmental",
  committeeId: "constitution",
  status: "agenda",
  lastUpdated: "2024-03-12",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2024-01-29",
          time: "09:30",
          sessionId: 2213962
        },
        {
          date: "2024-02-13",
          time: "14:00",
          sessionId: 2214926
        }
      ]
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
