// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2206912,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק לקידום הנשים בישראל, התשפ\"ג-2023",
  type: "private",
  committeeId: "special",
  committeeName: "הוועדה המשותפת של ועדת החוקה, חוק ומשפט ושל הוועדה לקידום מעמד האישה ולשוויון מגדרי לדיון בהצעת חוק לקידום הנשים בישראל, התשפ\"ג-2023 (פ/3670/25)",
  status: "agenda",
  lastUpdated: "2023-07-18",
  initiators: [
    {
      kind: "mk",
      personId: 30849,
      name: "לימור סון הר מלך",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2023-07-17",
          time: "09:30",
          sessionId: 2208846
        },
        {
          date: "2023-07-18",
          time: "13:00",
          sessionId: 2209195
        },
        {
          date: "2023-07-18",
          time: "15:55",
          sessionId: 2209231
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
