// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2206948,
  syncedAt: "2026-08-12",
  officialName: "חוק עבודת הנוער (תיקון מס' 22), התשפ\"ד-2024",
  type: "governmental",
  committeeId: "labor-welfare",
  status: "completed",
  summaryOfficial: "התיקון לחוק קובע  כי מעסיק יהיה רשאי להעסיק צעיר (בגילאים 16 עד 18) עד השעה 1:00 בלילה (במקום עד השעה 20.00) בתקופת חופשת לימודים רשמית, למעט ביום שלמחרתו מתקיימים לימודים. כמו כן התיקון לחוק קובע כי אם עבודתו של הצעיר בחופשה כאמור הסתיימה לאחר השעה 23:00, המעסיק יהיה מחויב להחזיר את הצעיר הביתה בעצמו או על ידי מי מטעמו, ולעניין זה קובע התיקון כי אם הפרש הזמנים בין סיום העבודה לאחר השעה 23:00 ובין יציאת הצעיר בחזרה לביתו עלה על חצי שעה, יראו במעסיק כמי שלא החזיר את הצעיר לביתו בסיום העבודה. התיקון מסמיך את שר העבודה לקבוע, לשם הגנה על צעירים, שההוראות האמורות לא יחולו בעבודות או בענפי עבודה מסוימים. התיקון לחוק קובע עבירה פלילית וכן עיצום כספי לגבי מעסיק שהפר את החובה להחזיר את הצעיר לביתו. עוד קובע התיקון לחוק כי באפשרות בית הדין לעבודה לפסוק פיצויים לדוגמה (דהיינו, פיצויים שאינם תלויים בנזק) בסכום שלא יעלה על 5,000 ש\"ח בתביעה אזרחית שהגיש נער או ארגון עובדים מטעמו, בשל כך שהנער שהועסק בשעות הלילה שלא במסגרת השעות שנקבעו בחוק או שהועסק אחרי השעה 23.00 בלא שהמעסיק החזירו לביתו. כמו כן נקבע כי בתביעה אזרחית כאמור שבה המעסיק לא הציג רישומי נוכחות של הנער או הצעיר תהיה חובת ההוכחה עליו שלא העסיק את הנער בניגוד להוראות האמורות.",
  lastUpdated: "2024-10-09",
  completedDate: "2024-06-03",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-05-22",
          time: "10:00",
          sessionId: 2217955
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
