// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2206819,
  syncedAt: "2026-08-12",
  officialName: "חוק המידע הפלילי ותקנת השבים (תיקון מס' 10), התשפ\"ו–2026",
  type: "private",
  committeeId: "constitution",
  status: "completed",
  summaryOfficial: "נקבע כי מעסיק רשאי לבקש מהמשטרה הודעה המציינת אם יש או אין למועמד בגיר לעבודה רישום פלילי בגין עבירת טרור חמורה, הסתה לטרור או הזדהות עם ארגון טרור. בקשה לקבלת ההודעה מותנית בהסכמת המועמד בכתב, וההודעה תינתן רק על עבירות שבוצעו בהיותו בגיר וטרם התיישנו, ללא פירוט העבירות עצמן. ככל שקיים רישום פלילי, המעסיק מחויב לאפשר למועמד להציג מידע על מהות העבירה, נסיבותיו האישיות ושיקומו בטרם יקבל החלטה על העסקתו.\nעוד נקבע כי על המעסיק תחול חובת סודיות לגבי המידע, ונאסר עליו לצלמו, להעתיקו, למסור אותו לאחר או להשתמש בו לכל מטרה אחרת שאינה בחינת העסקתו של המועמד. במקביל, המשטרה תשמור למשך שבע שנים תיעוד של פרטי המעסיקים והמועמדים שלגביהם התבקש המידע. לשם יישום החוק, הוסמכו שרי המשפטים והביטחון הלאומי להתקין תקנות שיאפשרו בין היתר למעסיק לבקש ולקבל את ההודעה במערכת ממשלתית מקוונת.",
  lastUpdated: "2026-07-28",
  completedDate: "2026-02-23",
  initiators: [
    {
      kind: "mk",
      personId: 30772,
      name: "ניסים ואטורי",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-07-23",
          time: "14:00",
          sessionId: 2220616
        },
        {
          date: "2024-09-10",
          time: "13:30",
          sessionId: 2221917
        },
        {
          date: "2024-11-04",
          time: "12:00",
          sessionId: 2222938
        },
        {
          date: "2024-11-04",
          time: "13:00",
          sessionId: 2222942
        },
        {
          date: "2024-12-09",
          time: "12:15",
          sessionId: 2224566
        },
        {
          date: "2024-12-09",
          time: "13:00",
          sessionId: 2225106
        },
        {
          date: "2025-02-03",
          time: "12:30",
          sessionId: 2227556
        },
        {
          date: "2025-03-19",
          time: "09:00",
          sessionId: 2229899
        },
        {
          date: "2025-03-23",
          time: "09:00",
          sessionId: 2230318
        },
        {
          date: "2025-03-23",
          time: "12:00",
          sessionId: 2230353
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-06-11",
          time: "09:00",
          sessionId: 2232557
        },
        {
          date: "2025-07-08",
          time: "11:30",
          sessionId: 2233735
        },
        {
          date: "2025-12-02",
          time: "12:01",
          sessionId: 2236697
        },
        {
          date: "2026-01-13",
          time: "13:00",
          sessionId: 2239021
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
