// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2206093,
  syncedAt: "2026-08-12",
  officialName: "חוק תובענות ייצוגיות (תיקון מס' 15), התשפ\"ד-2024",
  type: "governmental",
  committeeId: "constitution",
  status: "completed",
  summaryOfficial: "התיקון לחוק קובע כי שר המשפטים רשאי, באישור ועדת החוקה חוק ומשפט של הכנסת, לשנות בצו פרטים בתוספת השנייה לחוק, לאחר התייעצות עם שר האוצר, וזאת בשונה מהדין שהיה קיים ולפיו שר המשפטים יכול רק להוסיף פרטים לתוספת השנייה. כמו כן, תוקן פריט 11 לתוספת השנייה, ונקבע כי תביעה ייצוגית כלפי רשות מקרקעי ישראל, להשבת סכומים שגבתה שלא כדין, במסגרת פעילותה לפי חוק רשות מקרקעי ישראל, התש\"ך–1960, תוגש לפי פריט 11 בלבד. משמעות תיקון זה כי לרשות מקרקעי ישראל תהיינה ההגנות שניתנו למדינה ובכלל זה האפשרות להימנע מאישור התביעה כתובענה אזרחית אם הרשות הודיעה על חדילה, וכן הגבלת תקופת ההשבה לשנתיים בלבד.",
  lastUpdated: "2025-05-05",
  completedDate: "2024-03-26",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-07-09",
          time: "14:30",
          sessionId: 2208404
        },
        {
          date: "2024-03-10",
          time: "10:30",
          sessionId: 2215555
        },
        {
          date: "2024-03-18",
          time: "12:20",
          sessionId: 2216245
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
