// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2207737,
  syncedAt: "2026-08-12",
  officialName: "חוק שוויון זכויות לאנשים עם מוגבלות (תיקון מס' 25), התשפ\"ד-2024",
  type: "governmental",
  committeeId: "labor-welfare",
  status: "completed",
  summaryOfficial: "נקבע כי חברות ממשלתיות וחברות בת ממשלתיות המעסיקות 100 עובדים לפחות יחויבו לפעול לייצוג הולם של אנשים עם מוגבלות בקרב עובדיהם כפי שקבוע היום החוק לגבי גופים ציבוריים שהם מעסיקים גדולים. נקבע כי הוראות אלה יכנסו לתוקף ב-7 באפריל 2025 וכי התחולה תהיה מדורגת כך שבשנה הראשונה יהיה יעד הייצוג ההולם 3.5% מהעובדים ורק בתום השנה האמורה יהיה יעד הייצוג  5% מהעובדים. נוסף על כך, בשל העברת סמכויות משר הכלכלה והתעשייה לשר העבודה, נקבעו תיקונים שונים להוראות בחוק אשר קובעות סמכות לשר הכלכלה והתעשייה או למשרד הכלכלה והתעשייה.",
  lastUpdated: "2024-08-01",
  completedDate: "2024-04-02",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-03-26",
          time: "13:00",
          sessionId: 2216797
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
