// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2207137,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק-יסוד: ירושלים בירת ישראל (תיקון - איסור על פתיחת נציגות דיפלומטית זרה)",
  type: "private",
  committeeId: "constitution",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2024-07-09",
  initiators: [
    {
      kind: "mk",
      personId: 30839,
      name: "דן אילוז",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2024-07-09",
          time: "09:00",
          sessionId: 2219938
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
