// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2207030,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק הרשויות המקומיות (ניהול סיכונים תאגידי), התשפ\"ג-2023 ",
  type: "private",
  committeeId: "interior-environment",
  status: "agenda",
  lastUpdated: "2025-03-25",
  initiators: [
    {
      kind: "mk",
      personId: 30842,
      name: "חנוך דב מלביצקי",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2025-03-23",
          time: "13:00",
          sessionId: 2230330
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
