// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2208654,
  syncedAt: "2026-08-12",
  officialName: "חוק שחרור על-תנאי ממאסר (תיקון מס' 17 – הוראת שעה) (תיקון מס' 3), התשפ\"ד-2023",
  type: "governmental",
  committeeId: "national-security",
  status: "completed",
  summaryOfficial: "נקבעה הארכה להוראת השעה המסדירה את פעילות היחידה לשחרור ממאסרים קצרים, שדנה בבקשות לשחרור מוקדם של אסירים שנגזרו עליהם תקופות מאסר של 3 חודשים עד שנה, עד ליום י\"ד בכסלו התשפ\"ה (15 בדצמבר 2024).",
  lastUpdated: "2025-08-14",
  completedDate: "2023-09-19",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-09-06",
          time: "13:45",
          sessionId: 2209500
        },
        {
          date: "2023-09-19",
          time: "10:00",
          sessionId: 2210236
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
