// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2209512,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק ביטוח בריאות ממלכתי (תיקון מס' ...) (הגדרת אמבולנס לעניין החזר דמי נסיעה), התשפ\"ב–2023",
  type: "private",
  committeeId: "health",
  status: "agenda",
  lastUpdated: "2023-07-25",
  initiators: [
    {
      kind: "mk",
      personId: 30702,
      name: "חוה אתי עטייה",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "inProgress",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
