// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2209485,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק התקנת מצלמות לשם הגנה על פעוטות במעונות יום לפעוטות (תיקון - החלה על גני ילדים והגברת האכיפה), התשפ\"ד-2023",
  type: "private",
  committeeId: "education",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2024-05-28",
  initiators: [
    {
      kind: "mk",
      personId: 30558,
      name: "יוסף עטאונה",
      partyId: "hadash-taal",
      factionName: "חד\"ש-תע\"ל"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2024-05-07",
          time: "10:00",
          sessionId: 2217585
        },
        {
          date: "2024-05-28",
          time: "13:30",
          sessionId: 2218244
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
