// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2209023,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק ביטוח בריאות ממלכתי (תיקון - השתתפות עצמית ברכישת תכשיר מרשם מבית מרקחת שאינו בהסדר עם קופת החולים), התשפ\"ג-2023",
  type: "private",
  committeeId: "health",
  status: "agenda",
  lastUpdated: "2024-12-11",
  initiators: [
    {
      kind: "mk",
      personId: 560,
      name: "אחמד טיבי",
      partyId: "hadash-taal",
      factionName: "חד\"ש-תע\"ל"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2024-12-10",
          time: "14:00",
          sessionId: 2225090
        },
        {
          date: "2025-01-27",
          time: "12:00",
          sessionId: 2227040
        },
        {
          date: "2025-07-21",
          time: "09:00",
          sessionId: 2233780
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
