// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2210781,
  syncedAt: "2026-08-12",
  officialName: "חוק לדחיית הבחירות הכלליות לרשויות המקומיות (תיקון), התשפ\"ד-2023",
  type: "governmental",
  committeeId: "interior-environment",
  status: "completed",
  summaryOfficial: "בחוק זה נקבעו מספר הסדרים משלימים הנובעים מדחיית הבחירות הכלליות לרשויות המקומיות עקב מלחמת \"חרבות ברזל\". כך למשל, נקבע מנגנון פיצוי עיזבון של מועמד בבחירות לראשות מועצה אזורית שהוכר כחלל מערכות ישראל או מי שנפטר כתוצאה מפגיעת איבה בקשר למצב הביטחוני המיוחד, על הוצאות בחירות שהוציא המועמד כדין. עוד נקבע, כי החובה לצאת לחופשה או להפסיק את השירות מיום הגשת הרשימות, החלה על המועמדים העובדים בשירות המדינה ועל אנשי הקבע של צה\"ל, לא תחול עד היום ה-30 שלפני מועד הבחירות החדש. כמו כן, נקבע כי מועמד שנדרש לצאת לחופשה ללא תשלום או להפסיק את שירותו על מנת להתמודד בבחירות, ועשה כן לפי כל דין, זכאי לתשלום מיוחד ממעסיקו בעד התקופה בה שהה בחופשה או שהופסק בה שירותו בשיעור של 70% מהשכר הרגיל שלו, ולא יותר מ-11,870 ש\"ח. בנוסף, נקבע כי במסגרת הוראת שעה, יוקלו התנאים לנטילת מקדמות למימון בחירות, יתאפשר החזר חלקי מוקדם של ערבונות שניתנו לשם התמודדות בבחירות ואף סכום התרומות המותר למועמד או לרשימה יעלה.",
  lastUpdated: "2024-01-02",
  completedDate: "2023-11-01",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-10-29",
          time: "10:00",
          sessionId: 2210859
        },
        {
          date: "2023-10-30",
          time: "10:45",
          sessionId: 2210974
        },
        {
          date: "2023-10-31",
          time: "12:00",
          sessionId: 2210973
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
