// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2210330,
  syncedAt: "2026-08-12",
  officialName: "חוק הכשרות המשפטית והאפוטרופסות (תיקון מס' 24), התשפ\"ו–2026",
  type: "private",
  committeeId: "constitution",
  status: "completed",
  summaryOfficial: "נקבע בחוק (לצורך הבהרה) כי אפוטרופוס רשאי לפתוח או לנהל חשבון תשלום עבור האדם שהוא אפוטרופסו, וכן להשתמש בעבורו באמצעי תשלום, בשיקים ובהרשאות לחיוב, לרבות באמצעים מקוונים. עוד נקבע כי נותן שירותי תשלום שאליו פנה אפוטרופוס לשם קבלת שירותים אלו לא יסרב לבקשתו, ולא יתנה את מתן השירות בתנאים בלתי סבירים בנסיבות העניין רק בשל העובדה שמדובר בחשבון של אדם שמונה לו אפוטרופוס. כמו כן, הוחלו הוראות אלו גם על מיופה כוח, כך שיוכל לפעול באותו אופן לעניין הממנה.",
  lastUpdated: "2026-07-28",
  completedDate: "2026-01-14",
  initiators: [
    {
      kind: "mk",
      personId: 30875,
      name: "צגה מלקו",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-05-20",
          time: "14:30",
          sessionId: 2231663
        },
        {
          date: "2025-06-24",
          time: "09:00",
          sessionId: 2232603
        },
        {
          date: "2025-07-01",
          time: "12:50",
          sessionId: 2233414
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-12-30",
          time: "11:15",
          sessionId: 2238316
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
