// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2210981,
  syncedAt: "2026-08-12",
  officialName: "חוק המאבק בטרור (תיקון מס' 10), התשפ\"ד-2023",
  type: "governmental",
  committeeId: "foreign-defense",
  status: "completed",
  summaryOfficial: "החוק מתקן את פרק ב' לחוק המאבק בטרור, התשע\"ו-2016, כך ששר הביטחון יוכל להכריז באופן עצמאי וישיר גם על אדם זר כפעיל טרור, אף מבלי שגורם מוסמך מחוץ לישראל הכריז עליו קודם לכן ככזה. \nעוד נקבעה הרחבה להגדרה הקיימת כיום בחוק האמור של \"פעיל טרור\", כך שגם מי שנוטל חלק באופן ממשי במימון פעילות של ארגון טרור מוכרז או בהעמדת אמצעים לארגון כאמור, גם אם אינו חבר בו, יכנס לגדר ההגדרה \"פעיל טרור\". כן תוקנה הגדרת המונח \"נשק\" כך שההגדרה תכלול גם נשק שאינו תקין.",
  lastUpdated: "2024-01-15",
  completedDate: "2023-11-13",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-10-30",
          time: "10:45",
          sessionId: 2210974
        },
        {
          date: "2023-11-05",
          time: "15:00",
          sessionId: 2211095
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
