// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2210354,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק המרכז להנצחת מורשת הלוחם היהודי במלחמת העולם השנייה, התשפ\"ו-2026",
  type: "private",
  committeeId: "education",
  status: "agenda",
  lastUpdated: "2026-07-17",
  initiators: [
    {
      kind: "mk",
      personId: 30121,
      name: "עודד פורר",
      partyId: "yisrael-beiteinu",
      factionName: "ישראל ביתנו"
    },
    {
      kind: "mk",
      personId: 30831,
      name: "אלי דלל",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30722,
      name: "יבגני סובה",
      partyId: "yisrael-beiteinu",
      factionName: "ישראל ביתנו"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-03-04",
          time: "10:45",
          sessionId: 2215887
        },
        {
          date: "2024-09-03",
          time: "09:00",
          sessionId: 2221854
        },
        {
          date: "2025-01-06",
          time: "11:00",
          sessionId: 2224956
        },
        {
          date: "2025-02-10",
          time: "11:00",
          sessionId: 2228088
        },
        {
          date: "2025-02-24",
          time: "12:00",
          sessionId: 2228777
        },
        {
          date: "2025-10-21",
          time: "09:00",
          sessionId: 2235354
        },
        {
          date: "2026-01-12",
          time: "12:30",
          sessionId: 2238853
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2026-05-26",
          time: "10:30",
          sessionId: 2242408
        },
        {
          date: "2026-05-31",
          time: "13:00",
          sessionId: 2243656
        },
        {
          date: "2026-06-15",
          time: "11:00",
          sessionId: 2243719
        }
      ]
    },
    {
      stage: "secondThird",
      state: "inProgress",
      discussions: []
    }
  ]
};
