// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2210752,
  syncedAt: "2026-08-12",
  officialName: "חוק הארכת תקופות ודחיית מועדים (הוראת שעה – חרבות ברזל) (אישורים רגולטוריים, עיצומים כספיים ובדיקות מיתקני גז), התשפ\"ד-2023",
  type: "governmental",
  committeeId: "constitution",
  status: "completed",
  summaryOfficial: "נקבעו בחוק זה הסדרים לצורך הקלה על המשק והבטחת רציפות תפקודית תקינה של אספקת מצרכים ושירותים לציבור בשל מצב החירום. זאת, באמצעות הארכת אישורים רגולטוריים בשלושה חודשים (ובחלק מהמקרים - בארבעה חודשים), דחיית מועדים הקשורים לעיצומים כספיים בשלושה חודשים ודחיית מועד לביצוע בדיקה תקופתית של מתקן גז בשלושה חודשים. ראש הממשלה רשאי, בצו, באישור הממשלה להאריך את תקופת הדחייה של נתינת אישור רגולטורי ואת המועד לביצוע בדיקה תקופתית של מתקן גז אם נוכח כי מתקיימות נסיבות המצדיקות זאת עקב המצב הבטחוני המיוחד. שר המשפטים רשאי, בצו, באישור ממשלה להאריך את תקופת הדחייה של דחיית מועדים הקשורים לעיצומים כספיים אם נוכח כי מתקיימות נסיבות המצדיקות זאת עקב המצב הבטחוני המיוחד.",
  lastUpdated: "2024-02-07",
  completedDate: "2023-10-25",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-10-23",
          time: "11:00",
          sessionId: 2210740
        },
        {
          date: "2023-10-24",
          time: "09:30",
          sessionId: 2210769
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
