// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2210623,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק שמירת הניקיון (הוראת שעה), התשפ\"ג-2023 - החלק שנותר",
  type: "governmental",
  committeeId: "interior-environment",
  status: "agenda",
  lastUpdated: "2023-10-18",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-10-16",
          time: "11:15",
          sessionId: 2210579
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "inProgress",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
