// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2211247,
  syncedAt: "2026-08-12",
  officialName: "חוק הארכת תקופות ודחיית מועדים (הוראת שעה – חרבות ברזל) (תכנון ובנייה ומקרקעי ציבור), התשפ\"ד-2023",
  type: "governmental",
  committeeId: "interior-environment",
  status: "completed",
  summaryOfficial: "נקבע הסדר שעניינו הארכת תקופות ודחיית מועדים לביצוע פעולות בנושאי התכנון והבנייה. כך למשל נקבעה תקופת הקפאה גורפת בכל הארץ, ותקופת הקפאה ארוכה יותר ביישובים שפונו בשל המצב הביטחוני המיוחד, אשר במסגרתן, אם חלה תקופה שנקבעה לפי הוראות חוק מסוימות המצוינות בחוק זה, לא יבואו הימים שבתקופת ההקפאה במניין הימים של התקופה האמורה. כמו כן, ניתנה סמכות ליושב ראש מוסד תכנון להורות על הארכת תקופה המוגדרת בחוק או להורות על דיון בהתנגדות שהוגשה לאחר תום המועד להגשת התנגדות לפי כל דין, אם סבר שיש לכך הצדקה בשל המצב הביטחוני המיוחד. בנוסף, הוראות פקיעה של תכנית שחלה בתקופה של 5 חודשים מיום כ\"ב בתשרי התשפ\"ד (7 באוקטובר 2023), יידחה מועד פקיעת התכנית בשישה חודשים. עוד נקבע כי ועדה מקומית עצמאית שהסמכתה הסתיימה בתקופה שמיום י\"ד באב התשפ\"ג (1 באוגוסט 2023), תוארך הסמכתה לתקופה של שנה.\nנוסף על כן, נקבע הסדר בהוראת שעה למשך שנה, במסגרתו במידה וועדה מקומית לא החליטה בבקשה להיתר בתוך 90 ימים ממועד קליטתה, בהינתן תנאים מסוימים הבקשה תעבור לדיון בוועדת הערר, לה יהיו את כל הסמכויות הנתונות לוועדה המקומית לעניין זה.",
  lastUpdated: "2024-01-02",
  completedDate: "2023-11-15",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-11-06",
          time: "20:00",
          sessionId: 2211245
        },
        {
          date: "2023-11-09",
          time: "12:00",
          sessionId: 2211233
        },
        {
          date: "2023-11-14",
          time: "10:30",
          sessionId: 2211380
        },
        {
          date: "2023-11-15",
          time: "10:00",
          sessionId: 2211498
        },
        {
          date: "2023-11-15",
          time: "10:30",
          sessionId: 2211520
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
