// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2211015,
  syncedAt: "2026-08-12",
  officialName: "חוק נציב תלונות הציבור על שופטים (תיקון מס' 5 - הוראת שעה), התשפ\"ד-2023",
  type: "governmental",
  committeeId: "constitution",
  status: "completed",
  summaryOfficial: "נקבע בהוראת שעה לתקופה של חצי שנה, כי שר המשפטים ונשיא בית המשפט העליון, יחד, יהיו רשאים להאריך את תקופת כהונתו של נציב תלונות הציבור על שופטים בתקופה של חצי שנה בלבד.",
  lastUpdated: "2024-02-07",
  completedDate: "2023-11-06",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-11-06",
          time: "11:30",
          sessionId: 2211089
        },
        {
          date: "2023-11-06",
          time: "15:30",
          sessionId: 2211230
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
