// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2211471,
  syncedAt: "2026-08-12",
  officialName: "חוק הענקת אזרחות כבוד לחללי מערכות ישראל, התשפ\"ד-2023",
  type: "governmental",
  committeeId: "interior-environment",
  status: "completed",
  summaryOfficial: "נקבע כי שר הפנים, בהמלצת שר הביטחון, יעניק אזרחות כבוד של מדינת ישראל לחלל מערכות ישראל שבמועד פטירתו לא היה אזרח ישראלי. \nעוד נקבע כי במידה והורה, בן זוג, ילד או אח של חלל שהוענקה לו אזרחות כבוד יגיש בקשה לשר הפנים לבטלה, שר הפנים יעשה כן כך שיראוה כאילו לא ניתנה כלל.",
  lastUpdated: "2023-12-26",
  completedDate: "2023-11-15",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-11-13",
          time: "15:30",
          sessionId: 2211477
        },
        {
          date: "2023-11-15",
          time: "09:30",
          sessionId: 2211516
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
