// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2211939,
  syncedAt: "2026-08-12",
  officialName: "חוק לתיקון דיני הראיות (הגנת ילדים) (תיקון מס' 19 - הוראת שעה - חרבות ברזל), התשפ\"ד-2023",
  type: "governmental",
  committeeId: "constitution",
  status: "completed",
  summaryOfficial: "חוקר ילדים אחראי על חקירת ילדים וגביית העדות בעבירות המפורטות בתוספת בחוק. בחוק זה, הורחבה סמכותו של חוקר ילדים כאמור לעניין עבירות המתה, עבירות התעללות ועבירות חטיפה בקשר למעשה טרור או פגיעת איבה שבוצעו בתקופה מיום ה-7 באוקטובר 2023 עד תום שנה מיום תחילתו של החוק זאת בתנאי שהילד אינו חשוד ומתחת לגיל 14. שר המשפטים רשאי להאריך את התקופה בהסכמת שר הרווחה והביטחון חברתי, ובאישור ועדת החוקה, חוק ומשפט. כמו כן, הורחבה סמכותו של חוקר ילדים אף לעניין כל עבירה שבוצעה בקשר למעשה טרור או פגיעת איבה בתקופה מיום ה-7 באוקטובר 2023 עד יום 9 באוקטובר 2023, זאת בתנאי שהילד אינו חשוד ומתחת לגיל 15. במידה והילד נפגע עבירת החטיפה, חוקר הילדים יוכל לחקור אותו גם אם המעשה או פגיעת האיבה התרחשה לאחר התקופה המנויה. לבסוף, נקבע שבטרם קבלת ההחלטה על חקירת ילדים בקשר למעשה הטרור או פגיעת האיבה שבוצעו, יתייעץ הקצין הממונה על חקירת העבירה במשטרה עם חוקר ילדים.",
  lastUpdated: "2024-02-05",
  completedDate: "2023-12-04",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-11-29",
          time: "10:45",
          sessionId: 2211950
        },
        {
          date: "2023-12-03",
          time: "13:00",
          sessionId: 2212026
        },
        {
          date: "2023-12-04",
          time: "10:30",
          sessionId: 2212128
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
