// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2211439,
  syncedAt: "2026-08-12",
  officialName: "חוק מניעת מימון לייצוג משפטי בידי מדינת ישראל (חשוד, נאשם או מורשע בעבירת ביטחון - חרבות ברזל), התשפ\"ה–2024",
  type: "private",
  committeeId: "constitution",
  status: "completed",
  summaryOfficial: "החוק קובע ששכרם של סניגורים שימונו או שמונו החל מה-7 באוקטובר 2023 על ידי בית המשפט למי שחשוד, נאשם או הורשע בעבירת ביטחון הקשורה לאירועי ה-7 באוקטובר או במסגרת מלחמת חרבות ברזל, יקוזז מהכספים אותם מעבירה ממשלת ישראל לרשות הפלסטינית.",
  lastUpdated: "2025-09-28",
  completedDate: "2024-12-11",
  initiators: [
    {
      kind: "mk",
      personId: 30812,
      name: "שמחה רוטמן",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    },
    {
      kind: "mk",
      personId: 30868,
      name: "יונתן מישרקי",
      partyId: "shas",
      factionName: "התאחדות הספרדים שומרי תורה תנועתו של מרן הרב עובדיה יוסף זצ\"ל"
    },
    {
      kind: "mk",
      personId: 30859,
      name: "צביקה פוגל",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-03-04",
          time: "09:00",
          sessionId: 2215249
        },
        {
          date: "2024-07-15",
          time: "09:00",
          sessionId: 2220613
        },
        {
          date: "2024-07-16",
          time: "11:30",
          sessionId: 2220846
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-09-08",
          time: "09:00",
          sessionId: 2221900
        },
        {
          date: "2024-11-04",
          time: "09:00",
          sessionId: 2222935
        },
        {
          date: "2024-11-05",
          time: "13:00",
          sessionId: 2223205
        },
        {
          date: "2024-11-12",
          time: "11:50",
          sessionId: 2223366
        },
        {
          date: "2024-11-12",
          time: "11:00",
          sessionId: 2223614
        },
        {
          date: "2024-11-19",
          time: "11:00",
          sessionId: 2223795
        },
        {
          date: "2024-11-20",
          time: "08:45",
          sessionId: 2224123
        },
        {
          date: "2024-11-20",
          time: "10:20",
          sessionId: 2224133
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
