// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2211196,
  syncedAt: "2026-08-12",
  officialName: "חוק הגנה על עובדים בשעת חירום (תיקון מס' 5 והוראת שעה – חרבות ברזל), התשפ\"ד-2023",
  type: "governmental",
  committeeId: "labor-welfare",
  status: "completed",
  summaryOfficial: "חוק זה קובע כהוראת שעה לשלושה חודשים (עם אפשרות הארכה של כולה או חלקה, עד 12 חודשים), הגנה מפני פיטורים לעובד שנעדר מעבודתו או לא ביצע את עבודתו, מאחת הסיבות המפורטות: \n(א) העובד שהתפנה מאחד הישובים שמנויים בתוספת; \n(ב) העובד הוא הורה או בן זוג של נעדר או חטוף, או שהוא ילדו או אחיו של החטוף או קרוב משפחה אחר של חטוף או נעדר והצהיר שההיעדרות או אי ביצוע העבודה נגרמו עקב כך.\n(ג) העובד שנעדר משום שיש עמו ילד עד גיל 14 ובן זוגו או הורהו האחר של הילד הוא חייל או שהוא בשירות עבודה או בשירות אחר שמנוי בסעיף 11 לחוק. \n(4) העובד נעדר מעבודתו משום שהוא חטוף או נעדר. \n(5) העובד נעדר בשל סגירת מוסד החינוך של ילדו  - גם  אם הסגירה היא עקב הודעה מהרשות המקומית או ממוסד החינוך עצמו בלבד.\n\nכמו כן החוק קובע כהוראת שעה לשנתיים, שניתן להאריכה בשנה נוספת, שמעסיק של עובד חטוף או נעדר יהיה חייב להמשיך להפריש עבורו בתקופה שהוא חטוף או נעדר את מלוא ההפרשות לקופת גמל לקצבה לשם שמירת רצף הזכויות והמוסד לביטוח לאומי ישפה את המעסיק על כך. המוסד לביטוח לאומי ישלם את ההפקדות לקופת גמל לקצבה עבור חטוף או נעדר שהוא עצמאי, וכן עבור חטוף או נעדר שעבודתו הסתיימה בחמשת החודשים שקדמו לחטיפה או ההיעדרות וגם למי שתסתיים העסקתו לאחר מכן, בתקופה שהוא חטוף או נעדר.\n\nהחוק קובע כהוראה קבועה כי ההגנה מפני פיטורים הניתנת בשל הצורך בהשגחה על ילד קיימת גם לגבי ילד במשפחת אומנה וזאת בכפוף לאישור של מנחה האומנה.",
  lastUpdated: "2024-01-11",
  completedDate: "2023-11-27",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-11-06",
          time: "11:00",
          sessionId: 2211186
        },
        {
          date: "2023-11-13",
          time: "11:00",
          sessionId: 2211298
        },
        {
          date: "2023-11-23",
          time: "13:15",
          sessionId: 2211681
        },
        {
          date: "2023-11-27",
          time: "15:45",
          sessionId: 2211877
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
