// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2211293,
  syncedAt: "2026-08-12",
  officialName: "חוק הביטוח הלאומי (תיקון מס' 238 - הוראת שעה – חרבות ברזל) (תגמולים למשרתים במילואים), התשפ\"ד-2023",
  type: "governmental",
  committeeId: "labor-welfare",
  status: "completed",
  summaryOfficial: "חוק זה קובע כהוראת שעה לגבי מי ששירת במילואים בתקופה שמיום 7.10.2023 ועד יום 31.12.2023, ששיעור התגמול המזערי בעד יום מילואים עבורו יעלה לסכום של 300.61 שקלים חדשים במקום 215.17 שקלים חדשים שהיו ניתנים עד היום. בנוסף, החוק מאפשר לשר העבודה בהסכמת שר הביטחון ושר האוצר ובאישור ועדת העבודה והרווחה של הכנסת להאריך בצו את התקופה האמורה אם הדבר יידרש בשל הימשכות מלחמת חרבות ברזל.",
  lastUpdated: "2024-01-11",
  completedDate: "2023-11-08",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-11-08",
          time: "10:30",
          sessionId: 2211290
        },
        {
          date: "2023-11-09",
          time: "11:00",
          sessionId: 2211302
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
