// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2211195,
  syncedAt: "2026-08-12",
  officialName: "חוק חינוך מיוחד (הוראת שעה – חרבות ברזל) (הארכת זכאות), התשפ\"ד-2023 ",
  type: "governmental",
  committeeId: "education",
  status: "completed",
  summaryOfficial: "החוק קובע בהוראת שעה כי זכאות לשירותי חינוך מיוחדים של תלמיד שנקבעה על ידי ועדת זכאות ואפיון או יל ידי ועדת השגה בשנות הלימוד תשפ\"א-תשפ\"ג, תוארך בשנה נוספת בלא צורך בקיום דיון חוזר בוועדה; זאת מבלי לגרוע מהסמכות לקיים דיון חוזר בוועדה לגבי התלמיד אם הוגשה בקשה לעשות כן, לרבות ע\"י ההורים. עוד נקבע סייג לפיו יתקיים דיון חוזר בעניינם של תלמידים שנקבעה להם זכאות בשנים התשפ\"ב-התשפ\"ג, אם תום תקופת הזכאות המקורית הוא לקראת מעבר בין שלבי הגיל (מגן חובה לבי\"ס יסודי, מיסודי לחטיבת הביניים או מחטיבת הביניים לחטיבה העליונה). החוק מחייב את משרד החינוך, ככל הניתן, להודיע להורים בתוך חודש מתחילתו על תקופת הארכת הזכאות, הזכות לבקש דיון חוזר ודרך הגשת הבקשה לדיון חוזר.",
  lastUpdated: "2023-11-16",
  completedDate: "2023-11-13",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-11-06",
          time: "11:00",
          sessionId: 2211186
        },
        {
          date: "2023-11-13",
          time: "09:00",
          sessionId: 2211263
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
