// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2211055,
  syncedAt: "2026-08-12",
  officialName: "חוק התקשורת (בזק ושידורים) (תיקון מס' 81), התשפ\"ה–2025",
  type: "private",
  committeeId: "economy",
  status: "completed",
  summaryOfficial: "התיקון קובע כי ספק שירות טלפוניה רשאי להעביר למוקד חירום לעזרה ראשונה נפשית או למוקד לסיוע לנפגעות ונפגעי תקיפה מינית, לבקשת המוקד האמור, את שלוש הספרות האחרונות של מספרי הטלפון החסויים שמהם מבוצעות שיחות לאותו מוקד. מוקדי החירום שיהיו רשאים לקבל את המידע האמור הם מוקדי החירום שנקבעו בתקנות שהתקין שר התקשורת, בהסכמת שר הרווחה והביטחון החברתי. עוד נקבע כי המידע שנמסר כאמור יאובטח לפי חוק הגנת הפרטיות, התשמ\"א-1981, וישמש את מוקד החירום רק לצורך פנייה למשטרת ישראל במקרה של חשש לשלום הפונה למוקד. לאחר תום הצורך במידע האמור, ולא יאוחר מ-24 שעות לאחר קבלת המידע, המידע יימחק על ידי מי שקיבל אותו. בנוסף, התיקון קובע כי רשימת מוקדי החירום כאמור, וכל שינוי בה, יפורסמו באתר האינטרנט של משרד התקשורת.",
  lastUpdated: "2025-04-07",
  completedDate: "2025-03-31",
  initiators: [
    {
      kind: "mk",
      personId: 30106,
      name: "נעמה לזימי",
      partyId: "labor",
      factionName: "העבודה"
    },
    {
      kind: "mk",
      personId: 30706,
      name: "קטי קטרין שטרית",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30782,
      name: "טטיאנה מזרסקי",
      partyId: "yesh-atid",
      factionName: "יש עתיד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-09-11",
          time: "11:30",
          sessionId: 2221711
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-03-18",
          time: "10:00",
          sessionId: 2229132
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
