// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2211470,
  syncedAt: "2026-08-12",
  officialName: "חוק הארכת תקופות ודחיית מועדים (הוראת שעה – חרבות ברזל) (הליכי מס ומענקי סיוע), התשפ\"ד-2023 ",
  type: "governmental",
  committeeId: "finance",
  status: "completed",
  summaryOfficial: "מוצע להאריך תוקפן של תקופות קצובות בזמן שנקבעו בהליכי מס שונים. לפי המוצע, אם מועד תחילת ביצוע הפעולה חל לפני תום התקופה הקובעת (תקופה של שלושה חודשים שתחילתה ביום 7 באוקטובר 2023) ומועד סיום ביצוע הפעולה, חל במהלך התקופה הקובעת או בחודשיים שאחריה, תקופה זו לא תבוא במניין הימים לביצוע הפעולה. כמו כן, מוצע להוסיף ימים למניין התקופות בעניין מכירת דירת מגורים מזכה לפי חוק מיסוי מקרקעין (שבח ורכישה), התשכ\"ג–1963.",
  lastUpdated: "2025-01-05",
  completedDate: "2023-11-27",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-11-13",
          time: "14:20",
          sessionId: 2211410
        },
        {
          date: "2023-11-20",
          time: "10:00",
          sessionId: 2211583
        },
        {
          date: "2023-11-21",
          time: "12:40",
          sessionId: 2211586
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
