// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2212298,
  syncedAt: "2026-08-12",
  officialName: "חוק כליאתם של לוחמים בלתי חוקיים (תיקון מס' 4 והוראת שעה – חרבות ברזל), התשפ\"ד-2023",
  type: "governmental",
  committeeId: "foreign-defense",
  status: "completed",
  summaryOfficial: "חוק כליאתם של לוחמים בלתי חוקיים קובע כי במקרה בו הודיעה הממשלה לוועדת החוץ והביטחון של הכנסת על החלטה לפתוח במלחמה או על פעולות צבאיות משמעותיות לפי חוק יסוד: הממשלה, רשאית היא להכריז כי אלו מצריכות תחולה של הוראות שונות בחוק. בחוק זה נקבעו הוראות אשר נועדו להתאים לתיקונים שנעשו בחוק יסוד: הממשלה, כך שתהיה התייחסות להכרזה על פעולות צבאיות משמעותיות העלולות להוביל בהסתברות קרובה לוודאי למלחמה. עוד נקבעה, בהוראת שעה למשך ארבעה חודשים, הארכה למשך תקופת הכליאה הזמנית של לוחמים בלתי חוקיים, מועד ההבאה בפני שופט והתקופות בהן ניתן למנוע פגישה עם עורך דין. בנוסף, נקבע כי במקרים של שינויים בתחולת החוק תרד דרגת הגורם הצבאי המוסמך לאשר פעולות שונות לפי החוק, וכן יתאפשר קיום דיונים לפי החוק בדרך של היוועדות חזותית.",
  lastUpdated: "2024-01-15",
  completedDate: "2023-12-18",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2023-12-18",
          time: "11:00",
          sessionId: 2212367
        },
        {
          date: "2023-12-18",
          time: "15:45",
          sessionId: 2212481
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
