// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2212439,
  syncedAt: "2026-08-12",
  officialName: "חוק הגישה לתוכן דיגיטלי לאחר פטירתו של אדם, התשפ\"ד–2024",
  type: "private",
  committeeId: "constitution",
  status: "completed",
  summaryOfficial: "החוק קובע כי ספקי שירות תוכן דיגיטלי יקבעו ויפרסמו כללים בנוגע לאופן הטיפול והגישה לתוכן אישי של משתמש לאחר פטירתו. נקבע כי אותם כללים יפורסמו באופן נגיש וברור בשפה שבה ניתן השירות. במסגרת אותם כללים, על הספק לקבוע הוראות שיאפשרו למשתמש לבחור להעניק לאדם אחר גישה לתוכן האישי שלו או לחלק ממנו, או לא להעניק גישה לאדם אחר כלל. עם זאת, הספק רשאי לקבוע כי לחלק מהתוכן האמור לא תינתן גישה. בנוסף, נקבע כי בנוגע לתקשורת בין אישית, בין אדם לאדם, לא תחול על הספק החובה לקבוע הוראות כאמור. כמו כן, נקבע כי שר המשפטים יהיה מוסמך, באישור ועדת החוקה, להוסיף בתוספת שירותים שעליהם לא תחול החובה לקביעת הוראות. נקבע כי על הספק לעדכן את המשתמשים על הכללים שקבע ועל בחירת המשתמש מעת לעת, וכי הוראות אלו יחולו גם על ספק שירות תוכן דיגיטלי שאינו מישראל ככל שהוא מציע את שירותיו למשתמשים ישראלים ומכוון את שירותיו למשתמשים כאמור.",
  lastUpdated: "2025-02-23",
  completedDate: "2024-07-22",
  initiators: [
    {
      kind: "mk",
      personId: 30873,
      name: "ארז מלול",
      partyId: "shas",
      factionName: "התאחדות הספרדים שומרי תורה תנועתו של מרן הרב עובדיה יוסף זצ\"ל"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-03-28",
          time: "09:00",
          sessionId: 2216135
        },
        {
          date: "2024-05-21",
          time: "09:00",
          sessionId: 2217583
        },
        {
          date: "2024-05-27",
          time: "11:00",
          sessionId: 2218298
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-07-08",
          time: "12:45",
          sessionId: 2219401
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
