// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2212681,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק העבירות המינהליות (תיקון - הפחתת תוספת הפיגור על אי-תשלום קנס), התשפ\"ד-2024 פ/4166/25",
  type: "private",
  committeeId: "constitution",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2024-02-21",
  initiators: [
    {
      kind: "mk",
      personId: 560,
      name: "אחמד טיבי",
      partyId: "hadash-taal",
      factionName: "חד\"ש-תע\"ל"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2024-02-08",
          time: "12:00",
          sessionId: 2214794
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
