// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2212280,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק סיוע לסטודנטים המשרתים במילואים (הוראת שעה - חרבות ברזל), התשפ\"ד-2023",
  type: "private",
  committeeId: "education",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2024-01-31",
  initiators: [
    {
      kind: "mk",
      personId: 30682,
      name: "מיכאל מרדכי ביטון",
      partyId: "national-unity",
      factionName: "המחנה הממלכתי"
    },
    {
      kind: "mk",
      personId: 30770,
      name: "יוסף טייב",
      partyId: "shas",
      factionName: "התאחדות הספרדים שומרי תורה תנועתו של מרן הרב עובדיה יוסף זצ\"ל"
    },
    {
      kind: "mk",
      personId: 30701,
      name: "אופיר כץ",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2024-01-30",
          time: "09:30",
          sessionId: 2214106
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
