// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2212125,
  syncedAt: "2026-08-12",
  officialName: "חוק התוכנית הכלכלית (תיקוני חקיקה ליישום המדיניות הכלכלית לשנות התקציב 2023 ו-2024) (תיקון), התשפ\"ד-2024",
  type: "governmental",
  committeeId: "economy",
  status: "completed",
  summaryOfficial: "במסגרת חוק ההתייעלות הכלכלית (תיקוני חקיקה להשגת יעדי התקציב לשנות התקציב 2023 ו-2024), התשפ\"ג–2023 , בוצעו מספר תיקונים בחוק הבנקאות (שירות ללקוח), התשמ\"א-1981, שעסקו בהגברת השקיפות ללקוחות הבנקים. אחד מהתיקונים כאמור היה תיקון סעיף 5א לחוק הבנקאות, בו נקבע כי בתחילת כל חודש קלנדרי ישלחו הבנקים לכל לקוחותיהם, באמצעי המאפשר תקשורת מיידית ונגישה, ככל האפשר, הודעה שבה יפרטו את הסכומים הכוללים של העמלות ושל הריביות שגבה הבנק מהלקוח בחודש שקדם למועד שליחת ההודעה. עוד נקבע כי מועד תחילתו של התיקון לעניין עמלות יהיה ב-1 בינואר 2024, ולעניין ריביות וכן עמלות וריביות שנגבו בעבור הלוואה לדיור, ב-2 ביוני 2024. \nנוכח מלחמת \"חרבות ברזל\" שפרצה ב-7 באוקטובר 2023, הוכרז מצב מיוחד בעורף שהוחל על כל שטחי המדינה והחל גיוס מילואים נרחב. עובדים רבים בכל מערכות המשק לרבות המערכת הבנקאית גויסו, ועיקר המשאבים הופנו לטיפול בנפגעים ובמקרים הדחופים. המציאות החדשה השפיעה על היערכותם של הבנקים ליישום הוראות התיקון במועד שנקבע.  \nהחוק נועד לאפשר לבנקים ארכה להיערכות ליישום משלוח ההודעות ללקוחותיהם. בהתאם לכך, החוק דוחה בחודשיים, עד ליום ה-1 במרץ 2024, את מועד תחילתה של ההוראה המחייבת תאגיד בנקאי לשלוח ללקוחותיו, בתחילת כל חודש קלנדרי, הודעה לעניין עמלות כאמור. כמו כן, החוק חל רטרואקטיבית מה-1 בינואר 2024 שהוא מועד תחילתה המקורי של ההוראה כאמור.",
  lastUpdated: "2024-08-12",
  completedDate: "2024-02-26",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-01-01",
          time: "10:30",
          sessionId: 2212846
        },
        {
          date: "2024-01-15",
          time: "09:30",
          sessionId: 2213690
        },
        {
          date: "2024-02-19",
          time: "13:15",
          sessionId: 2215124
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
