// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2213308,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק הגנת השכר (תיקון מס' 32) (הגברת האכיפה – ניכויים משכר עבודה), התשפ\"ה–2025",
  type: "private",
  committeeId: "labor-welfare",
  status: "agenda",
  lastUpdated: "2025-12-29",
  initiators: [
    {
      kind: "mk",
      personId: 30808,
      name: "אפרת רייטן מרום",
      partyId: "labor",
      factionName: "העבודה"
    },
    {
      kind: "mk",
      personId: 30758,
      name: "אימאן ח'טיב יאסין",
      partyId: "raam",
      factionName: "רע\"ם"
    },
    {
      kind: "mk",
      personId: 30713,
      name: "מנסור עבאס",
      partyId: "raam",
      factionName: "רע\"ם"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-04-01",
          time: "11:00",
          sessionId: 2217156
        },
        {
          date: "2024-07-08",
          time: "11:00",
          sessionId: 2220298
        },
        {
          date: "2024-11-18",
          time: "09:30",
          sessionId: 2223857
        },
        {
          date: "2025-02-04",
          time: "13:00",
          sessionId: 2227759
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2025-12-22",
          time: "10:30",
          sessionId: 2238055
        },
        {
          date: "2025-12-29",
          time: "12:15",
          sessionId: 2238301
        }
      ]
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
