// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2214645,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק להפסקת יחסי מדינת ישראל עם סוכנות הסעד והתעסוקה של האו\"ם לפליטי פלסטין במזרח הקרוב (אונר\"א) והכרזה עליה כארגון טרור, התשפ\"ד-2024",
  type: "private",
  committeeId: "foreign-defense",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2024-09-29",
  initiators: [
    {
      kind: "mk",
      personId: 23560,
      name: "יוליה מלינובסקי",
      partyId: "yisrael-beiteinu",
      factionName: "ישראל ביתנו"
    },
    {
      kind: "mk",
      personId: 427,
      name: "אביגדור ליברמן",
      partyId: "yisrael-beiteinu",
      factionName: "ישראל ביתנו"
    },
    {
      kind: "mk",
      personId: 30121,
      name: "עודד פורר",
      partyId: "yisrael-beiteinu",
      factionName: "ישראל ביתנו"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-06-04",
          time: "12:30",
          sessionId: 2218227
        },
        {
          date: "2024-07-02",
          time: "09:00",
          sessionId: 2219925
        },
        {
          date: "2024-07-09",
          time: "10:30",
          sessionId: 2220252
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2024-09-03",
          time: "10:00",
          sessionId: 2221880
        },
        {
          date: "2024-09-24",
          time: "11:00",
          sessionId: 2222257
        },
        {
          date: "2024-09-29",
          time: "20:30",
          sessionId: 2222408
        }
      ]
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
