// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2214856,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק שירות המדינה (מינויים) (תיקון - עדיפות למשרת מילואים פעיל), התשפ\"ד-2024",
  type: "private",
  committeeId: "constitution",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2024-10-28",
  initiators: [
    {
      kind: "mk",
      personId: 30863,
      name: "שרון ניר",
      partyId: "yisrael-beiteinu",
      factionName: "ישראל ביתנו"
    },
    {
      kind: "mk",
      personId: 427,
      name: "אביגדור ליברמן",
      partyId: "yisrael-beiteinu",
      factionName: "ישראל ביתנו"
    },
    {
      kind: "mk",
      personId: 30121,
      name: "עודד פורר",
      partyId: "yisrael-beiteinu",
      factionName: "ישראל ביתנו"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2024-08-07",
          time: "09:30",
          sessionId: 2221363
        },
        {
          date: "2024-09-08",
          time: "10:20",
          sessionId: 2221912
        },
        {
          date: "2024-10-28",
          time: "09:00",
          sessionId: 2222504
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
