// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2214414,
  syncedAt: "2026-08-12",
  officialName: "חוק הפחתת הגירעון והגבלת ההוצאה התקציבית (תיקון מס' 25), התשפ\"ד-2024",
  type: "governmental",
  committeeId: "finance",
  status: "completed",
  summaryOfficial: "מוצע להעלות את תקרת הגירעון לשנת 2024 כך ששיעור הגירעון הכולל לא יעלה על 6.6% מהתוצר הלאומי הגולמי (במקום שיעור של 2.25%), וכן להגדיל את ההוצאה הממשלתית המותרת בשנת 2024 בשיעור של 11.35% מסך ההוצאה הממשלתית לשנת 2023 לצורך המשך מימון הצרכים הצבאיים ובשיעור של 3.2% לצורך המשך מימון הצרכים האזרחיים הנובעים במישרין מהלחימה.",
  lastUpdated: "2024-10-06",
  completedDate: "2024-03-12",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-02-12",
          time: "10:00",
          sessionId: 2214969
        },
        {
          date: "2024-02-20",
          time: "14:20",
          sessionId: 2215233
        },
        {
          date: "2024-02-26",
          time: "11:20",
          sessionId: 2215553
        },
        {
          date: "2024-02-28",
          time: "09:30",
          sessionId: 2215703
        },
        {
          date: "2024-03-11",
          time: "10:00",
          sessionId: 2216152
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
