// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2215702,
  syncedAt: "2026-08-12",
  officialName: "חוק העונשין (תיקון מס' 151), התשפ\"ה–2024",
  type: "private",
  committeeId: "constitution",
  status: "completed",
  summaryOfficial: "החוק קובע כי עבירת תקיפת סוהר, שהייתה מוסדרת כחלק מעבירת 'תקיפת עובד ציבור' תקבל התייחסות פרטנית בחוק העונשין, וכי הסימן בחוק העונשין שעניינו בתקיפה או הפרעה לשוטר, יחול בשינויים מסוימים גם על תקיפה או הפרעה לסוהר.",
  lastUpdated: "2025-09-03",
  completedDate: "2024-11-27",
  initiators: [
    {
      kind: "mk",
      personId: 30859,
      name: "צביקה פוגל",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-06-04",
          time: "12:30",
          sessionId: 2218227
        },
        {
          date: "2024-06-17",
          time: "15:45",
          sessionId: 2219353
        },
        {
          date: "2024-07-01",
          time: "11:30",
          sessionId: 2219952
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-09-23",
          time: "11:30",
          sessionId: 2222230
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
