// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2215127,
  syncedAt: "2026-08-12",
  officialName: "חוק התקנים (תיקון מס' 18), התשפ\"ד–2024",
  type: "governmental",
  committeeId: "economy",
  status: "completed",
  summaryOfficial: "כחלק מצעדי הממשלה לביצוע התאמות לשם התכנסות למסגרות הפיסקאליות לשנת 2024 ואילך, אשר נועדו לסייע למשק להתמודד עם ההוצאות הנגרמות ממלחמת \"חרבות ברזל\", נקבע כי מכון התקנים יעביר לאוצר המדינה סכום חד פעמי של 105 מיליון שקלים חדשים בתוך שישה חודשים מיום תחילתו של החוק. מקור הכספים יהיו מתוך עודפי מכון התקנים שהם סכומים הכלולים בהון העצמי של המכון ומקורם ברווח הנקי שלו, כפי שנקבע לפי כללי חשבונאות מקובלים, כמפורט בדוחות הכספיים האחרונים של המכון שפורסמו לפני מועד העברת הסכום.",
  lastUpdated: "2024-04-08",
  completedDate: "2024-03-04",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-02-19",
          time: "10:30",
          sessionId: 2215148
        },
        {
          date: "2024-02-26",
          time: "09:00",
          sessionId: 2215350
        },
        {
          date: "2024-02-26",
          time: "13:20",
          sessionId: 2215690
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
