// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2216841,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק האקלים, התשפ\"ד-2024",
  type: "governmental",
  committeeId: "interior-environment",
  status: "agenda",
  lastUpdated: "2024-11-25",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2024-06-04",
          time: "10:00",
          sessionId: 2217795
        },
        {
          date: "2024-07-02",
          time: "13:45",
          sessionId: 2219494
        },
        {
          date: "2024-09-22",
          time: "12:30",
          sessionId: 2221850
        },
        {
          date: "2024-09-25",
          time: "13:30",
          sessionId: 2221685
        },
        {
          date: "2024-10-13",
          time: "11:00",
          sessionId: 2222539
        },
        {
          date: "2024-10-29",
          time: "12:30",
          sessionId: 2222547
        },
        {
          date: "2024-11-03",
          time: "13:00",
          sessionId: 2222930
        },
        {
          date: "2024-11-17",
          time: "11:30",
          sessionId: 2223469
        },
        {
          date: "2024-11-19",
          time: "12:30",
          sessionId: 2223902
        },
        {
          date: "2024-11-21",
          time: "12:00",
          sessionId: 2224090
        },
        {
          date: "2024-12-03",
          time: "11:00",
          sessionId: 2224262
        },
        {
          date: "2024-12-03",
          time: "17:25",
          sessionId: 2224888
        }
      ]
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
