// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2216026,
  syncedAt: "2026-08-12",
  officialName: "חוק לתיקון פקודת מס הכנסה (מס' 272), התשפ\"ד–2024",
  type: "governmental",
  committeeId: "finance",
  status: "completed",
  summaryOfficial: "החוק נועד לתת מענה להמלצות הפורום העולמי לשקיפות וחילופי מידע למטרות מס הפועל תחת ה-OECD , בנוגע למידע על בעלי שליטה סופיים בתאגידים ולעולים חדשים ותושבים חוזרים ותיקים.\nהחוק מחייב דיווח על בעלי שליטה ותושבותם במסגרת דיווחי נאמנות ובדו\"ח השנתי. כמו כן, מבטל את הפטור מדיווח על הכנסות עולים חדשים ותושבים חוזרים ותיקים, אך אינו משנה את הפטור ממס הקבוע בסעיף 14 לפקודה לתקופה של עשר שנים.\nהדיווחים יתאפשרו בשפת המקור ויונגשו באמצעות תרגום טפסים. בנוסף, רשות המסים תוכל למסור מידע מזהה למוסדות פיננסיים לצורך יישום הסכמים בין-לאומיים בלבד, ולא תעשה בו שימוש לצרכים אחרים.",
  lastUpdated: "2025-08-07",
  completedDate: "2024-04-02",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-03-26",
          time: "10:00",
          sessionId: 2216737
        },
        {
          date: "2024-04-01",
          time: "12:00",
          sessionId: 2217048
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
