// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2216582,
  syncedAt: "2026-08-12",
  officialName: "חוק הכנסת (תיקון מס' 52), התשפ\"ד–2024",
  type: "committee",
  committeeId: "knesset-committee",
  status: "completed",
  summaryOfficial: "תיקון מס' 52 לחוק הכנסת מסדיר את הליך הערעור על החלטה של ועדת הכנסת שלפיה חבר הכנסת פרש מסיעתו. לפי התיקון, חבר הכנסת שהוגדר כפורש וסיעתו יהיו רשאים לערער לבית המשפט העליון (ולא המחוזי כקבוע היום). כמו כן נקצבו זמנים להליך: הערעור יוגש בתוך 14 ימים מיום ההחלטה, ופסק הדין יינתן בהקדם האפשרי ולא יאוחר מ-30 ימים מיום הגשת הערעור.",
  lastUpdated: "2024-07-07",
  completedDate: "2024-07-03",
  initiators: [],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-04-08",
          time: "11:30",
          sessionId: 2217373
        },
        {
          date: "2024-06-04",
          time: "12:30",
          sessionId: 2218227
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-06-25",
          time: "11:00",
          sessionId: 2219576
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
