// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2216711,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק תגמולים ליתום משני הוריו שאחד מהם נספה במלחמת חרבות ברזל (תיקוני חקיקה), התשפ\"ד-2024",
  type: "private",
  committeeId: "labor-welfare",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2026-01-27",
  initiators: [
    {
      kind: "mk",
      personId: 30601,
      name: "ינון אזולאי",
      partyId: "shas",
      factionName: "התאחדות הספרדים שומרי תורה תנועתו של מרן הרב עובדיה יוסף זצ\"ל"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2025-09-16",
          time: "10:30",
          sessionId: 2233449
        },
        {
          date: "2025-10-21",
          time: "10:00",
          sessionId: 2235606
        },
        {
          date: "2025-10-27",
          time: "09:00",
          sessionId: 2235490
        },
        {
          date: "2025-10-29",
          time: "09:00",
          sessionId: 2235496
        },
        {
          date: "2025-11-04",
          time: "11:15",
          sessionId: 2236137
        },
        {
          date: "2025-11-18",
          time: "11:00",
          sessionId: 2236707
        },
        {
          date: "2025-11-30",
          time: "10:00",
          sessionId: 2237033
        },
        {
          date: "2026-01-13",
          time: "10:00",
          sessionId: 2232978
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
