// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2217086,
  syncedAt: "2026-08-12",
  officialName: "חוק העונשין (תיקון מס' 150), התשפ\"ה-2024",
  type: "private",
  committeeId: "constitution",
  status: "completed",
  summaryOfficial: "התיקון לחוק קובע כי עבירת השוטטות, שהעונש הקבוע בצידה היה שישה חודשי מאסר, אשר הופיעה כאחת מההתנהגויות שנחשבות כעבירה של \"התנהגות פסולה במקום ציבורי\", תימחק מחוק העונשין, התשל\"ז–1977.",
  lastUpdated: "2025-04-27",
  completedDate: "2024-11-19",
  initiators: [
    {
      kind: "mk",
      personId: 30852,
      name: "משה סולומון",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-11-11",
          time: "09:00",
          sessionId: 2223368
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
