// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2217506,
  syncedAt: "2026-08-12",
  officialName: "חוק בתי קברות צבאיים (תיקון מס' 5) (תיקון), התשפ\"ו–2026",
  type: "private",
  committeeId: "national-security",
  status: "completed",
  summaryOfficial: "חוק בתי קברות צבאיים, התש\"י–1950, מסדיר את זכאותם של חללי צה\"ל וכוחות הביטחון, ובהם שוטרים, סוהרים ועובדי שירות הביטחון הכללי והמוסד, להיקבר בבית קברות צבאי. במסגרת תיקון מס' 5 לחוק, שאושר בשנת 2024, הורחבה רשימת הזכאים כך שנוספו אליה גם כבאים שנהרגו בעת שירותם ועקב שירותם. כעת, במסגרת תיקון נוסף, הוחלה הרחבת הזכאות הזו למפרע. נקבע כי כבאי שנהרג בעת שירותו ועקב שירותו החל מיום כ\"ו באב התשפ\"ג (13 באוגוסט 2023) או לאחריו, יהיה זכאי גם הוא להיקבר בבית קברות צבאי. מועד זה נבחר במטרה להחיל את זכאות הקבורה בבית קברות צבאי גם על הכבאים שקיפחו את חייהם בפעולת החילוץ ב\"אסון הבור\" בדיר אל־אסד, שאירע בתאריך זה.",
  lastUpdated: "2026-04-16",
  completedDate: "2025-12-31",
  initiators: [
    {
      kind: "mk",
      personId: 30859,
      name: "צביקה פוגל",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    },
    {
      kind: "mk",
      personId: 30102,
      name: "מירב בן ארי",
      partyId: "yesh-atid",
      factionName: "יש עתיד"
    },
    {
      kind: "mk",
      personId: 30876,
      name: "אושר שקלים",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-07-08",
          time: "12:00",
          sessionId: 2233659
        },
        {
          date: "2025-07-20",
          time: "13:00",
          sessionId: 2232153
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-12-14",
          time: "12:35",
          sessionId: 2237752
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
