// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2217192,
  syncedAt: "2026-08-12",
  officialName: "החלק שפוצל - הצעת חוק הגנת הסביבה (ייעול הליכי רישוי סביבתי) (תיקוני חקיקה), התשפ\"ד-2024",
  type: "governmental",
  committeeId: "interior-environment",
  status: "agenda",
  lastUpdated: "2024-04-01",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "inProgress",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
