// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2217762,
  syncedAt: "2026-08-12",
  officialName: "חוק פיצויי פיטורים (תיקון מס' 34 – הוראת שעה – חרבות ברזל), התשפ\"ד-2024",
  type: "governmental",
  committeeId: "labor-welfare",
  status: "completed",
  summaryOfficial: "לפי סעיף 5 לחוק פיצויי פיטורים, התשכ\"ג-1963, מעסיק חייב לשלם לשאריו המפורטים בחוק של עובד שנפטר את פיצויי הפיטורים שהיה משלם לו אילו היו מפטר אותו, ואם אין לנפטר בן זוג או ילדים התלויים בו, נדרש הליך בבית הדין לעבודה לעניין מתן פיצויי הפיטורים לשאירים האחרים. התיקון לחוק נועד לייתר את הפנייה לבית הדין לעבודה בכך שהוא קובע כהוראת שעה לגבי עובד שנפטר בתקופה שמיום 7.10.23 ועד שנה מתום תקופת תוקפה של ההכרזה על מצב מיוחד בעורף שהוכרזה ביום האמור, שפיצויי הפיטורים ישולמו על ידי המעסיק לשאריו של העובד שנפטר, ואם אין שארים ישולמו הפיצויים ליורשים על פי דין או לזוכים לפי צוואה לפי חוק הירושה. החוק מסמיך את שר העבודה להאריך את התקופה שלגבי הנפטרים בה יחול ההסדר, בתקופות נוספות שמשכן הכולל לא יעלה על 12 חודשים אם הדבר נדרש עקב הימשכות מלחמת חרבות ברזל.",
  lastUpdated: "2024-09-30",
  completedDate: "2024-08-05",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-07-03",
          time: "10:00",
          sessionId: 2219904
        },
        {
          date: "2024-07-08",
          time: "10:30",
          sessionId: 2220297
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
