// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2217130,
  syncedAt: "2026-08-12",
  officialName: "חוק הבנקאות (רישוי) (תיקון מס' 31), התשפ\"ד-2024",
  type: "governmental",
  committeeId: "economy",
  status: "completed",
  summaryOfficial: "החוק מטפל בשני נושאים: האחד, הקלה על מכירת אחזקותיה של חברת כרטיסי האשראי \"כאל\" על ידי בנק דיסקונט, וזאת על ידי ביטול האיסורים החלים על גוף מוסדי גדול ועל תאגיד ריאלי משמעותי הנוגעים לרכישת אמצעי שליטה בחברת כרטיסי אשראי מבנק בעל היקף פעילות רחב, וכן על ידי הארכת המועדים האחרונים להפרדה בין בנק דיסקונט לחברת כאל. הנושא השני נוגע לעידוד התחרות בשוק האשראי על ידי הרחבת האיסור לגבי שליטה בחברת כרטיסי אשראי גם לבנק בעל היקף פעילות בינוני, ועל ידי כך מניעת מצב שבו יש שחקן השולט בחברת כרטיסי אשראי, אך הוא נעדר תמריצים לפעול באופן אגרסיבי באותו שוק.",
  lastUpdated: "2024-09-29",
  completedDate: "2024-07-22",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-07-10",
          time: "09:00",
          sessionId: 2220144
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
