// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2217246,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק התקנת מצלמות לשם הגנה על פעוטות במעונות יום לפעוטות (תיקון), התשפ\"ד-2024",
  type: "governmental",
  committeeId: "education",
  status: "agenda",
  lastUpdated: "2024-04-16",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2024-04-03",
          time: "21:09",
          sessionId: 2217291
        },
        {
          date: "2024-05-07",
          time: "10:00",
          sessionId: 2217585
        },
        {
          date: "2024-05-28",
          time: "13:30",
          sessionId: 2218244
        },
        {
          date: "2024-09-03",
          time: "09:00",
          sessionId: 2221854
        },
        {
          date: "2025-01-14",
          time: "14:30",
          sessionId: 2226523
        },
        {
          date: "2025-03-10",
          time: "09:30",
          sessionId: 2229506
        },
        {
          date: "2025-06-03",
          time: "12:00",
          sessionId: 2232169
        }
      ]
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
