// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2217541,
  syncedAt: "2026-08-12",
  officialName: "חוק כלי הירייה (תיקון מס' 24) (תיקון), התשפ\"ד–2024",
  type: "governmental",
  committeeId: "national-security",
  status: "completed",
  summaryOfficial: "במסגרת חוק כלי הירייה (תיקון מס' 24), התשפ\"ג–2023 (להלן – החוק), נקבע כי דמוי כלי ירייה, הינו כלי בעל קנה שאינו כלי ירייה, לרבות חלק ממנו, שניתן להסב אותו לכלי ירייה והוא מסוג המנוי ברשימה שיקבע השר לביטחון פנים בצו לאחר התייעצות עם המפקח הכללי של המשטרה. כמו כן נקבע כי פעילות ייצור, יצוא, יבוא, אחסנה, הובלה ומסחר בדמויי כלי ירייה יחויבו ברישיון, וכי החזקה ונשיאה של דמויי כלי ירייה ייעשו רק במועדוני קליעה שקיבלו רישיון לכך. זאת ועוד, כהוראת שעה לשנה, יתאפשר גם מתן הרשאה להחזקה ונשיאה של דמוי כלי ירייה לצורכי אימונים ותחרויות, במספר מוגבל ובכפוף לתנאים שייקבעו בתקנות. \nבמסגרת התיקון לחוק נדחה באופן רטרואקטיבי מועד פרסום הצו המפרט את רשימת הכלים הכלולים בהגדרה של \"דמוי כלי יריה\" בתשעה חודשים, כך שהצו יפורסם עד יום ב' באב התשפ\"ד (6 באוגוסט 2024), וכי תחילת תיקון זה יהיה ביום כ\"ב בחשוון התשפ\"ד (6 בנובמבר 2023). כמו כן, נקבע לדחות את מועד פקיעת איסור הייבוא בעניין זה, כל עוד לא נכנס הצו כאמור לתוקף או עד שמונה עשרה חודשים מיום תחילת החוק, לפי המוקדם.",
  lastUpdated: "2025-10-20",
  completedDate: "2024-05-08",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-04-15",
          time: "11:15",
          sessionId: 2217453
        },
        {
          date: "2024-05-02",
          time: "11:00",
          sessionId: 2217543
        },
        {
          date: "2024-05-08",
          time: "11:30",
          sessionId: 2217769
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
