// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2218306,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק זיכרון אירועי הטרור של כ\"ב בתשרי (ה-7 באוקטובר) ומלחמת חרבות ברזל, התשפ\"ד-2024",
  type: "private",
  committeeId: "education",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2024-09-25",
  initiators: [
    {
      kind: "mk",
      personId: 30102,
      name: "מירב בן ארי",
      partyId: "yesh-atid",
      factionName: "יש עתיד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2024-09-22",
          time: "10:30",
          sessionId: 2222179
        },
        {
          date: "2024-09-25",
          time: "14:00",
          sessionId: 2222303
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
