// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2218723,
  syncedAt: "2026-09-22",
  officialName: "חוק הנכים (תגמולים ושיקום) (תיקון מס' 35), התשפ\"ו–2026",
  type: "private",
  committeeId: "knesset-committee",
  status: "completed",
  summaryOfficial: "החוק מוסיף לחוק הנכים (תגמולים ושיקום) את ההגדרות \"הלם קרב\" ו\"נפגע הלם קרב\" וקובע כי לנפגעי הלם קרב ינתן טיפול רפואי מותאם. כמו כן החוק קובע כי שר הביטחון יקים ועדה מתן סיוע לפנים משורת הדין לנכים ולבני משפחה של נכים עם מאפיינים מיוחדים, כלומר נכים שיש להם דרגת נכות של 35% לפחות בשל פגימת ראש או פגימה נפשית ובכלל זה הפרעה בתר-חבלתית, דרגת נכות 100% או דרגת נכות מיוחדת, אם בן המשפחה נקלע למצוקה קשה בקשר לנכותו של הנכה. ההוראות לעניין הוועדה למתן סיוע לפנים משורת הדין הוחלו גם על נפגעי פעולות איבה.",
  lastUpdated: "2026-09-22",
  completedDate: "2026-07-13",
  initiators: [
    {
      kind: "mk",
      personId: 30853,
      name: "משה סעדה",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30839,
      name: "דן אילוז",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30877,
      name: "משה פסל",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-11-25",
          time: "09:00",
          sessionId: 2224331
        },
        {
          date: "2024-12-18",
          time: "09:00",
          sessionId: 2225640
        },
        {
          date: "2026-07-12",
          time: "10:00",
          sessionId: 2245092
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2026-07-15",
          time: "10:30",
          sessionId: 2245219
        },
        {
          date: "2026-07-15",
          time: "10:30",
          sessionId: 2245219
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
