// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2218799,
  syncedAt: "2026-08-12",
  officialName: "חוק לתיקון פקודת סדר הדין הפלילי (מעצר וחיפוש) (מס' 17), התשפ\"ד–2024",
  type: "governmental",
  committeeId: "national-security",
  status: "completed",
  summaryOfficial: "במסגרת חוק המאבק בכלי הנשק הבלתי חוקיים (תיקון חקיקה והוראת שעה), התשפ\"ג–2023, נעשה תיקון לפקודת סדר הדין הפלילי (מעצר וחיפוש) [נוסח חדש], התשכ\"ט–1969 (להלן – הפקודה), לפיו נוספו שתי עילות חדשות לביצוע חיפוש ללא צו שופט במטרה להקנות למשטרה כלי אכיפה יעילים למיגור תופעת כלי הנשק הבלתי חוקיים. העילה הראשונה שנוספה מאפשרת לשוטר לבצע חיפוש ללא צו שופט אם התעורר חשד סביר שכלי נשק או חלק מהותי מנשק, שעשוי לשמש ראיה לביצוע עבירה, נמצא במקום, ואם בשל הצורך המיידי לביצוע החיפוש לא ניתן לקבל צו. העילה השנייה שנוספה מאפשרת למשטרה לבצע חיפוש של תיעוד או מצלמה שעשויים לשמש ראיה לביצוע עבירה שדינה עשר שנות מאסר לפחות, הכוללת עבירת נשק, עבירה של ירי במקום מגורים או עבירת סחיטה באיומים. לגבי שתי עילות אלו, נקבע כי החיפוש יבוצע רק באישור בכתב של קצין משטרה בדרגת רב-פקד ומעלה, שיכלול את הנסיבות והנימוקים לצורך בחיפוש מיידי ללא צו. עוד נקבע כי אם במהלך החיפוש נתגלה חפץ שאינו נוגע לעבירה שבשלה ניתן האישור לביצוע החיפוש, השוטר יהיה רשאי לתפוס את החפץ ולהביאו לבחינת שופט, אשר יחליט מה ייעשה בו. הסדרים אלו נקבעו כהוראת שעה לתקופה של שנה, החל מיום כ\"ד באייר התשפ\"ג (15 במאי 2023), זאת בכדי לאפשר בחינה של ההסדרים המוצעים.\nבמסגרת תיקון מספר 17 לפקודה, נקבע כי הוראת השעה כאמור תוארך בשנה אחת, עד ליום ד' בתמוז התשפ\"ה (30 ביוני 2025).",
  lastUpdated: "2025-08-05",
  completedDate: "2024-06-26",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-06-24",
          time: "09:00",
          sessionId: 2219521
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
