// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2218798,
  syncedAt: "2026-08-12",
  officialName: "חוק לדחיית הבחירות הכלליות לרשויות המקומיות (תיקון מס' 2), התשפ\"ד-2024",
  type: "governmental",
  committeeId: "interior-environment",
  status: "completed",
  summaryOfficial: "נקבע שאוצר המדינה ישפה סיעה, מועמד או רשימה שהתמודדו בבחירות האחרונות לרשויות המקומיות ובהם לא התרחשו לבסוף בחירות, בסכום השווה להוצאות הבחירות שהוציאו בפועל וכדין, ובלבד שהסכום לא יעלה על 75% מסכום המימון הכולל ברשות, בניכוי מקדמות שהתקבלו. עלה הסכום הכולל לתשלום לכלל המועמדים על 115% מסכום המימון לכלל הרשויות המקומיות הרלוונטיות, יופחתו סכומי התשלום אותם יקבלו המועמדים בשיעור שווה. התשלום יותנה בהגשת בקשה תוך 30 ימים לשר הפנים והגשת דוח כספי למבקר המדינה. בנוסף מוצע שתותר תרומה נוספת מאדם, אף אם תרם את התרומה המירבית לטובת הבחירות שלא התקיימו.",
  lastUpdated: "2024-07-07",
  completedDate: "2024-07-03",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-06-03",
          time: "15:45",
          sessionId: 2218757
        },
        {
          date: "2024-06-17",
          time: "09:30",
          sessionId: 2218835
        },
        {
          date: "2024-07-01",
          time: "10:00",
          sessionId: 2219441
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
