// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2218716,
  syncedAt: "2026-08-12",
  officialName: "חוק להנצחת זכרו של מנחם בגין (תיקון מס' 4), התשפ\"ה–2025",
  type: "private",
  committeeId: "education",
  status: "completed",
  summaryOfficial: "בחוק להנצחת זכרו של מנחם בגין, התשנ\"ח–1998, יתווספו הוראות כך שבכל שנה, ב-ד' באדר, יום פטירתו של מנחם בגין, יקויים יום ציון לזכרו. במהלך היום יתקיימו ארועי זכרון והנצחה. במחנות צה\"ל יוקדש זמן להנצחת זכרו וללימוד פועלו בהתאם להחלטת הרמטכ\"ל, ובבתי הספר יוקדש זמן לכך ככל ששר החינוך יחליט על כך.",
  lastUpdated: "2025-04-20",
  completedDate: "2025-03-31",
  initiators: [
    {
      kind: "mk",
      personId: 30706,
      name: "קטי קטרין שטרית",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-01-21",
          time: "13:30",
          sessionId: 2227005
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-03-18",
          time: "13:30",
          sessionId: 2229790
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
