// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2218838,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק המים (תיקון - קביעת תעריפי מים לחקלאות), התשפ\"ד-2024",
  type: "private",
  committeeId: "economy",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2024-12-04",
  initiators: [
    {
      kind: "mk",
      personId: 30810,
      name: "מיכל מרים וולדיגר",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2024-07-30",
          time: "10:00",
          sessionId: 2221179
        },
        {
          date: "2024-11-13",
          time: "09:15",
          sessionId: 2222274
        },
        {
          date: "2024-12-04",
          time: "09:00",
          sessionId: 2224296
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
