// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2220439,
  syncedAt: "2026-08-12",
  officialName: "חוק סיוע לבני משפחה של נעדרים, התשפ\"ו–2026",
  type: "private",
  committeeId: "national-security",
  status: "completed",
  summaryOfficial: "חוק סיוע לבני משפחה של נעדרים, התשפ\"ו–2026, מסדיר מנגנון לקידום הסיוע למשפחות נעדרים ולייעול שיתוף הפעולה בין רשויות המדינה. על פי החוק, \"נעדר\" מוגדר כאזרח או תושב ישראל שנעדר מביתו או ממסגרת שהייתו לפחות 60 ימים מיום הדיווח למשטרה, מקום הימצאו אינו ידוע, לא ניתן ליצור עימו קשר, אין ראיה לכך שאינו בחיים, ויש לגביו הכרזה תקפה כנעדר על ידי המשטרה. ההגדרה כוללת חייל שנעדר משירות צבאי, למעט במקרים של חשד לעבירות עריקות או היעדר מן השירות. החוק קובע כי שר העבודה ימנה ועדה בין-משרדית, בראשות נציג משרדו, שתכלול נציגים ממגוון משרדי ממשלה, מהמוסד לביטוח לאומי ומהאפוטרופוס הכללי. תפקידה של הוועדה לתכלל את המענים הניתנים למשפחות, לגבש נהלי עבודה קבועים בין הרשויות ולבחון מקרים פרטניים לשם שיפור הטיפול. לשם כך, חויבו משטרת ישראל וצבא הגנה לישראל להודיע לוועדה על אדם כנעדר, באופן שלא יפגע בצורכי חקירה, ביחסי החוץ או בביטחון המדינה, והוסדרו סמכויות למסירת מידע רלוונטי לוועדה מגופים ציבוריים, בכפוף להסכמת המשפחה ושמירה על פרטיות. עוד קובע החוק כי המשטרה או צה\"ל יחויבו ליידע את בני המשפחה של נעדר בדבר אפשרותם לפנות למחלקה לשירותים חברתיים ברשות המקומית וללשכת הסיוע המשפטי, לשם בחינת זכויותיהם. בנוסף לכך, במסגרת החוק תוקן חוק הסיוע המשפטי, כך שמשפחת נעדר תהיה זכאית לסיוע משפטי בהליכים אזרחיים בישראל הקשורים לענייניו, ללא צורך בעמידה במבחן זכאות כלכלית. וכן תוקנו חוק הביטוח הלאומי וחוק ביטוח בריאות ממלכתי, כך שיינתן פטור מתשלום דמי ביטוח בעד התקופה שבה האדם נעדר, בתנאי שאין לו הכנסה אחרת, ונקבע כי לא תשולם גמלה בעדו בחלוף שישה חודשים מהמועד שבו נקבע כי הוא נעדר, וכל עוד לא אותר.",
  lastUpdated: "2026-07-27",
  completedDate: "2026-05-20",
  initiators: [
    {
      kind: "mk",
      personId: 30859,
      name: "צביקה פוגל",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    },
    {
      kind: "mk",
      personId: 30810,
      name: "מיכל מרים וולדיגר",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    },
    {
      kind: "mk",
      personId: 30106,
      name: "נעמה לזימי",
      partyId: "labor",
      factionName: "העבודה"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-06-30",
          time: "12:15",
          sessionId: 2233382
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2026-05-06",
          time: "09:00",
          sessionId: 2242633
        },
        {
          date: "2026-05-13",
          time: "09:00",
          sessionId: 2242833
        },
        {
          date: "2026-05-13",
          time: "10:00",
          sessionId: 2243026
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
