// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2220910,
  syncedAt: "2026-08-12",
  officialName: "חוק שירות ביטחון (תיקון מס' 29 - הוראת שעה), התשפ\"ו-2026",
  type: "governmental",
  committeeId: "foreign-defense",
  status: "completed",
  summaryOfficial: "חוק שירות ביטחון מסדיר את חובת השירות ומשך השירות הסדיר בצבא הגנה לישראל. במסגרת תיקונים קודמים לחוק, נקבע כי משך השירות לגברים שמתגייסים החל מ-1 ביולי 2024 יקוצר ל-30 חודשים במקום 32 חודשים. כעת, על רקע מלחמת \"חרבות ברזל\" והצורך המבצעי שהתעורר בעקבותיה, נקבע במסגרת חוק שירות ביטחון (תיקון מס' 29 – הוראת שעה), התשפ\"ו–2026, כהוראת שעה עד ליום י\"ז בתמוז התשפ\"ט (30 ביוני 2029), כי תקופת השירות הסדיר של יוצא צבא גבר תעמוד על 32 חודשים, במקום 30 חודשים. עוד נקבע כי הארכה זו תחול גם על כל יוצא צבא שכבר מצוי בשירות סדיר ביום פרסומו של החוק. כמו כן, כדי לאזן את הפגיעה באינטרס ההסתמכות של החיילים שהתגייסו לשירות מקוצר וכעת שירותם מוארך, מעגן החוק מנגנון תגמול ייעודי: ליוצא צבא שנקרא מראש לשירות סדיר של 30 חודשים ישולמו דמי קיום מוגדלים בעד החודש השלושים ואחד ועד תום החודש השלושים ושניים לשירותו. לעניין זה, החוק קובע כי מי שנקרא לשירות בתקופה שמיום כ\"ה בסיוון התשפ\"ד (1 ביולי 2024) עד יום ד' בתמוז התשפ\"ה (30 ביוני 2025), יהיה זכאי, בחודשי ה-31 וה-32 לשירותם, לדמי קיום בגובה כפל דמי הקיום הקבועים לפי פקודות הצבא; ואילו לגבי חיילים שנקראו לשירות בתקופה שמיום ה' בתמוז התשפ\"ה (1 ביולי 2025) עד יום ט\"ו בתמוז התשפ\"ו (30 ביוני 2026), דמי הקיום שלהם בחודשים אלה יוגדלו ב-75%.",
  lastUpdated: "2026-07-26",
  completedDate: "2026-07-13",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-07-24",
          time: "08:30",
          sessionId: 2221216
        },
        {
          date: "2024-08-07",
          time: "11:30",
          sessionId: 2221602
        },
        {
          date: "2026-05-20",
          time: "10:00",
          sessionId: 2243227
        },
        {
          date: "2026-05-20",
          time: "09:00",
          sessionId: 2243226
        },
        {
          date: "2026-07-02",
          time: "13:00",
          sessionId: 2244664
        },
        {
          date: "2026-07-12",
          time: "15:00",
          sessionId: 2245030
        },
        {
          date: "2026-07-13",
          time: "11:00",
          sessionId: 2245179
        },
        {
          date: "2026-07-13",
          time: "22:00",
          sessionId: 2245187
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
