// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2220329,
  syncedAt: "2026-08-12",
  officialName: "חוק הביטוח הלאומי (תיקון מס' 255), התשפ\"ה–2025",
  type: "private",
  committeeId: "labor-welfare",
  status: "completed",
  summaryOfficial: "בתיקון זה לחוק הביטוח הלאומי נקבע כי אדם שלפני שירותו במילואים שוחרר משירות קבע, יחולו עליו הוראות פרק י\"ב לחוק הביטוח הלאומי והתקנות שנקבעו לפיו, לעניין חישוב תגמול המילואים, כאילו היה עובד בעת שירותו בשירות הקבע, אף שלא התקיימו לגביו יחסי עבודה, אלא אם כן לטובתו הוא שחישוב התגמול ייעשה ללא התייחסות לשירות הקבע. תחילתו של החוק היא ביום 1 ביוני 2025, והוא יחול על תגמול המגיע בעד שירות מילואים שהחל ביום 7 באוקטובר 2023 או אחריו.",
  lastUpdated: "2025-08-11",
  completedDate: "2025-03-05",
  initiators: [
    {
      kind: "mk",
      personId: 30702,
      name: "חוה אתי עטייה",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-11-19",
          time: "12:00",
          sessionId: 2223894
        },
        {
          date: "2024-11-19",
          time: "14:00",
          sessionId: 2223569
        },
        {
          date: "2024-12-09",
          time: "12:00",
          sessionId: 2224993
        },
        {
          date: "2025-01-27",
          time: "11:00",
          sessionId: 2227502
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-02-19",
          time: "10:00",
          sessionId: 2228577
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
