// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2220657,
  syncedAt: "2026-08-12",
  officialName: "חוק יום לציון עליית יהודי תימן לישראל ולהנצחת זכרם של הנספים בדרך לישראל, התשפ\"ה–2025",
  type: "private",
  committeeId: "education",
  status: "completed",
  summaryOfficial: "מדי שנה, ביום ט\"ו בכסלו, יקוים יום לציון עליית יהודי תימן לישראל ולהנצחת זכרם של הנספים בדרך ארצה. יום זה יצויין בדיון מיוחד בכנסת. כמו כן, ייערך כנס עיוני בנושא עליית יהודי תימן לישראל והנצחת זכרם של הנספים בדרך, ברוח ערכי המסורת והמורשת של יהדות תימן. במוסדות החינוך תתקיים פעילות חינוכית-ערכית ככל שיחליט על כך שר החינוך.",
  lastUpdated: "2025-04-01",
  completedDate: "2025-02-04",
  initiators: [
    {
      kind: "mk",
      personId: 30868,
      name: "יונתן מישרקי",
      partyId: "shas",
      factionName: "התאחדות הספרדים שומרי תורה תנועתו של מרן הרב עובדיה יוסף זצ\"ל"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-11-26",
          time: "11:00",
          sessionId: 2224151
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-01-21",
          time: "12:00",
          sessionId: 2226986
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
