// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2220461,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק נכסי המדינה (תיקון מס' 9) (הרשאת שימוש לשם הקמת מיתקני שידור לתקשורת בשיטה התאית), התשפ\"ה–2025",
  type: "private",
  committeeId: "economy",
  status: "dropped",
  offPipelineReason: "נעצרה",
  lastUpdated: "2025-07-21",
  initiators: [
    {
      kind: "mk",
      personId: 30480,
      name: "אברהם בצלאל",
      partyId: "shas",
      factionName: "התאחדות הספרדים שומרי תורה תנועתו של מרן הרב עובדיה יוסף זצ\"ל"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-03-23",
          time: "15:30",
          sessionId: 2229966
        },
        {
          date: "2025-05-12",
          time: "12:30",
          sessionId: 2230818
        },
        {
          date: "2025-05-19",
          time: "12:30",
          sessionId: 2231547
        }
      ]
    },
    {
      stage: "first",
      state: "inProgress",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
