// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2220848,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק יסוד: השפיטה (תיקון - שלילת זכות עמידה למתגמל טרור)",
  type: "private",
  committeeId: "constitution",
  status: "agenda",
  lastUpdated: "2024-11-06",
  initiators: [
    {
      kind: "mk",
      personId: 30812,
      name: "שמחה רוטמן",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2024-11-04",
          time: "12:30",
          sessionId: 2223122
        },
        {
          date: "2024-11-05",
          time: "12:45",
          sessionId: 2223242
        },
        {
          date: "2024-11-18",
          time: "09:00",
          sessionId: 2223784
        },
        {
          date: "2024-12-10",
          time: "14:00",
          sessionId: 2224194
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
