// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2221978,
  syncedAt: "2026-08-12",
  officialName: "חוק הפחתת הגירעון והגבלת ההוצאה התקציבית (תיקון מס' 26), התשפ\"ד-2024",
  type: "governmental",
  committeeId: "finance",
  status: "completed",
  summaryOfficial: "מוצע לתקן את חוק הפחתת הגירעון והגבלת ההוצאה התקציבית התשנ\"ב-1992, ולהגדיל את ההוצאה הממשלתית בשנת 2024 בסכום של 3,357 מיליארד שקלים חדשים לצורך מימון ההוצאות הדרושות לצרכים אזרחיים הנובעים ממלחמת חרבות ברזל.",
  lastUpdated: "2024-11-27",
  completedDate: "2024-09-29",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-09-11",
          time: "12:40",
          sessionId: 2222015
        },
        {
          date: "2024-09-17",
          time: "13:00",
          sessionId: 2222115
        },
        {
          date: "2024-09-19",
          time: "12:00",
          sessionId: 2222121
        },
        {
          date: "2024-09-22",
          time: "13:00",
          sessionId: 2222252
        },
        {
          date: "2024-09-23",
          time: "13:00",
          sessionId: 2222254
        },
        {
          date: "2024-09-23",
          time: "10:00",
          sessionId: 2222253
        },
        {
          date: "2024-09-24",
          time: "13:00",
          sessionId: 2222300
        },
        {
          date: "2024-09-25",
          time: "13:30",
          sessionId: 2222222
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
