// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2221641,
  syncedAt: "2026-08-12",
  officialName: "חוק הסכמים קיבוציים (תיקון מס' 11 – הוראת שעה – חרבות ברזל) (הוראות מיוחדות לעניין הרחבת הסכם קיבוצי כללי שנעשה בשל פעולות האיבה או פעולות המלחמה) (תיקון), התשפ\"ד-2024",
  type: "governmental",
  committeeId: "labor-welfare",
  status: "completed",
  summaryOfficial: "הוארך תוקפן של הוראות השעה בחוק הסכמים קיבוציים שמקצרות את המועדים ומפשטות את ההליכים למתן צו הרחבה להסכם קיבוצי כללי, שלגביו שר העבודה ציין כי העניינים בו נובעים בעיקרם ממלחמת חרבות ברזל, ושוכנע שיש דחיפות בהרחבתו. הוראות אלו יחולו ברציפות עד תום שלושה חודשים מסיום התוקף של ההכרזה על מצב מיוחד בעורף שהוכרזה בתחילת המלחמה.",
  lastUpdated: "2025-04-29",
  completedDate: "2024-10-28",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-08-05",
          time: "09:00",
          sessionId: 2221565
        },
        {
          date: "2024-09-16",
          time: "13:00",
          sessionId: 2221755
        },
        {
          date: "2024-09-25",
          time: "13:00",
          sessionId: 2222280
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
