// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2222052,
  syncedAt: "2026-08-12",
  officialName: "חוק הבנקאות (שירות ללקוח) (תיקון מס' 38), התשפ\"ה–2025",
  type: "private",
  committeeId: "economy",
  status: "completed",
  summaryOfficial: "החוק קובע שהחל מ-1.12.2025, בנק ששווי נכסיו עולה על 5% משווי הנכסים של כלל הבנקים בישראל יהיה חייב לאפשר ללקוחות כל הבנקים לפתוח אצלו פיקדון במטבע ישראלי, מבלי להתנות זאת בפתיחת חשבון עובר ושב בבנק. לפי החוק, אפשרות זו מותנית בכך שהכספים יופקדו בפיקדון באמצעות חשבון במערכת סגורה, שניתן להפקיד בו רק כספים מחשבון של בעל הפיקדון בבנק אחר או בבנק הדואר, וכן להעביר אותם בחזרה רק לחשבון ממנו הועברו, וכן בהתאם לתנאים שקבע נגיד בנק ישראל בצו לפי חוק איסור הלבנת הון. בנוסף, החוק אוסר על בנק להפעיל השפעה בלתי הוגנת על הלקוח בכל עניין הקשור בפתיחת פיקדון כאמור בבנק אחר. כדי להקל על הליך הפקדת הכספים בפיקדון בבנק אחר, החוק מאפשר ללקוח לאשר בכתב לבנק שבו הוא מבקש להפקיד כספים לנהל עבורו את ההליכים הנדרשים לשם כך. המפקח על הבנקים יהיה רשאי להחיל את הוראות החוק גם על הפקדת כספים בפיקדונות במטבע חוץ. עוד קובע החוק כי המפקח על הבנקים יפרסם את מספר הפיקדונות שהופקדו בכל אחד מהבנקים באמצעות חשבון במערכת סגורה. כמו כן, המפקח על הבנקים יעביר לוועדת הכלכלה של הכנסת דיווח שנתי, החל משנת 2027 ולמשך 3 שנים, על יישום הוראות חוק זה.",
  lastUpdated: "2025-06-22",
  completedDate: "2025-05-13",
  initiators: [
    {
      kind: "mk",
      personId: 30880,
      name: "אביחי אברהם בוארון",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30873,
      name: "ארז מלול",
      partyId: "shas",
      factionName: "התאחדות הספרדים שומרי תורה תנועתו של מרן הרב עובדיה יוסף זצ\"ל"
    },
    {
      kind: "mk",
      personId: 30877,
      name: "משה פסל",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-12-25",
          time: "11:00",
          sessionId: 2226111
        },
        {
          date: "2025-02-18",
          time: "11:30",
          sessionId: 2228128
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-03-11",
          time: "11:00",
          sessionId: 2229633
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
