// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2222789,
  syncedAt: "2026-08-12",
  officialName: "חוק לייעול האכיפה והפיקוח העירוניים ברשויות המקומיות (הוראת שעה) (תיקון מס' 13), התשפ\"ה-2024",
  type: "governmental",
  committeeId: "national-security",
  status: "completed",
  summaryOfficial: "החוק לייעול האכיפה והפיקוח העירוניים ברשויות המקומיות נחקק כהוראת שעה בשנת 2011, והחל כפיילוט במספר רשויות מקומיות. מטרת החוק הינה ייעול יכולת הפיקוח והאכיפה של הרשויות המקומיות בעבירות שבתחום אחריותן וכן סיוע למשטרת ישראל בפעולות למניעת אלימות. לשם כך החוק מסמיך פקחים עירוניים ומסדיר את הקמתו של מערך שיטור עירוני. לאורך השנים הוראת השעה הוארכה מספר פעמים ותחולתה הורחבה לרשויות נוספות. \nבתיקון מספר 13 לחוק, תוקן סעיף 23, כך שתוקפו של החוק הוארך לתקופת זמן נוספת ועד ליום י\"ז בכסלו התשפ\"ה (18 בדצמבר 2024).",
  lastUpdated: "2025-04-02",
  completedDate: "2024-10-30",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-10-28",
          time: "10:30",
          sessionId: 2222753
        },
        {
          date: "2024-10-29",
          time: "14:15",
          sessionId: 2222838
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
