// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2222384,
  syncedAt: "2026-08-12",
  officialName: "חוק הרבנות הראשית לישראל (תיקון מס' 8), התשפ\"ה-2024",
  type: "governmental",
  committeeId: "constitution",
  status: "completed",
  summaryOfficial: "החוק עורך שינויים בהרכב האסיפה הבוחרת לרבנים הראשיים ולמועצת הרבנות הראשית. החוק מגדיר כי \"רב\" שניתן למנותו במסגרת 10 הרבנים שממונים לאסיפה הבוחרת על ידי הרבנים הראשיים, הוא רב שמוסמך לרבנות מטעם הרבנות הראשית לישראל או רב שבידו תעודת כשירות לכהונת רב עיר, רב אזורי, רב מושב או רב שכונה. כמו כן, נקבע רף מינימלי למינוי של נשים לנציגות ציבור, מכל אחת מהקבוצות המיוצגות באסיפה הבוחרת ומנגנון למקרים שבהם אין מספיק נשים שמשמשות בתפקידים בקבוצות האמורות. בנוסף, נקבעו הסדרים בנושא ניגוד עניינים. לבסוף, נקבע כי החל מהבחירות שיתקיימו אחרי הבחירות הקרובות למועצת הרבנות הראשית, הגדרות בעלי התפקידים שחברים באסיפה הבוחרת, יחולו גם לגבי מי שממלא תפקיד זה ביהודה ושומרון.",
  lastUpdated: "2025-09-03",
  completedDate: "2024-12-04",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-11-19",
          time: "12:15",
          sessionId: 2223786
        },
        {
          date: "2024-11-24",
          time: "09:00",
          sessionId: 2224186
        },
        {
          date: "2024-11-25",
          time: "12:00",
          sessionId: 2224197
        },
        {
          date: "2024-11-26",
          time: "09:00",
          sessionId: 2224425
        },
        {
          date: "2024-11-26",
          time: "13:00",
          sessionId: 2224472
        },
        {
          date: "2024-11-26",
          time: "14:00",
          sessionId: 2224488
        },
        {
          date: "2024-11-27",
          time: "08:00",
          sessionId: 2224512
        },
        {
          date: "2024-12-02",
          time: "09:00",
          sessionId: 2224514
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
