// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2223826,
  syncedAt: "2026-08-12",
  officialName: "חוק ההתייעלות הכלכלית (תיקוני חקיקה להשגת יעדי התקציב לשנת התקציב 2025) (הקפאת שכר נושאי משרה ברשויות השלטון וברשויות מקומיות בשנת 2025), התשפ\"ה–2024",
  type: "governmental",
  committeeId: "finance",
  status: "completed",
  summaryOfficial: "מוצע לקבוע כי בשנת 2025 לא תעודכן משכורתם של נושאי משרה מסוימים ברשויות השלטון וברשויות המקומיות בהתאם לשינוי השכר הממוצע, וכן שלא תעודכן משכורתם של נושאי משרה כאמור שמשכורתם מעודכנת לפי מדד המחירים לצרכן.",
  lastUpdated: "2025-01-05",
  completedDate: "2024-12-18",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-11-19",
          time: "12:00",
          sessionId: 2223894
        },
        {
          date: "2024-11-19",
          time: "14:00",
          sessionId: 2223569
        },
        {
          date: "2024-12-03",
          time: "13:00",
          sessionId: 2224598
        },
        {
          date: "2024-12-10",
          time: "13:00",
          sessionId: 2225004
        },
        {
          date: "2024-12-12",
          time: "14:00",
          sessionId: 2225289
        },
        {
          date: "2024-12-18",
          time: "09:00",
          sessionId: 2225640
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
