// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2223864,
  syncedAt: "2026-08-12",
  officialName: "חוק כליאתם של לוחמים בלתי חוקיים (תיקון מס' 4 והוראת שעה – חרבות ברזל) (תיקון מס' 3), התשפ\"ה-2024",
  type: "governmental",
  committeeId: "foreign-defense",
  status: "completed",
  summaryOfficial: "חוק כליאתם של לוחמים בלתי חוקיים, התשס\"ב–2002, נועד להסדיר את כליאתם של לוחמים בלתי חוקיים, אשר אינם זכאים למעמד של שבויי מלחמה, בדרך העולה בקנה אחד עם מחויבויותיה של מדינת ישראל לפי הוראות המשפט הבין-לאומי ההומניטרי. בין שלל ההסדרים בחוק זה, נכללים גם ביקורת שיפוטית על כליאתו של לוחם בלתי חוקי, זכאותו לפגישה עם עורך דין וייצוגו ותנאי כליאתו. במקרים שבהם הכריזה הממשלה על מלחמה או הודיעה על נקיטת פעולות צבאיות משמעותיות, הממשלה, באישור ועדת החוץ והביטחון, מוסמכת להכריז על שינויים בתחולת החוק. במהלך תקופת תוקפה של ההכרזה, התקופות המנויות בחוק ארוכות יותר והדרג המוסמך לקבל החלטות לפי החוק נמוך יותר.\nחוק כליאתם של לוחמים בלתי חוקיים (תיקון מס' 4 והוראת שעה – חרבות ברזל), התשפ\"ד–2023, קבע, כהוראת שעה, כי במקרה של הכרזה כאמור, יוארכו התקופות המנויות בחוק אף יותר, הורד הדרג המוסמך לאשר הגבלות על פגישה עם עורך דין, וכן נקבע כי ניתן יהיה לקיים דיונים בדרך של היוועדות חזותית. הוראת השעה הוארכה מאז מספר פעמים, בתיקונים שונים.\nבמסגרת תיקון מספר 3, הוארכה תוקפה של הוראת השעה כאמור עד ליום ב' בניסן התשפ\"ה (31 במרץ 2025), וכן הוארכה תקופת תוקפה של הכרזת הממשלה על שינויים בתחולת החוק עד ליום ל' בשבט התשפ\"ה (28 בפברואר 2025). עוד נקבע כי ההוראות הנוגעות לקיום דיונים בנוכחות הכלוא דרך היוועדות חזותית ולמבקרים רשמיים במתקן הכליאה יחולו במנותק מהכרזת הממשלה כאמור אך עדיין במסגרת הוראת השעה.",
  lastUpdated: "2025-09-07",
  completedDate: "2024-11-27",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-11-26",
          time: "10:00",
          sessionId: 2224215
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
