// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2223362,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק הקמת שדה תעופה בנבטים (הוראות מיוחדות), התשפ\"ה–2025",
  type: "private",
  committeeId: "economy",
  status: "agenda",
  lastUpdated: "2025-04-23",
  initiators: [
    {
      kind: "mk",
      personId: 30691,
      name: "רם בן ברק",
      partyId: "yesh-atid",
      factionName: "יש עתיד"
    },
    {
      kind: "mk",
      personId: 30861,
      name: "שלום דנינו",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30682,
      name: "מיכאל מרדכי ביטון",
      partyId: "national-unity",
      factionName: "המחנה הממלכתי"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-01-07",
          time: "12:00",
          sessionId: 2226589
        },
        {
          date: "2025-01-22",
          time: "09:00",
          sessionId: 2227272
        },
        {
          date: "2025-03-03",
          time: "09:00",
          sessionId: 2229142
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-03-23",
          time: "08:30",
          sessionId: 2229964
        },
        {
          date: "2025-03-25",
          time: "16:50",
          sessionId: 2230376
        }
      ]
    },
    {
      stage: "secondThird",
      state: "inProgress",
      discussions: []
    }
  ]
};
