// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2223990,
  syncedAt: "2026-08-12",
  officialName: "חוק הביטוח הלאומי (תיקון מס' 258), התשפ\"ה-2025 ",
  type: "governmental",
  committeeId: "labor-welfare",
  status: "completed",
  summaryOfficial: "חוק זה קובע כי לעניין זכאות למענק לימודים מהמוסד לביטוח לאומי עבור ילדיו של הורה עצמאי, גם נקיטה בהליכים משפטיים בבתי המשפט לענייני משפחה המעידים על כוונה לפירוק התא המשפחתי יוכלו להיחשב כפעולה בהליך של השתחררות מקשר הנישואין, וזאת גם אם לא נפתח הליך בבית דין דתי. מוצע כי הזכאות לפי התיקון המוצע תחל רק על תביעות למענק לימודים בעד שנת הלימודים שהחלה ב1.9.2025 ואילך.",
  lastUpdated: "2025-12-31",
  completedDate: "2025-06-16",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-05-13",
          time: "10:30",
          sessionId: 2231348
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
