// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2224462,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק הגנת הפרטיות (תיקון מס' 14), התשפ\"ה-2025",
  type: "private",
  committeeId: "national-security",
  status: "agenda",
  lastUpdated: "2025-06-29",
  initiators: [
    {
      kind: "mk",
      personId: 30859,
      name: "צביקה פוגל",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-05-06",
          time: "11:30",
          sessionId: 2223679
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "inProgress",
      discussions: []
    }
  ]
};
