// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2224634,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק העמותות (תיקון - תרומה מישות מדינית זרה), התשפ\"ה-2024",
  type: "private",
  committeeId: "constitution",
  status: "agenda",
  lastUpdated: "2025-03-12",
  initiators: [
    {
      kind: "mk",
      personId: 30710,
      name: "אריאל קלנר",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2025-05-05",
          time: "11:00",
          sessionId: 2230885
        },
        {
          date: "2025-05-28",
          time: "09:00",
          sessionId: 2232056
        },
        {
          date: "2025-06-04",
          time: "09:00",
          sessionId: 2232313
        },
        {
          date: "2025-06-10",
          time: "14:00",
          sessionId: 2232327
        },
        {
          date: "2025-07-21",
          time: "08:00",
          sessionId: 2233738
        },
        {
          date: "2025-11-04",
          time: "13:00",
          sessionId: 2235514
        },
        {
          date: "2025-11-18",
          time: "12:30",
          sessionId: 2236423
        },
        {
          date: "2025-11-25",
          time: "14:00",
          sessionId: 2237047
        },
        {
          date: "2025-12-10",
          time: "09:00",
          sessionId: 2237537
        },
        {
          date: "2025-12-23",
          time: "14:15",
          sessionId: 2238070
        },
        {
          date: "2026-01-13",
          time: "10:00",
          sessionId: 2239020
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
