// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2224519,
  syncedAt: "2026-08-12",
  officialName: "חוק תקציב נוסף לשנת הכספים 2024 (מס' 3), התשפ\"ה-2024",
  type: "governmental",
  committeeId: "finance",
  status: "completed",
  summaryOfficial: "מוצע לקבוע כי תקציב ההוצאה לשנת הכספים 2024 יעמוד על 760,585,079,000 שקלים חדשים המורכב מתקציב רגיל בסך 557,712,771,000 שקלים חדשים ומתקציב פיתוח וחשבון הון בסך 202,872,308,000 שקלים חדשים.",
  lastUpdated: "2025-01-05",
  completedDate: "2024-12-23",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2024-12-05",
          time: "12:20",
          sessionId: 2224881
        },
        {
          date: "2024-12-10",
          time: "11:30",
          sessionId: 2224999
        },
        {
          date: "2024-12-12",
          time: "14:30",
          sessionId: 2225273
        },
        {
          date: "2024-12-15",
          time: "15:00",
          sessionId: 2225401
        },
        {
          date: "2024-12-17",
          time: "10:00",
          sessionId: 2225403
        },
        {
          date: "2024-12-18",
          time: "09:00",
          sessionId: 2225640
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
