// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2224903,
  syncedAt: "2026-08-12",
  officialName: "חוק התקציב לשנת הכספים 2025, התשפ\"ה-2025 ",
  type: "governmental",
  committeeId: "finance",
  status: "completed",
  summaryOfficial: "החוק קובע כי תקציב ההוצאה לשנת הכספים 2025 יעמוד על 755,906,699,000 שקלים חדשים המורכב מתקציב רגיל בסך 547,406,561,000 שקלים חדשים ומתקציב פיתוח וחשבון הון בסך 208,500,138,000 שקלים חדשים, כי תקציב ההוצאה המותנית בהכנסה יעמוד על 84,593,530,000 שקלים חדשים, וכי שיא כוח האדם יעמוד על 100,964 משרות.",
  lastUpdated: "2025-08-07",
  completedDate: "2025-03-24",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-01-13",
          time: "11:00",
          sessionId: 2226694
        },
        {
          date: "2025-01-20",
          time: "10:00",
          sessionId: 2227099
        },
        {
          date: "2025-02-10",
          time: "10:00",
          sessionId: 2228149
        },
        {
          date: "2025-02-11",
          time: "10:00",
          sessionId: 2228152
        },
        {
          date: "2025-02-16",
          time: "09:00",
          sessionId: 2228482
        },
        {
          date: "2025-02-17",
          time: "10:00",
          sessionId: 2228484
        },
        {
          date: "2025-02-20",
          time: "09:00",
          sessionId: 2228495
        },
        {
          date: "2025-02-23",
          time: "09:00",
          sessionId: 2228897
        },
        {
          date: "2025-02-25",
          time: "18:30",
          sessionId: 2229086
        },
        {
          date: "2025-02-26",
          time: "09:30",
          sessionId: 2228899
        },
        {
          date: "2025-02-27",
          time: "10:00",
          sessionId: 2228901
        },
        {
          date: "2025-03-02",
          time: "10:00",
          sessionId: 2229334
        },
        {
          date: "2025-03-04",
          time: "18:00",
          sessionId: 2229347
        },
        {
          date: "2025-03-05",
          time: "09:45",
          sessionId: 2229349
        },
        {
          date: "2025-03-10",
          time: "12:00",
          sessionId: 2229565
        },
        {
          date: "2025-03-12",
          time: "09:30",
          sessionId: 2229572
        },
        {
          date: "2025-03-13",
          time: "08:30",
          sessionId: 2229918
        },
        {
          date: "2025-03-17",
          time: "09:30",
          sessionId: 2229898
        },
        {
          date: "2025-03-17",
          time: "18:20",
          sessionId: 2229921
        },
        {
          date: "2025-03-18",
          time: "09:00",
          sessionId: 2229928
        },
        {
          date: "2025-03-18",
          time: "16:50",
          sessionId: 2230050
        },
        {
          date: "2025-03-19",
          time: "09:00",
          sessionId: 2230084
        },
        {
          date: "2025-03-23",
          time: "09:00",
          sessionId: 2230295
        },
        {
          date: "2025-03-23",
          time: "13:00",
          sessionId: 2230330
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
