// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2225750,
  syncedAt: "2026-08-12",
  officialName: "הנחה בתשלומי ארנונה, חשמל ומים מתוך הצעת חוק למתן הטבות למשרתים במילואים, התשפ\"ה-2024",
  type: "private",
  committeeId: "finance",
  status: "agenda",
  lastUpdated: "2024-12-19",
  initiators: [
    {
      kind: "mk",
      personId: 30852,
      name: "משה סולומון",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    },
    {
      kind: "mk",
      personId: 30867,
      name: "יצחק קרויזר",
      partyId: "otzma",
      factionName: "עוצמה יהודית בראשות איתמר בן גביר"
    },
    {
      kind: "mk",
      personId: 30772,
      name: "ניסים ואטורי",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2025-01-29",
          time: "10:00",
          sessionId: 2227519
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
