// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2225865,
  syncedAt: "2026-08-12",
  officialName: "חוק תאגידי מים וביוב (תיקון מס' 17), התשפ\"ה-2025",
  type: "governmental",
  committeeId: "economy",
  status: "completed",
  summaryOfficial: "התיקון דוחה ל-1.1.2026 את המועד הקובע, שהוא המועד המחייב להקמה של תאגידי מים וביוב אזוריים שיספקו שירותי מים וביוב לכמה רשויות מקומיות. החל במועד הקובע, תאגיד מים וביוב ורשות מקומית לא יספקו  שירותי מים וביוב לצרכנים, אלא באמצעות תאגיד אזורי, ובלבד שלא ניתן פטור מהחובה להקים תאגיד אזורי בהתאם לתנאים הקבועים בחוק. כמו כן, ובהתאמה לדחיית המועד הקובע, התיקון דוחה את המועד לתחילת ביצועם של השלבים להקמת תאגידים אזוריים, כך שיחול ב-1.9.2025.",
  lastUpdated: "2025-04-07",
  completedDate: "2025-01-21",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-01-08",
          time: "10:00",
          sessionId: 2226536
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
