// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2225805,
  syncedAt: "2026-08-12",
  officialName: "חוק קידום התחרות בענפי המזון והפארם (תיקון מס' 9), התשפ\"ו–2025",
  type: "private",
  committeeId: "economy",
  status: "completed",
  summaryOfficial: "החוק משנה את ההגדרה של \"קמעונאי פארם גדול\", הקבועה בחוק קידום התחרות בענפי המזון והפארם, התשע\"ד–2014, כדי להתאים את ההגדרה למאפייני שוק הפארם. כיום, לפי החוק, היקף מחזור המכירות שלפיו מוגדר \"קמעונאי פארם\" כ\"קמעונאי פארם גדול\", עומד על סכום של כ-287 מיליון שקלים חדשים (סכום זה זהה לסכום שלפיו קמעונאי בתחום המזון מוגדר כ\"קמעונאי גדול\"). לפי ההסדר החדש, \"קמעונאי פארם\" יוגדר כ\"קמעונאי פארם גדול\", אם מחזור ההכנסות שלו עומד על 450 מיליון שקלים חדשים, במקום 287 מיליון שקלים, וכן הוא יידרש להחזיק 12 חנויות פארם לפחות. יצוין כי ההגדרה תחול רק לעניין קמעונאי פארם, בעוד שהגדרת \"קמעונאי גדול\" בתחום המזון תישאר כשהייתה.\nשינוי ההגדרה נועד להתאים את החוק הקיים למאפייני שוק הפארם, שמתאפיין בריכוזיות גבוהה ובקשיים בכניסת שחקנים חדשים לשוק. להגדרה של קמעונאי כ\"קמעונאי גדול\" יש השלכות רחבות, שכן החוק הקיים מטיל שורה של הוראות מחמירות החלות אך ורק על קמעונאי גדול – הוראות אלה כוללות, בין היתר, מגבלות על פעולות שקמעונאי גדול רשאי לבצע במסגרת יחסיו עם ספקים, הוראות שעניינן שמירה על תחרות בין קמעונאים הפועלים באותו אזור גאוגרפי וכן חובות שונות בעניין שקיפות מחירים. כתוצאה מתיקון החוק, יצטמצם מספרם של קמעונאי פארם שעליהם יחולו הוראות מחמירות כאמור, והדבר יקל על שחקנים חדשים להיכנס לשוק ויקדם את התחרות בענף.",
  lastUpdated: "2026-04-14",
  completedDate: "2025-12-29",
  initiators: [
    {
      kind: "mk",
      personId: 30601,
      name: "ינון אזולאי",
      partyId: "shas",
      factionName: "התאחדות הספרדים שומרי תורה תנועתו של מרן הרב עובדיה יוסף זצ\"ל"
    },
    {
      kind: "mk",
      personId: 30877,
      name: "משה פסל",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-05-12",
          time: "11:00",
          sessionId: 2230772
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-07-01",
          time: "13:30",
          sessionId: 2232831
        },
        {
          date: "2025-07-07",
          time: "10:30",
          sessionId: 2233889
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
