// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2225485,
  syncedAt: "2026-08-12",
  officialName: "חוק הביטוח הלאומי (תיקון מס' 253 והוראות שעה), התשפ\"ה-2025 ",
  type: "governmental",
  committeeId: "labor-welfare",
  status: "completed",
  summaryOfficial: "התיקון לחוק קובע כמה הוראות לעניין חישוב תגמולי מילואים:\nראשית, התגמול המינימלי ליום מילואים ימשיך לעמוד על שיעור מוגדל של 95% מהסכום הבסיסי לחודש חלקי 30 (כ-321 ש\"ח ליום) עד לסוף שנת 2025. \nשנית, כהוראת שעה עבור עובדים עצמאיים ששירתו במילואים בין פברואר 2023 לסוף שנת 2025 והחלו לפעול כעצמאים עד סוף שנת 2024, התגמול יחושב לפי הגבוה מבין אלה: ההכנסה המחושבת לפי השומה הסופית או ההכנסה ששימשה בסיס לחישוב גובה המקדמות ששולמו לביטוח הלאומי ועל פיה שולמו תגמולי המילואים. התיקון יביא, בין השאר לביטול חובות שנוצרו לעצמאים שקיבלו תגמולים לפי המקדמות, הגבוהים מהכנסתם לפי השומה הסופית. \nשלישית, נקבע בסעיף 274ב לחוק הביטוח הלאומי כללים לחישוב התגמול במקרה של \"סבבי מילואים\" בתקופת חירום, כך שמי שנקרא לשירות נוסף בתוך פחות מ-90 ימים מסיום שירות קודם במילואים יקבל תגמול המבוסס על השכר שקדם לסבב המילואים הראשון שלו בתקופת החירום. לפי התיקון, עליית שכר של עד 20% בין הסבבים תובא בחשבון, ואילו עלייה גבוהה מכך תוכר רק אם יוכח שהיא נובעת מעבודה ולא מתגמולי המילואים עצמם; גרירת שכר לפי סעיף 279 לחוק הביטוח הלאומי לא תחול לעניין שירות מילואים נוסף שהחל בתקופת החירום,  למעט לגבי מבוטח שחלו לגביו ההוראות של סעיף 279 לפני תחילת תקופת החירום – שלגביו תתאפשר גרירת השכר אך יחולו ההוראות הנוגעות לחישוב עליית השכר עד 20% ומעל 20%. הוראות אלו לגבי סבבי השירות נכנסו לתוקף ב-1 במאי 2025  לגבי שירות מילואים מאותו מועד ואילך, והן יחולו בתקופת חירום כפי שהיא מוגדרת בתיקון – לפי קריאה למילואים בצו 8, אלא אם כן שר העבודה, בהסכמת שר האוצר ושר הביטחון ובאישור ועדת העבודה והרווחה קבע בצו כי ההוראות לא יחולו בתקופת החירום או חלקה.",
  lastUpdated: "2026-04-19",
  completedDate: "2025-01-20",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-01-14",
          time: "11:00",
          sessionId: 2226685
        },
        {
          date: "2025-01-15",
          time: "10:00",
          sessionId: 2226688
        },
        {
          date: "2025-01-15",
          time: "09:00",
          sessionId: 2227043
        },
        {
          date: "2025-10-20",
          time: "09:30",
          sessionId: 2235510
        },
        {
          date: "2025-11-11",
          time: "10:15",
          sessionId: 2236399
        },
        {
          date: "2025-11-17",
          time: "12:00",
          sessionId: 2236709
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
