// GENERATED BY scripts/sync-bill.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. Your
// editorial content for this bill lives beside it, in
// src/content/bills/editorial/, and is never touched by the sync.
//
// Regenerate:  node scripts/sync-bill.mjs 2227232
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2227232,
  syncedAt: "2026-08-12",
  officialName: "חוק התחשבנות בין בתי חולים לקופות חולים (בריאות הנפש), התשפ\"ה-2025",
  type: "governmental",
  committeeId: "health",
  status: "completed",
  lastUpdated: "2025-12-31",
  completedDate: "2025-03-19",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-01-27",
          time: "09:00",
          sessionId: 2227073
        },
        {
          date: "2025-02-02",
          time: "11:30",
          sessionId: 2227614
        },
        {
          date: "2025-02-05",
          time: "09:00",
          sessionId: 2227619
        },
        {
          date: "2025-02-09",
          time: "11:30",
          sessionId: 2227709
        },
        {
          date: "2025-02-12",
          time: "09:00",
          sessionId: 2227712
        },
        {
          date: "2025-02-16",
          time: "11:30",
          sessionId: 2228142
        },
        {
          date: "2025-02-19",
          time: "09:00",
          sessionId: 2228184
        },
        {
          date: "2025-02-23",
          time: "13:00",
          sessionId: 2228422
        },
        {
          date: "2025-02-26",
          time: "09:00",
          sessionId: 2228424
        },
        {
          date: "2025-03-12",
          time: "09:00",
          sessionId: 2229799
        },
        {
          date: "2025-03-18",
          time: "19:30",
          sessionId: 2230241
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: [],
      vote: {
        date: "2025-03-20",
        inFavor: 64,
        against: 50,
        abstained: 0,
        absent: 6
      }
    }
  ]
};
