// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2227749,
  syncedAt: "2026-08-12",
  officialName: "חוק איסור אלימות בספורט (תיקון מס' 4), התשפ\"ו–2026",
  type: "private",
  committeeId: "national-security",
  status: "completed",
  summaryOfficial: "במסגרת חוק זה נקבעה עבירה פלילית חדשה וייעודית האוסרת על יידוי אמצעים פירוטכניים באירועי ספורט. החוק מגדיר \"אמצעי פירוטכני\" ככזה הכולל מכלול אמצעים כימיים שהפעלתם גורמת לקולות נפץ, עשן או אור, ובכלל זה חזיזים. על פי החוק, חל איסור מוחלט ליידות אמצעים אלו בזמן קיומו של אירוע ספורט או בסמוך אליו, בין אם היידוי מתבצע בתוך המקום שבו מתקיים האירוע ובין אם הוא מכוון לעבר מקום כזה מבחוץ. נקבע כי אדם שיורשע ביידוי אמצעי פירוטכני באירוע ספורט או לעברו צפוי לעונש של שלוש שנות מאסר, זאת בשונה מהעונש שהיה קבוע עד כה בחוק בגין עבירה כללית של יידוי חפץ שהסתכם בקנס כספי בלבד.",
  lastUpdated: "2026-04-16",
  completedDate: "2026-02-04",
  initiators: [
    {
      kind: "mk",
      personId: 23560,
      name: "יוליה מלינובסקי",
      partyId: "yisrael-beiteinu",
      factionName: "ישראל ביתנו"
    },
    {
      kind: "mk",
      personId: 427,
      name: "אביגדור ליברמן",
      partyId: "yisrael-beiteinu",
      factionName: "ישראל ביתנו"
    },
    {
      kind: "mk",
      personId: 30121,
      name: "עודד פורר",
      partyId: "yisrael-beiteinu",
      factionName: "ישראל ביתנו"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-12-10",
          time: "10:20",
          sessionId: 2237732
        },
        {
          date: "2025-12-23",
          time: "14:00",
          sessionId: 2237862
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2026-01-13",
          time: "10:00",
          sessionId: 2238976
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
