// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2227961,
  syncedAt: "2026-08-12",
  officialName: "חוק להגדלת היצע הדיור ברשויות מקומיות (תיקוני חקיקה), התשפ\"ה-2025",
  type: "private",
  committeeId: "interior-environment",
  status: "completed",
  summaryOfficial: "מוצע לקבוע כי בקביעת מספר התושבים לעניין קביעת מספר חברי המועצה, אישור שכר של עובדים המביא בחשבון את מספר התושבים ברשות המקומית, המשרות התקניות ברשות המקומית שנקבעות לפי מספר התושבים וסיווגן, ומספר סגני ראש הרשות ושכרם - יובאו בחשבון גם מספר התושבים שעתידים להתגורר ביחידות הדיור החדשות הנבנות ברשות המקומית כך שיחושב מספר התושבים כפי שהוא נקבע לאותו עניין בצירוף מכפלה של שני תושבים לכל יחידת דיור חדשה למגורים שטרם ניתנה לגביה תעודת גמר, ובלבד שיש לגביה היתר בנייה בתוקף ואישור תחילת עבודה. כן, מוצע לקבוע כי מניין התושבים יתעדכן רק אם התוספת במספר התושבים על פי הנוסחה המוצעת תעלה על חמישה אחוזים ממספר התושבים ברשות המקומית בעת החישוב ובתנאי שמספר יחידות הדיור החדשות ברשות הוא 1000 לפחות. לבסוף, מוצע לקבוע כי רשות רישוי מקומית תמסור לגזבר העירייה, לשר הפנים ולשר האוצר את מספר יחידות הדיור החדשות, בתחומה של הרשות המקומית במספר מועדים הקבועים בהצעה.",
  lastUpdated: "2025-07-30",
  completedDate: "2025-06-16",
  initiators: [
    {
      kind: "mk",
      personId: 23641,
      name: "יעקב אשר",
      partyId: "utj",
      factionName: "יהדות התורה"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-03-25",
          time: "14:30",
          sessionId: 2230235
        },
        {
          date: "2025-03-30",
          time: "11:00",
          sessionId: 2230540
        },
        {
          date: "2025-04-27",
          time: "14:30",
          sessionId: 2230698
        },
        {
          date: "2025-05-12",
          time: "10:00",
          sessionId: 2230983
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-06-09",
          time: "10:00",
          sessionId: 2232653
        },
        {
          date: "2025-12-31",
          time: "09:00",
          sessionId: 2238442
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
