// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2228568,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק הליכי חקירה והעדה (התאמה לאנשים עם מוגבלות שכלית או נפשית) (תיקון - חקירה והעדה מותאמת למתמודדי נפש), התשפ\"ה-2025",
  type: "private",
  committeeId: "constitution",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2025-12-22",
  initiators: [
    {
      kind: "mk",
      personId: 30810,
      name: "מיכל מרים וולדיגר",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    },
    {
      kind: "mk",
      personId: 30868,
      name: "יונתן מישרקי",
      partyId: "shas",
      factionName: "התאחדות הספרדים שומרי תורה תנועתו של מרן הרב עובדיה יוסף זצ\"ל"
    },
    {
      kind: "mk",
      personId: 30782,
      name: "טטיאנה מזרסקי",
      partyId: "yesh-atid",
      factionName: "יש עתיד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2025-12-16",
          time: "09:00",
          sessionId: 2237779
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
