// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2228138,
  syncedAt: "2026-08-12",
  officialName: "חוק איסור שהייה וישיבה בישראל שלא כדין (תיקוני חקיקה), התשפ\"ה-2025",
  type: "private",
  committeeId: "foreign-defense",
  status: "completed",
  summaryOfficial: "במסגרת החוק נקבע כי שר הפנים או מפקד כוחות צבא הגנה לישראל באזור, לפי העניין, לא ייתן היתר שהייה בישראל ולא יחדש רישיון לישיבה בישראל למבקש שהוא פעיל טרור או של מי שהורשע במעשה טרור, וכן למבקש שהוא בן משפחה של אדם כאמור. כמו כן, נקבע כי המונח \"בן משפחה\" יוגדר אחרת לפי שלב הגשת הבקשה להיתר או לרישיון כאמור. לעניין בקשה ראשונה, המוגשת ככלל טרם הכניסה לישראל, ההגדרה תהיה רחבה ותכלול מעגלים נוספים ואילו לעניין חידוש היתר או רישיון כאמור של אדם שכבר שוהה בישראל ונמצא בהליך להסדרת מעמדו, ההגדרה תהיה מצומצמת ותכלול רק את בני המשפחה הקרובים.\nעוד נקבע כי מי שנכנס לישראל מהאזור או דרך האזור בניגוד לחוק, או מפר תנאי מהתנאים שנקבעו באשרתו או ברישיון הישיבה שניתנו לו לפי חוק זה, לא יקבל היתר או רישיון כאמור במשך עשר שנים, אלא אם כן יסבור שר הפנים או מפקד האזור, לפי העניין, כי יש לתת לו היתר או רישיון כאמור מטעמים מיוחדים.\nזאת ועוד, הוחמרה הענישה בגין עבירות ספציפיות של שהייה בישראל שלא כדין, אם בוצעו בידי מי שנכנס לישראל מהאזור או דרך האזור, ובמסגרת זאת נקבע כי העונש המרבי בעבירות אלה יהיה עד שנתיים מאסר במקום שנה אחת. כמו כן, נקבעו חובת הטלת קנס על מי שהורשע בעבירות כאמור, וכן הסדר חילוט, המבוסס על חזקה שלפיה כסף מזומן הנמצא בחזקתו של חשוד בעבירות המבוצעות בנסיבות אלה יראה כשכר שניתן עבור ביצוע העבירה או כאמצעי לביצועה, אלא אם הוכח אחרת.",
  lastUpdated: "2025-08-14",
  completedDate: "2025-07-09",
  initiators: [
    {
      kind: "mk",
      personId: 30711,
      name: "עמית הלוי",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30876,
      name: "אושר שקלים",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30706,
      name: "קטי קטרין שטרית",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-02-25",
          time: "10:00",
          sessionId: 2228874
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-05-13",
          time: "12:15",
          sessionId: 2231406
        },
        {
          date: "2025-06-15",
          time: "13:30",
          sessionId: 2233057
        },
        {
          date: "2025-07-01",
          time: "14:00",
          sessionId: 2233469
        },
        {
          date: "2025-07-02",
          time: "10:00",
          sessionId: 2233688
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
