// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2228505,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק שירות הקבע בצבא הגנה לישראל (גמלאות) (תיקון - קצבאות שאירים - תיקונים שונים), התשפ\"ה-2025",
  type: "private",
  committeeId: "labor-welfare",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2026-01-13",
  initiators: [
    {
      kind: "mk",
      personId: 30701,
      name: "אופיר כץ",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30807,
      name: "גלעד קריב",
      partyId: "labor",
      factionName: "העבודה"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2026-01-06",
          time: "10:00",
          sessionId: 2238706
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
