// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2229395,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק למניעת מפגעי אסבסט ואבק מזיק (תיקון מס' 5), התשפ\"ה-2025",
  type: "governmental",
  committeeId: "interior-environment",
  status: "agenda",
  lastUpdated: "2025-07-13",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-07-01",
          time: "15:00",
          sessionId: 2232904
        }
      ]
    },
    {
      stage: "secondThird",
      state: "inProgress",
      discussions: []
    }
  ]
};
