// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2229019,
  syncedAt: "2026-08-12",
  officialName: "חוק נוכחות עורך דין בחקירת קטינים ואנשים עם מוגבלות (תיקוני חקיקה והוראת שעה), התשפ\"ו-2026",
  type: "governmental",
  committeeId: "constitution",
  status: "completed",
  lastUpdated: "2026-07-30",
  completedDate: "2026-07-28",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-05-14",
          time: "09:00",
          sessionId: 2231328
        },
        {
          date: "2025-05-27",
          time: "09:00",
          sessionId: 2231659
        },
        {
          date: "2025-06-05",
          time: "09:00",
          sessionId: 2232318
        },
        {
          date: "2025-06-10",
          time: "12:00",
          sessionId: 2232326
        },
        {
          date: "2025-06-23",
          time: "09:00",
          sessionId: 2232964
        },
        {
          date: "2025-07-03",
          time: "09:00",
          sessionId: 2233418
        },
        {
          date: "2025-07-09",
          time: "09:00",
          sessionId: 2233419
        },
        {
          date: "2025-07-14",
          time: "12:15",
          sessionId: 2234289
        },
        {
          date: "2025-07-15",
          time: "13:00",
          sessionId: 2234155
        },
        {
          date: "2025-07-20",
          time: "09:30",
          sessionId: 2234156
        },
        {
          date: "2025-07-27",
          time: "09:00",
          sessionId: 2234603
        },
        {
          date: "2025-07-27",
          time: "10:15",
          sessionId: 2234604
        },
        {
          date: "2025-08-05",
          time: "12:20",
          sessionId: 2234619
        },
        {
          date: "2025-08-12",
          time: "10:00",
          sessionId: 2234847
        },
        {
          date: "2025-09-30",
          time: "12:15",
          sessionId: 2235323
        },
        {
          date: "2025-11-17",
          time: "13:01",
          sessionId: 2236694
        },
        {
          date: "2025-12-01",
          time: "11:00",
          sessionId: 2237288
        },
        {
          date: "2025-12-09",
          time: "11:30",
          sessionId: 2237534
        },
        {
          date: "2025-12-16",
          time: "09:00",
          sessionId: 2237779
        },
        {
          date: "2025-12-22",
          time: "10:00",
          sessionId: 2238002
        },
        {
          date: "2026-03-15",
          time: "10:00",
          sessionId: 2241563
        },
        {
          date: "2026-03-17",
          time: "10:00",
          sessionId: 2241577
        },
        {
          date: "2026-03-22",
          time: "14:00",
          sessionId: 2241871
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
