// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2229752,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק הפסקת כהונה של נושאי משרה בכירים בתקופת הכהונה הראשונית של ממשלה חדשה, התשפ\"ה-2025",
  type: "private",
  committeeId: "constitution",
  status: "agenda",
  lastUpdated: "2026-06-14",
  initiators: [
    {
      kind: "mk",
      personId: 30859,
      name: "צביקה פוגל",
      partyId: "rzp",
      factionName: "הציונות הדתית"
    },
    {
      kind: "mk",
      personId: 30867,
      name: "יצחק קרויזר",
      partyId: "otzma",
      factionName: "עוצמה יהודית בראשות איתמר בן גביר"
    },
    {
      kind: "mk",
      personId: 30877,
      name: "משה פסל",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: []
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
