// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2229710,
  syncedAt: "2026-08-12",
  officialName: "חוק רישוי שירותים ומקצועות בענף הרכב (תיקון מס' 13), התשפ\"ה-2025 ",
  type: "governmental",
  committeeId: "economy",
  status: "completed",
  summaryOfficial: "התיקון קובע הוראות שעה חדשות בנושא ייבוא רכב, המחליפות את הוראות השעה הקודמות שהיו בתוקף ממועד תחילתו של חוק רישוי שירותים ומקצועות בענף הרכב, התשע\"ו–2016, ועד ליום 18 באוגוסט 2025. הוראות השעה החדשות הן לעניין כלי הרכב שהיבואנים הזעירים רשאים לייבא, וכן לעניין חובות היבואנים הישירים לטפל בכלי רכב המיובאים על ידי יבואנים זעירים ויבואנים עקיפים או בייבוא אישי אם כלי הרכב הם מאותו תוצר שמייבאים היבואנים הישירים. ראשית, לעניין יבואנים זעירים: התיקון קובע כי יבואן זעיר יוכל לייבא גם רכב מסוג אופנוע ורכב מסוג מכונה ניידת, נוסף על רכב נוסעים ורכב מסחרי שכבר כיום הוא רשאי לייבא. בנוסף, יבואן זעיר יוכל לקבל רישיון לייבוא רכב שאינו רכב חדש, כל עוד נותרו חודשיים עד למועד האחרון לרישומו בישראל הקבוע בתקנות התעבורה ובהתאם לסוג הרכב. כמו כן, התיקון מאפשר ליבואן זעיר לייבא גם אופנוע ומכונה ניידת, וזאת בנוסף לרכב שאינו רכב חדש כאמור. נוסף על כך, התיקון מגדיל את מספר כלי הרכב שמותר ליבואן זעיר לייבא בשנה, מ-20 ל-60 כלי רכב. שנית, לגבי יבואנים ישירים, התיקון קובע כי יבואנים ישירים מחויבים לתת שירות לגבי כל רכב מתוצר שהם מייבאים אף אם יובא על ידי יבואנים עקיפים וזעירים או בייבוא אישי, ולא רק לגבי רכב מסוג רכב נוסעים ורכב מסחרי כפי שקבעה הוראת השעה הקודמת. התיקון קובע כי חובה זו לא תחול לגבי רכב מסוג מכונה ניידת. הוראות השעה החדשות יעמדו בתוקף למשך ארבע שנים, החל מיום 19 באוגוסט 2025. שר התחבורה והבטיחות בדרכים, באישור ועדת הכלכלה של הכנסת, רשאי להאריך בצו את תוקפה של כל הוראת שעה בתקופות נוספות שלא יעלו על שישה חודשים בכל פעם, אך לא יותר מ-4 שנים במצטבר לגבי כל אחת מהוראות השעה.",
  lastUpdated: "2025-09-14",
  completedDate: "2025-08-13",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-05-28",
          time: "09:00",
          sessionId: 2231636
        },
        {
          date: "2025-06-09",
          time: "10:30",
          sessionId: 2232583
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
