// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2230613,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק איסור צריכת זנות, התשפ\"ה-2025",
  type: "private",
  committeeId: "constitution",
  status: "agenda",
  lastUpdated: "2025-05-13",
  initiators: [
    {
      kind: "mk",
      personId: 30102,
      name: "מירב בן ארי",
      partyId: "yesh-atid",
      factionName: "יש עתיד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2025-06-10",
          time: "09:00",
          sessionId: 2232320
        },
        {
          date: "2025-06-18",
          time: "09:00",
          sessionId: 2233107
        },
        {
          date: "2025-06-19",
          time: "09:30",
          sessionId: 2233032
        },
        {
          date: "2025-06-24",
          time: "13:30",
          sessionId: 2232972
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
