// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2230568,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק המרכז להנצחת זכרו של רבי נחמן מברסלב, התשפ\"ו-2026",
  type: "private",
  committeeId: "education",
  status: "agenda",
  lastUpdated: "2026-07-19",
  initiators: [
    {
      kind: "mk",
      personId: 30832,
      name: "אליהו רביבו",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2026-07-12",
          time: "14:30",
          sessionId: 2245124
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2026-07-13",
          time: "10:30",
          sessionId: 2245182
        }
      ]
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
