// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2231609,
  syncedAt: "2026-08-12",
  officialName: "חוק חובת המכרזים (תיקון מס' 24 – הוראת שעה) (תיקון מס' 2), התשפ\"ה–2025",
  type: "private",
  committeeId: "constitution",
  status: "completed",
  summaryOfficial: "החוק מאריך בשלוש שנים נוספות, עד ל-15 ביולי 2028, את הוראת השעה המסמיכה את הממשלה לקבוע בתקנות, באישור ועדת החוקה של הכנסת, הוראות לעניין העדפה של תוצרת הארץ ברכישת טקסטיל בעבור מערכת הביטחון והמשרד לביטחון הפנים. מכוח הוראה שקיימת בהוראת השעה המקורית, שר האוצר יהיה מוסמך להאריך תקופה זו, בצו, באישור ועדת החוקה של הכנסת, לפרק זמן של שנתיים נוספות.",
  lastUpdated: "2025-09-03",
  completedDate: "2025-07-15",
  initiators: [
    {
      kind: "mk",
      personId: 30893,
      name: "עפיף עבד",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30682,
      name: "מיכאל מרדכי ביטון",
      partyId: "national-unity",
      factionName: "המחנה הממלכתי"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-07-13",
          time: "11:00",
          sessionId: 2234147
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-07-15",
          time: "11:40",
          sessionId: 2234162
        },
        {
          date: "2025-07-15",
          time: "13:50",
          sessionId: 2234445
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
