// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2231205,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק לתיקון פקודת התעבורה (שירותי תחבורה שיתופית מקוונת), התשפ\"ה-2025",
  type: "private",
  committeeId: "economy",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2026-03-16",
  initiators: [
    {
      kind: "mk",
      personId: 30877,
      name: "משה פסל",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2026-01-26",
          time: "12:15",
          sessionId: 2239714
        },
        {
          date: "2026-01-26",
          time: "15:45",
          sessionId: 2239829
        },
        {
          date: "2026-02-02",
          time: "12:00",
          sessionId: 2239836
        },
        {
          date: "2026-02-10",
          time: "10:45",
          sessionId: 2240139
        },
        {
          date: "2026-02-24",
          time: "11:00",
          sessionId: 2240923
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
