// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2231844,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק ההתייעלות הכלכלית (תיקוני חקיקה להשגת יעדי התקציב לשנות התקציב 2023 ו-2024) (תיקון מס' 2), התשפ\"ה-2025 ",
  type: "governmental",
  committeeId: "finance",
  status: "agenda",
  lastUpdated: "2025-06-29",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2025-06-09",
          time: "12:00",
          sessionId: 2232593
        }
      ]
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
