// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2233694,
  syncedAt: "2026-08-12",
  officialName: "חוק התוכנית לסיוע כלכלי (הוראת שעה - חרבות ברזל), התשפ\"ה-2025",
  type: "governmental",
  committeeId: "finance",
  status: "completed",
  summaryOfficial: "החוק דומה בעיקרו להסדר שנקבע בחוק התוכנית לסיוע כלכלי (הוראת שעה – חרבות ברזל), התשפ\"ד–2023, החוק קובע מנגנון פיצוי לעסקים ולעובדים שנפגעו ישירות או בעקיפין במהלך מבצע \"עם כלביא\". עסקים שמחזור עסקאותיהם ירד בשיעור של לפחות 25%, ואינם עולים על 400 מיליון ש\"ח בשנה, זכאים לפיצוי בגין הוצאות קבועות, לרבות שכר. הוחל מסלול לפיצוי בגין נזק עקיף בעקבות נזק ישיר לעסק, וכן פיצוי לבעלי דירות שנגרם להן נזק מלחמה והושכרו טרם הפגיעה. לעובדים – נקבעו הסדרים ייחודיים לדמי אבטלה, כולל לחל\"ת של 12 ימים, גם אם העובד עבד עד יומיים בתקופה זו, ובכלל זה קיצור תקופת האכשרה. בני 67 ומעלה זכאים למענק יומי של עד 134 ש\"ח. נשים מוגנות לפי חוק עבודת נשים לא ייפגעו בזכויותיהן בשל היעדרות הנובעת ממצב חירום או סגירת מסגרות לילדים. החוק כולל הסדרים גם עבור עצמאים, אנשים עם מוגבלות, חיילים משוחררים ומפונים שמיצו את זכאותם לדמי אבטלה.",
  lastUpdated: "2025-08-07",
  completedDate: "2025-07-21",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-07-02",
          time: "10:30",
          sessionId: 2233691
        },
        {
          date: "2025-07-06",
          time: "10:30",
          sessionId: 2233711
        },
        {
          date: "2025-07-07",
          time: "10:00",
          sessionId: 2233712
        },
        {
          date: "2025-07-08",
          time: "10:50",
          sessionId: 2233715
        },
        {
          date: "2025-07-14",
          time: "10:00",
          sessionId: 2234137
        },
        {
          date: "2025-07-15",
          time: "10:00",
          sessionId: 2234140
        },
        {
          date: "2025-07-20",
          time: "10:00",
          sessionId: 2234495
        },
        {
          date: "2025-07-21",
          time: "10:00",
          sessionId: 2234549
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
