// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2233960,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק התפזרות הכנסת העשרים וחמש, התשפ\"ה-2025",
  type: "private",
  committeeId: "knesset-committee",
  status: "agenda",
  lastUpdated: "2026-05-20",
  initiators: [
    {
      kind: "mk",
      personId: 23635,
      name: "פנינה תמנו",
      partyId: "national-unity",
      factionName: "המחנה הממלכתי"
    },
    {
      kind: "mk",
      personId: 30657,
      name: "בנימין גנץ",
      partyId: "national-unity",
      factionName: "המחנה הממלכתי"
    },
    {
      kind: "mk",
      personId: 30683,
      name: "חילי טרופר",
      partyId: "national-unity",
      factionName: "המחנה הממלכתי"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2026-06-01",
          time: "08:30",
          sessionId: 2243644
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
