// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2233165,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק לשיקום מהיר של מבנים שניזוקו במלחמת עם כלביא (תיקוני חקיקה), התשפ\"ה-2025",
  type: "private",
  committeeId: "interior-environment",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2026-01-06",
  initiators: [
    {
      kind: "mk",
      personId: 23641,
      name: "יעקב אשר",
      partyId: "utj",
      factionName: "יהדות התורה"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2025-12-25",
          time: "10:00",
          sessionId: 2237919
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
