// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2234082,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק-יסוד: השפיטה (תיקון - רשות ערעור למדינה על זיכוי אדם בפלילים)",
  type: "private",
  committeeId: "constitution",
  status: "agenda",
  lastUpdated: "2025-12-24",
  initiators: [
    {
      kind: "mk",
      personId: 30693,
      name: "איתן גינזבורג",
      partyId: "national-unity",
      factionName: "המחנה הממלכתי"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2025-12-31",
          time: "09:00",
          sessionId: 2238314
        },
        {
          date: "2026-01-07",
          time: "09:00",
          sessionId: 2238902
        },
        {
          date: "2026-01-12",
          time: "11:15",
          sessionId: 2239018
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
