// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2237628,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק ועדת חקירה ממלכתית-לאומית לאירועי טבח שמיני עצרת התשפ״ד (טבח 7 באוקטובר 2023), התשפ\"ו-2026",
  type: "private",
  committeeId: "constitution",
  status: "agenda",
  lastUpdated: "2026-07-06",
  initiators: [
    {
      kind: "mk",
      personId: 30710,
      name: "אריאל קלנר",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2025-12-29",
          time: "12:15",
          sessionId: 2238301
        },
        {
          date: "2025-12-30",
          time: "13:45",
          sessionId: 2238390
        },
        {
          date: "2026-01-19",
          time: "09:00",
          sessionId: 2239033
        },
        {
          date: "2026-02-03",
          time: "09:00",
          sessionId: 2239940
        },
        {
          date: "2026-02-11",
          time: "09:00",
          sessionId: 2239943
        },
        {
          date: "2026-02-22",
          time: "14:00",
          sessionId: 2240993
        },
        {
          date: "2026-03-05",
          time: "09:00",
          sessionId: 2241015
        },
        {
          date: "2026-03-19",
          time: "09:00",
          sessionId: 2241633
        },
        {
          date: "2026-05-13",
          time: "10:00",
          sessionId: 2242952
        },
        {
          date: "2026-05-19",
          time: "14:30",
          sessionId: 2243234
        },
        {
          date: "2026-05-26",
          time: "13:30",
          sessionId: 2243377
        },
        {
          date: "2026-06-02",
          time: "14:00",
          sessionId: 2243641
        },
        {
          date: "2026-06-09",
          time: "11:00",
          sessionId: 2243973
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "inProgress",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
