// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2239258,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק תגמול למשרתים בשירות צבאי או אזרחי באקדמיה, התשפ\"ה-2024",
  type: "private",
  committeeId: "education",
  status: "agenda",
  lastUpdated: "2026-01-13",
  initiators: [
    {
      kind: "mk",
      personId: 30710,
      name: "אריאל קלנר",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30867,
      name: "יצחק קרויזר",
      partyId: "otzma",
      factionName: "עוצמה יהודית בראשות איתמר בן גביר"
    },
    {
      kind: "mk",
      personId: 30863,
      name: "שרון ניר",
      partyId: "yisrael-beiteinu",
      factionName: "ישראל ביתנו"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2026-01-20",
          time: "14:00",
          sessionId: 2239274
        },
        {
          date: "2026-02-24",
          time: "13:00",
          sessionId: 2240902
        }
      ]
    },
    {
      stage: "first",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "notReached",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
