// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2240529,
  syncedAt: "2026-08-12",
  officialName: "פרק ג' (צמצום ההון השחור), סימן ג' (חובת הצהרה של נותני שירותים פיננסיים) מתוך הצעת חוק ההתייעלות הכלכלית (תיקוני חקיקה להשגת יעדי התקציב לשנת התקציב 2026), התשפ\"ו-2026 [פוצלה לפי סעיף 84(ב) לתקנון]",
  type: "governmental",
  committeeId: "constitution",
  status: "agenda",
  lastUpdated: "2026-03-25",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2026-02-15",
          time: "13:00",
          sessionId: 2240548
        },
        {
          date: "2026-02-15",
          time: "12:30",
          sessionId: 2240547
        },
        {
          date: "2026-03-11",
          time: "09:00",
          sessionId: 2241493
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "inProgress",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
