// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2240537,
  syncedAt: "2026-08-12",
  officialName: "פרק ד' (התחשבנות בין בתי חולים לקופות חולים לשנים 2026 עד 2030) (רק סעיף 16) מתוך הצעת חוק ההתייעלות הכלכלית (תיקוני חקיקה להשגת יעדי התקציב לשנת התקציב 2026) התשפ\"ו-2026 [פוצלה לפי סעיף 84(ב) לתקנון] ",
  type: "governmental",
  committeeId: "health",
  status: "dropped",
  offPipelineReason: "מוזגה עם הצעת חוק אחרת",
  lastUpdated: "2026-03-18",
  initiators: [
    {
      kind: "ministry",
      name: "משרד ממשלתי"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2026-03-11",
          time: "10:15",
          sessionId: 2241519
        },
        {
          date: "2026-03-12",
          time: "10:00",
          sessionId: 2241479
        },
        {
          date: "2026-03-18",
          time: "09:00",
          sessionId: 2241600
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "inProgress",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
