// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2243179,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק התפזרות הכנסת העשרים וחמש, התשפ\"ו-2026",
  type: "private",
  committeeId: "knesset-committee",
  status: "agenda",
  lastUpdated: "2026-06-02",
  initiators: [
    {
      kind: "mk",
      personId: 30701,
      name: "אופיר כץ",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 11835,
      name: "אורי מקלב",
      partyId: "utj",
      factionName: "יהדות התורה"
    },
    {
      kind: "mk",
      personId: 30601,
      name: "ינון אזולאי",
      partyId: "shas",
      factionName: "התאחדות הספרדים שומרי תורה תנועתו של מרן הרב עובדיה יוסף זצ\"ל"
    }
  ],
  stages: [
    {
      stage: "preliminary",
      state: "completed",
      discussions: []
    },
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "inProgress",
      discussions: [
        {
          date: "2026-06-01",
          time: "08:30",
          sessionId: 2243644
        }
      ]
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
