// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2244462,
  syncedAt: "2026-08-12",
  officialName: "חוק הבחירות לכנסת העשרים ושש (הוראות מיוחדות ותיקוני חקיקה), התשפ\"ו-2026",
  type: "committee",
  committeeId: "constitution",
  status: "completed",
  summaryOfficial: "חוק הבחירות לכנסת ה-26 נחקק על רקע מצב ביטחוני מיוחד ועל כן נקבעו בו הוראות שעה ייחודיות, ובהן: נקבע הסדר הצבעה ייעודי לתושבים שהתפנו מבתיהם עקב המצב הביטחוני, הוענקו סמכויות מיוחדות ליושב ראש ועדת הבחירות המרכזית לקבוע הוראות הנוגעות להתנהלות הבחירות בעת חירום, נקבעו הקלות בנוגע להעסקת עובדי רשויות ציבוריות בוועדות הבחירות, וכן התאפשרה גמישות בנושא המכרזים עבור ועדת הבחירות המרכזית. בנוסף לכך, נקבעו בחוק מספר תיקוני קבע בתחומים שונים, וביניהם: יושב ראש ועדת הבחירות הוסמך לקבוע אגרות שייגבו עבור הגשת הליכים משפטיים מסוימים המובאים בפניו, והוסמך בנוסף גם למחוק מרשימת מועמדים לכנסת מועמד שאינו כשיר להתמודד מסיבות טכניות. בתחום התעמולה, נקבע כי חובת השקיפות בנוגע לזהות המפרסם של מודעת בחירות תחול בכל עת ולא רק בתקופת בחירות, וכי צילום כשלעצמו בלשכת נבחר ציבור לא ייחשב כשימוש אסור בנכסי ציבור. בנוסף, בשל הנגישות שקיימת היום ליצור ולערוך תוכן, בין השאר תוך שימוש בבינה מלאכותית, נקבעה הוראת שעה ובה חובת שקיפות חדשה. לפי הוראה זו, מי שמפרסם תעמולת בחירות שנוצרה או שנערכה באופן מהותי באמצעים דיגיטליים, אך כוללת תוכן שעשוי להיחזות כאילו תועד במקור כמו הצגה של דמות מקום או אירוע, חייב לצרף גילוי ברור ובולט שיבהיר לציבור שהתוכן שבתעמולה לא תועד במקור.",
  lastUpdated: "2026-07-28",
  completedDate: "2026-07-13",
  initiators: [],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: [
        {
          date: "2026-06-22",
          time: "09:00",
          sessionId: 2244300
        },
        {
          date: "2026-06-28",
          time: "13:10",
          sessionId: 2244543
        },
        {
          date: "2026-06-29",
          time: "12:05",
          sessionId: 2244552
        },
        {
          date: "2026-06-30",
          time: "10:50",
          sessionId: 2244743
        },
        {
          date: "2026-07-01",
          time: "09:00",
          sessionId: 2244554
        }
      ]
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "completed",
      discussions: [
        {
          date: "2026-07-06",
          time: "09:30",
          sessionId: 2244814
        },
        {
          date: "2026-07-06",
          time: "12:00",
          sessionId: 2244961
        },
        {
          date: "2026-07-06",
          time: "09:00",
          sessionId: 2244876
        },
        {
          date: "2026-07-12",
          time: "16:30",
          sessionId: 2245169
        },
        {
          date: "2026-07-13",
          time: "22:00",
          sessionId: 2245195
        },
        {
          date: "2026-07-15",
          time: "16:00",
          sessionId: 2245223
        }
      ]
    },
    {
      stage: "secondThird",
      state: "completed",
      discussions: []
    }
  ]
};
