// GENERATED BY scripts/sync-all.mjs - DO NOT EDIT BY HAND.
// Everything here comes from the Knesset's open data API. A thin
// record: no vote tallies ( curated bills get those richly, via
// sync-bill ). Editorial content, when this bill earns one, lives
// in src/content/bills/editorial/ and is never touched by a sync.
//
// Regenerate everything:  node scripts/sync-all.mjs
import type { BillFacts } from "../../types";

export const facts: BillFacts = {
  billId: 2245052,
  syncedAt: "2026-08-12",
  officialName: "הצעת חוק היועץ המשפטי לממשלה והתובע הכללי (מינוי, כהונה, תפקידים וסמכויות), התשפ\"ו–2026 ",
  type: "private",
  committeeId: "constitution",
  status: "agenda",
  lastUpdated: "2026-07-07",
  initiators: [
    {
      kind: "mk",
      personId: 30842,
      name: "חנוך דב מלביצקי",
      partyId: "likud",
      factionName: "הליכוד"
    },
    {
      kind: "mk",
      personId: 30867,
      name: "יצחק קרויזר",
      partyId: "otzma",
      factionName: "עוצמה יהודית בראשות איתמר בן גביר"
    },
    {
      kind: "mk",
      personId: 30710,
      name: "אריאל קלנר",
      partyId: "likud",
      factionName: "הליכוד"
    }
  ],
  stages: [
    {
      stage: "firstPrep",
      state: "completed",
      discussions: []
    },
    {
      stage: "first",
      state: "completed",
      discussions: []
    },
    {
      stage: "secondThirdPrep",
      state: "inProgress",
      discussions: []
    },
    {
      stage: "secondThird",
      state: "notReached",
      discussions: []
    }
  ]
};
